// frontend/src/components/TagManager.vue
<script setup>
import { ref, computed, watch, onMounted } from 'vue'
import axios from 'axios'
import { useI18n } from 'vue-i18n'
import { message, Modal } from 'ant-design-vue'
import Pagination from './Pagination.vue'
import { useLibraryStore } from '@/store/library'

const { t } = useI18n()
const libraryStore = useLibraryStore()
const socket = libraryStore.socket

const props = defineProps({
  types: { type: Array, required: true }
})

// listing state
const tags = ref([])
const selectedTypeId = ref(null)
const isLoading = ref(false)
const currentPage = ref(1)
const totalPages = ref(1)
const totalTags = ref(0)
const perPage = ref(20)

// editor state
const showModal = ref(false)
const editingTag = ref(null)
const tagForm = ref({
  id: null,
  name: '',
  description: '',
  type_id: null,
  parent_id: null,
  aliases: [],
  newAlias: ''
})

// parent remote suggest
const parentSuggestions = ref([])
const isParentLoading = ref(false)
const loadParentSuggestions = async (query = '') => {
  if (!tagForm.value.type_id) return
  try {
    isParentLoading.value = true
    const { data } = await axios.get('/api/v1/tags/suggest', {
      params: { q: query, type_id: tagForm.value.type_id, limit: 20 }
    })
    parentSuggestions.value = data.filter(x => x.id !== tagForm.value.id)
  } catch (e) {
    console.error('Failed to load parent suggestions:', e)
  } finally {
    isParentLoading.value = false
  }
}

// file change state
const showFileChangeModal = ref(false)
const fileChangeTag = ref(null)
const fileChangeAction = ref('delete') // delete | rename | split
const newTagName = ref('')
const newTagNames = ref([])
const newTagNameInput = ref('')
const isFileChanging = ref(false)
const isPreviewLoading = ref(false)
const previewData = ref({ impacted: 0, examples: [] })

// merge state
const showMergeModal = ref(false)
const mergeSourceTag = ref(null)
const mergeTarget = ref(null)
const isMerging = ref(false)
const mergeSuggestions = ref([])

const fileChangeOkDisabled = computed(() => {
  if (!fileChangeTag.value) return true
  if (fileChangeAction.value === 'rename') return !newTagName.value.trim()
  if (fileChangeAction.value === 'split') return newTagNames.value.length === 0
  return false
})

const fileChangeTagName = computed(() => fileChangeTag.value?.name || '')

const fetchTags = async (page = 1) => {
  isLoading.value = true
  try {
    const params = { page, per_page: perPage.value, type_id: selectedTypeId.value ?? undefined }
    const { data } = await axios.get('/api/v1/tags', { params })
    tags.value = data.tags
    currentPage.value = data.page
    totalPages.value = data.pages
    totalTags.value = data.total
  } catch (e) {
    console.error('Failed to fetch tags:', e)
    message.error(t('errorFetchingTags'))
  } finally {
    isLoading.value = false
  }
}

const handlePageChange = (page) => fetchTags(page)
watch(selectedTypeId, () => fetchTags(1))

onMounted(() => {
  fetchTags()
  socket.on('connect', () => console.log('Socket connected'))
  socket.on('disconnect', () => console.log('Socket disconnected'))
  socket.on('connect_error', (e) => console.error('Socket error:', e))
})

const getTypeName = (typeId) => props.types.find(ti => ti.id === typeId)?.name || t('none')
const getParentName = (parentId) => {
  if (!parentId) return t('none')
  const p = tags.value.find(tg => tg.id === parentId)
  return p ? p.name : t('none')
}

const openCreateModal = () => {
  editingTag.value = null
  tagForm.value = {
    id: null,
    name: '',
    description: '',
    type_id: selectedTypeId.value ?? props.types[0]?.id ?? null,
    parent_id: null,
    aliases: [],
    newAlias: ''
  }
  parentSuggestions.value = []
  if (tagForm.value.type_id) loadParentSuggestions('')
  showModal.value = true
}

const openEditModal = (tag) => {
  editingTag.value = { ...tag }
  tagForm.value = {
    id: tag.id,
    name: tag.name,
    description: tag.description || '',
    type_id: tag.type_id,
    parent_id: tag.parent_id,
    aliases: [...tag.aliases],
    newAlias: ''
  }
  parentSuggestions.value = []
  if (tagForm.value.type_id) loadParentSuggestions('')
  showModal.value = true
}

const closeModal = () => { showModal.value = false; editingTag.value = null }

const addAlias = () => {
  const a = (tagForm.value.newAlias || '').trim()
  if (!a) return
  if (tagForm.value.aliases.includes(a)) { message.warning('Alias already exists'); return }
  tagForm.value.aliases.push(a)
  tagForm.value.newAlias = ''
}
const removeAlias = (a) => { tagForm.value.aliases = tagForm.value.aliases.filter(x => x !== a) }

const saveTag = async () => {
  if (!tagForm.value.name || !tagForm.value.type_id) { message.warning(t('tagNameAndTypeRequired')); return }
  const payload = { name: tagForm.value.name, description: tagForm.value.description, type_id: tagForm.value.type_id, parent_id: tagForm.value.parent_id, aliases: tagForm.value.aliases }
  try {
    if (editingTag.value) await axios.put(`/api/v1/tags/${editingTag.value.id}`, payload)
    else await axios.post('/api/v1/tags', payload)
    message.success(t('settingsSavedSuccessfully'))
    closeModal(); fetchTags(currentPage.value)
  } catch (e) {
    console.error('Failed to save tag:', e)
    message.error(t('errorSavingTag') + (e.response?.data?.error || ''))
  }
}

const deleteTag = (tag) => {
  Modal.confirm({
    title: t('confirmDeletionTitle'),
    content: t('confirmDeleteTagWithUsage', { name: tag.name, count: tag.usage_count ?? 0 }),
    okType: 'danger',
    onOk: async () => {
      try {
        await axios.delete(`/api/v1/tags/${tag.id}`)
        message.success(t('settingsSavedSuccessfully'))
        fetchTags(currentPage.value)
      } catch (e) {
        console.error('Failed to delete tag:', e)
        message.error(t('errorDeletingTag') + (e.response?.data?.error || ''))
      }
    }
  })
}

// file-change modal
const openFileChangeModal = (tag) => { fileChangeTag.value = { ...tag }; fileChangeAction.value = 'delete'; newTagName.value=''; newTagNames.value=[]; newTagNameInput.value=''; previewData.value={impacted:0,examples:[]}; showFileChangeModal.value = true }
const closeFileChangeModal = () => { showFileChangeModal.value=false; fileChangeTag.value=null; fileChangeAction.value='delete'; newTagName.value=''; newTagNames.value=[]; newTagNameInput.value=''; isFileChanging.value=false }
const loadPreview = async () => {
  if (!fileChangeTag.value) return
  try {
    isPreviewLoading.value = true
    let endpoint, payload
    if (fileChangeAction.value === 'split') { endpoint = `/api/v1/tags/${fileChangeTag.value.id}/split/preview`; payload = { new_tag_names: newTagNames.value } }
    else { endpoint = `/api/v1/tags/${fileChangeTag.value.id}/file-change/preview`; payload = { action: fileChangeAction.value, new_name: fileChangeAction.value === 'rename' ? newTagName.value.trim() : undefined } }
    const { data } = await axios.post(endpoint, payload)
    previewData.value = data
  } catch (e) {
    console.error('Failed to load preview:', e)
    message.error(t('errorLoadingPreview') + (e.response?.data?.error || ''))
  } finally { isPreviewLoading.value = false }
}
const executeFileChange = async () => {
  if (!fileChangeTag.value) return
  if (fileChangeAction.value === 'rename' && !newTagName.value.trim()) { message.warning(t('pleaseEnterNewTagName')); return }
  if (fileChangeAction.value === 'split' && newTagNames.value.length === 0) { message.warning(t('noNewTagsAdded')); return }
  try {
    isFileChanging.value = true
    let endpoint, payload
    if (fileChangeAction.value === 'split') { endpoint = `/api/v1/tags/${fileChangeTag.value.id}/split`; payload = { new_tag_names: newTagNames.value } }
    else { endpoint = `/api/v1/tags/${fileChangeTag.value.id}/file-change`; payload = { action: fileChangeAction.value, new_name: fileChangeAction.value === 'rename' ? newTagName.value.trim() : undefined } }
    await axios.post(endpoint, payload)
    message.success(t('operationSubmittedCheckTaskManager'))
    closeFileChangeModal()
  } catch (e) {
    console.error('Failed to start operation:', e)
    message.error(t('errorStartingOperation') + (e.response?.data?.error || e.message))
  } finally { isFileChanging.value = false }
}
const addNewTagName = () => { const n = newTagNameInput.value.trim(); if (n && !newTagNames.value.includes(n)) { newTagNames.value.push(n); newTagNameInput.value='' } }
const removeNewTagName = (n) => { newTagNames.value = newTagNames.value.filter(x => x !== n) }

// merge modal
const openMergeModal = (tag) => { mergeSourceTag.value = tag; mergeTarget.value=null; mergeSuggestions.value=[]; showMergeModal.value = true }
const searchMergeTargets = async (q='') => { if (!mergeSourceTag.value) return; const { data } = await axios.get('/api/v1/tags/suggest', { params: { q, type_id: mergeSourceTag.value.type_id, limit: 20 } }); mergeSuggestions.value = data.filter(x => x.id !== mergeSourceTag.value.id) }
const executeMerge = async () => { if (!mergeSourceTag.value || !mergeTarget.value) return; try { isMerging.value = true; await axios.post(`/api/v1/tags/${mergeSourceTag.value.id}/merge`, { target_tag_id: mergeTarget.value }); message.success(t('mergeSuccess')); showMergeModal.value = false; fetchTags(currentPage.value) } catch (e) { console.error('Failed to merge:', e); message.error(t('mergeError') + (e.response?.data?.error || '')) } finally { isMerging.value = false } }
</script>

<template>
  <a-space direction="vertical" size="large" class="w-full">
    <a-card class="shadow-sm">
      <a-space direction="vertical" size="large" class="w-full">
        <div class="flex flex-wrap items-center justify-between gap-3">
          <a-form layout="inline" @submit.prevent>
            <a-form-item :label="$t('filterByType')">
              <a-select v-model:value="selectedTypeId" allow-clear style="min-width: 220px">
                <a-select-option :value="null">{{ $t('allTypes') }}</a-select-option>
                <a-select-option v-for="type in types" :key="type.id" :value="type.id">{{ type.name }}</a-select-option>
              </a-select>
            </a-form-item>
          </a-form>
          <a-button type="primary" @click="openCreateModal">+ {{ $t('newTag') }}</a-button>
        </div>

        <a-table :data-source="tags" :loading="isLoading" :row-key="r => r.id" :pagination="false" size="middle" :locale="{ emptyText: $t('noTagsFoundForType') }">
          <a-table-column :title="$t('name')" dataIndex="name" key="name" />
          <a-table-column :title="$t('description')" key="description">
            <template #default="{ record }"><a-typography-text type="secondary">{{ record.description || '-' }}</a-typography-text></template>
          </a-table-column>
          <a-table-column :title="$t('type')" key="type"><template #default="{ record }">{{ getTypeName(record.type_id) }}</template></a-table-column>
          <a-table-column :title="$t('parentTag')" key="parent"><template #default="{ record }">{{ getParentName(record.parent_id) }}</template></a-table-column>
          <a-table-column :title="$t('aliases')" key="aliases">
            <template #default="{ record }">
              <a-space wrap>
                <a-tag v-for="alias in record.aliases" :key="alias">{{ alias }}</a-tag>
                <a-typography-text v-if="!record.aliases.length" type="secondary">-</a-typography-text>
              </a-space>
            </template>
          </a-table-column>
          <a-table-column :title="$t('usage')" key="usage_count"><template #default="{ record }"><a-tag color="blue">{{ record.usage_count }}</a-tag></template></a-table-column>
          <a-table-column :title="$t('actions')" key="actions" :width="320">
            <template #default="{ record }">
              <a-space size="small" wrap>
                <a-button size="small" @click="openEditModal(record)">{{ $t('edit') }}</a-button>
                <a-button size="small" type="default" @click="openFileChangeModal(record)">{{ $t('fileChange') }}</a-button>
                <a-button size="small" type="default" @click="openMergeModal(record)">{{ $t('mergeTag') }}</a-button>
                <a-button size="small" danger @click="deleteTag(record)">{{ $t('delete') }}</a-button>
              </a-space>
            </template>
          </a-table-column>
        </a-table>

        <div class="flex justify-end">
          <Pagination :current-page="currentPage" :total-pages="totalPages" @page-changed="handlePageChange" />
        </div>
      </a-space>
    </a-card>
  </a-space>

  <a-modal v-model:open="showModal" :title="editingTag ? `${$t('edit')} ${$t('tag')}` : $t('newTag')" :ok-text="$t('save')" :cancel-text="$t('cancel')" :confirm-loading="false" :width="640" @ok="saveTag" @cancel="closeModal">
    <a-form layout="vertical">
      <a-form-item :label="$t('name')" :required="true"><a-input v-model:value="tagForm.name" /></a-form-item>
      <a-form-item :label="$t('description')"><a-textarea v-model:value="tagForm.description" :rows="3" /></a-form-item>
      <a-form-item :label="$t('type')" :required="true">
        <a-select v-model:value="tagForm.type_id" :dropdown-match-select-width="false">
          <a-select-option v-for="type in types" :key="type.id" :value="type.id">{{ type.name }}</a-select-option>
        </a-select>
      </a-form-item>
      <a-form-item :label="$t('parentTag')">
        <a-select v-model:value="tagForm.parent_id" show-search allow-clear :filter-option="false" :placeholder="t('none')" :not-found-content="isParentLoading ? $t('loading') : null" @search="loadParentSuggestions" @focus="loadParentSuggestions('')" :dropdown-match-select-width="false">
          <a-select-option :value="null">{{ t('none') }}</a-select-option>
          <a-select-option v-for="parent in parentSuggestions" :key="parent.id" :value="parent.id">{{ parent.name }} ({{ getTypeName(parent.type_id) }})</a-select-option>
        </a-select>
      </a-form-item>
      <a-form-item :label="$t('aliases')">
        <a-space align="start" class="w-full">
          <a-input v-model:value="tagForm.newAlias" :placeholder="$t('aliases')" @pressEnter.prevent="addAlias" />
          <a-button type="dashed" @click="addAlias">{{ $t('add') }}</a-button>
        </a-space>
        <div class="mt-2 flex flex-wrap gap-2">
          <a-tag v-for="alias in tagForm.aliases" :key="alias" closable @close.prevent="removeAlias(alias)">{{ alias }}</a-tag>
        </div>
      </a-form-item>
    </a-form>
  </a-modal>

  <a-modal v-model:open="showFileChangeModal" :title="`${$t('fileChange')} - ${fileChangeTagName}`" :cancel-text="$t('cancel')" :ok-button-props="{ disabled: fileChangeOkDisabled }" :confirm-loading="isFileChanging" width="720px" @ok="executeFileChange" @cancel="closeFileChangeModal">
    <a-form layout="vertical">
      <a-form-item :label="$t('selectAction')">
        <a-radio-group v-model:value="fileChangeAction">
          <a-radio value="delete">{{ $t('deleteTagFromFilenames') }} [{{ fileChangeTagName }}]</a-radio>
          <a-radio value="rename">{{ $t('renameTagInFilenames') }} [{{ fileChangeTagName }}]</a-radio>
          <a-radio value="split">{{ $t('splitTagInFilenames') }} [{{ fileChangeTagName }}]</a-radio>
        </a-radio-group>
      </a-form-item>

      <a-form-item v-if="fileChangeAction === 'rename'" :label="$t('newTagName')">
        <a-input v-model:value="newTagName" :placeholder="fileChangeTagName" />
      </a-form-item>

      <div v-if="fileChangeAction === 'split'" class="space-y-4">
        <a-form-item :label="$t('addNewTagName')">
          <a-space class="w-full">
            <a-input v-model:value="newTagNameInput" :placeholder="$t('newTagNamePlaceholder')" @pressEnter.prevent="addNewTagName" />
            <a-button type="dashed" @click="addNewTagName">{{ $t('add') }}</a-button>
          </a-space>
        </a-form-item>

        <div v-if="newTagNames.length > 0" class="space-y-2 max-h-48 overflow-y-auto">
          <a-list :data-source="newTagNames" size="small" bordered>
            <template #renderItem="{ item }">
              <a-list-item class="flex items-center justify-between">
                <a-typography-text>[{{ item }}]</a-typography-text>
                <a-button type="text" danger size="small" @click="removeNewTagName(item)">{{ $t('delete') }}</a-button>
              </a-list-item>
            </template>
          </a-list>
        </div>
      </div>

      <a-space direction="vertical" class="w-full">
        <a-button :loading="isPreviewLoading" @click="loadPreview">{{ $t('preview') }}</a-button>
        <div v-if="previewData">
          <a-typography-paragraph>
            {{ $t('impactedFiles') }}: <a-typography-text strong>{{ previewData.impacted }}</a-typography-text>
          </a-typography-paragraph>
          <a-list v-if="previewData.examples && previewData.examples.length" :data-source="previewData.examples" size="small" bordered>
            <template #renderItem="{ item }">
              <a-list-item>
                <div class="flex flex-col"><span><strong>OLD:</strong> {{ item.old }}</span><span><strong>NEW:</strong> {{ item.new }}</span></div>
              </a-list-item>
            </template>
          </a-list>
        </div>
        <a-alert type="warning" show-icon class="mt-2" :message="$t('warningFileRename')" />
      </a-space>
    </a-form>
  </a-modal>

  <a-modal v-model:open="showMergeModal" :title="$t('mergeTag')" :ok-text="$t('confirmMerge')" :cancel-text="$t('cancel')" :confirm-loading="isMerging" @ok="executeMerge" @cancel="() => (showMergeModal.value = false)">
    <a-form layout="vertical">
      <a-form-item :label="$t('selectTargetTag')">
        <a-select v-model:value="mergeTarget" show-search :filter-option="false" :placeholder="$t('selectTargetTag')" @search="searchMergeTargets" @focus="searchMergeTargets('')">
          <a-select-option v-for="opt in mergeSuggestions" :key="opt.id" :value="opt.id">{{ opt.name }} ({{ $t('usage') }}: {{ opt.usage_count }})</a-select-option>
        </a-select>
      </a-form-item>
    </a-form>
  </a-modal>
</template>

// apps/web/src/components/tags/TagManager.tsx
import { Alert, Button, Card, Form, Input, List, Modal, Pagination, Radio, Select, Space, Table, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { http } from '@/api/http'
import type { TagType } from '@/components/tags/TagTypeManager'
import { useLibraryStore } from '@/store/library'

export type TagSuggestion = {
  id: number
  name: string
  type_id: number
  usage_count: number
}

export type TagRecord = {
  id: number
  name: string
  description: string | null
  type_id: number
  parent_id: number | null
  aliases: string[]
  usage_count: number
}

type TagListResponse = {
  tags: TagRecord[]
  total: number
  page: number
  pages: number
}

type PreviewResult = { impacted: number; examples: Array<{ old: string; new: string }> }

type FileChangeAction = 'delete' | 'rename' | 'split'

export type TagManagerProps = {
  types: TagType[]
}

type TagFormState = {
  id: number | null
  name: string
  description: string
  type_id: number | null
  parent_id: number | null
  aliases: string[]
  newAlias: string
}

const unique = (values: string[]) => {
  const seen = new Set<string>()
  const list: string[] = []
  for (const value of values) {
    const trimmed = String(value || '').trim()
    if (!trimmed) continue
    if (seen.has(trimmed)) continue
    seen.add(trimmed)
    list.push(trimmed)
  }
  return list
}

export default function TagManager({ types }: TagManagerProps) {
  const { t } = useTranslation()
  const checkActiveTasks = useLibraryStore((state) => state.checkActiveTasks)

  const [tags, setTags] = useState<TagRecord[]>([])
  const [selectedTypeId, setSelectedTypeId] = useState<number | null>(null)
  const [loading, setLoading] = useState(false)
  const [currentPage, setCurrentPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)
  const [totalTags, setTotalTags] = useState(0)
  const perPage = 20

  const [editorOpen, setEditorOpen] = useState(false)
  const [editingTag, setEditingTag] = useState<TagRecord | null>(null)
  const [tagForm, setTagForm] = useState<TagFormState>({
    id: null,
    name: '',
    description: '',
    type_id: null,
    parent_id: null,
    aliases: [],
    newAlias: ''
  })

  const [parentSuggestions, setParentSuggestions] = useState<TagSuggestion[]>([])
  const [parentLoading, setParentLoading] = useState(false)

  const [fileChangeOpen, setFileChangeOpen] = useState(false)
  const [fileChangeTag, setFileChangeTag] = useState<TagRecord | null>(null)
  const [fileChangeAction, setFileChangeAction] = useState<FileChangeAction>('delete')
  const [newTagName, setNewTagName] = useState('')
  const [newTagNames, setNewTagNames] = useState<string[]>([])
  const [newTagNameInput, setNewTagNameInput] = useState('')
  const [fileChanging, setFileChanging] = useState(false)
  const [previewLoading, setPreviewLoading] = useState(false)
  const [previewData, setPreviewData] = useState<PreviewResult>({ impacted: 0, examples: [] })

  const [mergeOpen, setMergeOpen] = useState(false)
  const [mergeSourceTag, setMergeSourceTag] = useState<TagRecord | null>(null)
  const [mergeTarget, setMergeTarget] = useState<number | null>(null)
  const [mergeSuggestions, setMergeSuggestions] = useState<TagSuggestion[]>([])
  const [merging, setMerging] = useState(false)

  const getTypeName = useCallback((typeId: number) => types.find((type) => type.id === typeId)?.name || t('none'), [t, types])
  const getParentName = useCallback(
    (parentId: number | null) => {
      if (!parentId) return t('none')
      const parent = tags.find((tag) => tag.id === parentId)
      return parent ? parent.name : t('none')
    },
    [t, tags]
  )

  const fetchTags = useCallback(
    async (page: number) => {
      setLoading(true)
      try {
        const response = await http.get('/api/v1/tags', {
          params: {
            page,
            per_page: perPage,
            type_id: selectedTypeId ?? undefined
          }
        })
        const data = response?.data as TagListResponse
        setTags(data?.tags || [])
        setCurrentPage(data?.page || page)
        setTotalPages(data?.pages || 1)
        setTotalTags(data?.total || 0)
      } catch (error) {
        console.error('加载标签列表失败：', error)
        message.error(t('errorFetchingTags'))
      } finally {
        setLoading(false)
      }
    },
    [perPage, selectedTypeId, t]
  )

  useEffect(() => {
    fetchTags(1).catch(() => {})
  }, [fetchTags, selectedTypeId])

  const openCreateModal = () => {
    setEditingTag(null)
    setTagForm({
      id: null,
      name: '',
      description: '',
      type_id: selectedTypeId ?? types[0]?.id ?? null,
      parent_id: null,
      aliases: [],
      newAlias: ''
    })
    setParentSuggestions([])
    setEditorOpen(true)
  }

  const openEditModal = (tag: TagRecord) => {
    setEditingTag(tag)
    setTagForm({
      id: tag.id,
      name: tag.name,
      description: tag.description || '',
      type_id: tag.type_id,
      parent_id: tag.parent_id,
      aliases: Array.isArray(tag.aliases) ? tag.aliases.slice() : [],
      newAlias: ''
    })
    setParentSuggestions([])
    setEditorOpen(true)
  }

  const closeEditor = () => {
    setEditorOpen(false)
    setEditingTag(null)
    setParentSuggestions([])
  }

  const loadParentSuggestions = useCallback(
    async (keyword: string) => {
      const typeId = tagForm.type_id
      if (!typeId) return
      setParentLoading(true)
      try {
        const response = await http.get('/api/v1/tag-suggestions', { params: { q: keyword, type_id: typeId, limit: 20 } })
        const list = (response?.data || []) as TagSuggestion[]
        setParentSuggestions(list.filter((item) => item.id !== tagForm.id))
      } catch (error) {
        console.error('加载父级标签建议失败：', error)
      } finally {
        setParentLoading(false)
      }
    },
    [tagForm.id, tagForm.type_id]
  )

  useEffect(() => {
    if (!editorOpen) return
    if (!tagForm.type_id) return
    loadParentSuggestions('').catch(() => {})
  }, [editorOpen, loadParentSuggestions, tagForm.type_id])

  const addAlias = () => {
    const trimmed = String(tagForm.newAlias || '').trim()
    if (!trimmed) return
    if (tagForm.aliases.includes(trimmed)) {
      message.warning(t('aliasAlreadyExists'))
      return
    }
    setTagForm((prev) => ({ ...prev, aliases: prev.aliases.concat([trimmed]), newAlias: '' }))
  }

  const removeAlias = (alias: string) => {
    setTagForm((prev) => ({ ...prev, aliases: prev.aliases.filter((value) => value !== alias) }))
  }

  const saveTag = async () => {
    if (!tagForm.name.trim() || !tagForm.type_id) {
      message.warning(t('tagNameAndTypeRequired'))
      return
    }

    const payload = {
      name: tagForm.name.trim(),
      description: tagForm.description || '',
      type_id: tagForm.type_id,
      parent_id: tagForm.parent_id,
      aliases: unique(tagForm.aliases)
    }

    try {
      if (editingTag) {
        await http.put(`/api/v1/tags/${editingTag.id}`, payload)
      } else {
        await http.post('/api/v1/tags', payload)
      }
      message.success(t('settingsSavedSuccessfully'))
      closeEditor()
      fetchTags(currentPage).catch(() => {})
    } catch (error) {
      console.error('保存标签失败：', error)
      message.error(t('errorSavingTag') + ((error as any)?.response?.data?.error || ''))
    }
  }

  const deleteTag = (tag: TagRecord) => {
    Modal.confirm({
      title: t('confirmDeletionTitle'),
      content: t('confirmDeleteTagWithUsage', { name: tag.name, count: tag.usage_count ?? 0 }),
      okType: 'danger',
      okText: t('delete'),
      cancelText: t('cancel'),
      onOk: async () => {
        try {
          await http.delete(`/api/v1/tags/${tag.id}`)
          message.success(t('settingsSavedSuccessfully'))
          fetchTags(currentPage).catch(() => {})
        } catch (error) {
          console.error('删除标签失败：', error)
          message.error(t('errorDeletingTag') + ((error as any)?.response?.data?.error || ''))
        }
      }
    })
  }

  const openFileChangeModal = (tag: TagRecord) => {
    setFileChangeTag(tag)
    setFileChangeAction('delete')
    setNewTagName('')
    setNewTagNames([])
    setNewTagNameInput('')
    setPreviewData({ impacted: 0, examples: [] })
    setFileChangeOpen(true)
  }

  const closeFileChangeModal = () => {
    setFileChangeOpen(false)
    setFileChangeTag(null)
    setFileChangeAction('delete')
    setNewTagName('')
    setNewTagNames([])
    setNewTagNameInput('')
    setPreviewData({ impacted: 0, examples: [] })
  }

  const fileChangeOkDisabled = useMemo(() => {
    if (!fileChangeTag) return true
    if (fileChangeAction === 'rename') return !newTagName.trim()
    if (fileChangeAction === 'split') return newTagNames.length === 0
    return false
  }, [fileChangeAction, fileChangeTag, newTagName, newTagNames.length])

  const loadPreview = async () => {
    if (!fileChangeTag) return
    setPreviewLoading(true)
    try {
      if (fileChangeAction === 'split') {
        const response = await http.post('/api/v1/tag-splits/preview', { tag_id: fileChangeTag.id, new_tag_names: newTagNames })
        setPreviewData((response?.data || { impacted: 0, examples: [] }) as PreviewResult)
        return
      }

      const response = await http.post('/api/v1/tag-file-changes/preview', {
        tag_id: fileChangeTag.id,
        action: fileChangeAction,
        new_name: fileChangeAction === 'rename' ? newTagName.trim() : undefined
      })
      setPreviewData((response?.data || { impacted: 0, examples: [] }) as PreviewResult)
    } catch (error) {
      console.error('加载预览失败：', error)
      message.error(t('errorLoadingPreview') + ((error as any)?.response?.data?.error || ''))
    } finally {
      setPreviewLoading(false)
    }
  }

  const executeFileChange = async () => {
    if (!fileChangeTag) return
    if (fileChangeAction === 'rename' && !newTagName.trim()) {
      message.warning(t('pleaseEnterNewTagName'))
      return
    }
    if (fileChangeAction === 'split' && newTagNames.length === 0) {
      message.warning(t('noNewTagsAdded'))
      return
    }
    setFileChanging(true)
    try {
      if (fileChangeAction === 'split') {
        await http.post('/api/v1/tag-splits', { tag_id: fileChangeTag.id, new_tag_names: newTagNames })
      } else {
        await http.post('/api/v1/tag-file-changes', {
          tag_id: fileChangeTag.id,
          action: fileChangeAction,
          new_name: fileChangeAction === 'rename' ? newTagName.trim() : undefined
        })
      }
      message.success(t('operationSubmittedCheckTaskManager'))
      closeFileChangeModal()
    } catch (error) {
      console.error('提交操作失败：', error)
      message.error(t('errorStartingOperation') + ((error as any)?.response?.data?.error || (error as any)?.message || ''))
    } finally {
      setFileChanging(false)
      checkActiveTasks().catch(() => {})
    }
  }

  const addNewTagName = () => {
    const trimmed = newTagNameInput.trim()
    if (!trimmed) return
    setNewTagNames((prev) => (prev.includes(trimmed) ? prev : prev.concat([trimmed])))
    setNewTagNameInput('')
  }

  const removeNewTagName = (value: string) => {
    setNewTagNames((prev) => prev.filter((item) => item !== value))
  }

  const openMergeModal = (tag: TagRecord) => {
    setMergeSourceTag(tag)
    setMergeTarget(null)
    setMergeSuggestions([])
    setMergeOpen(true)
  }

  const searchMergeTargets = async (keyword: string) => {
    if (!mergeSourceTag) return
    const response = await http.get('/api/v1/tag-suggestions', { params: { q: keyword, type_id: mergeSourceTag.type_id, limit: 20 } })
    const list = (response?.data || []) as TagSuggestion[]
    setMergeSuggestions(list.filter((item) => item.id !== mergeSourceTag.id))
  }

  const executeMerge = async () => {
    if (!mergeSourceTag || !mergeTarget) return
    setMerging(true)
    try {
      await http.post('/api/v1/tag-merges', { source_tag_id: mergeSourceTag.id, target_tag_id: mergeTarget })
      message.success(t('mergeSuccess'))
      setMergeOpen(false)
      fetchTags(currentPage).catch(() => {})
    } catch (error) {
      console.error('合并标签失败：', error)
      message.error(t('mergeError') + ((error as any)?.response?.data?.error || ''))
    } finally {
      setMerging(false)
      checkActiveTasks().catch(() => {})
    }
  }

  const columns: ColumnsType<TagRecord> = useMemo(
    () => [
      { title: t('name'), dataIndex: 'name', key: 'name' },
      {
        title: t('description'),
        key: 'description',
        render: (_value: unknown, record) => <Typography.Text type="secondary">{record.description || '-'}</Typography.Text>
      },
      { title: t('type'), key: 'type', render: (_value: unknown, record) => getTypeName(record.type_id) },
      { title: t('parentTag'), key: 'parent', render: (_value: unknown, record) => getParentName(record.parent_id) },
      {
        title: t('aliases'),
        key: 'aliases',
        render: (_value: unknown, record) => (
          <Space wrap>
            {(record.aliases || []).length ? (
              (record.aliases || []).map((alias) => <Tag key={`${record.id}-alias-${alias}`}>{alias}</Tag>)
            ) : (
              <Typography.Text type="secondary">-</Typography.Text>
            )}
          </Space>
        )
      },
      {
        title: t('usage'),
        key: 'usage',
        width: 110,
        render: (_value: unknown, record) => <Tag color="blue">{record.usage_count ?? 0}</Tag>
      },
      {
        title: t('actions'),
        key: 'actions',
        width: 340,
        render: (_value: unknown, record) => (
          <Space size="small" wrap>
            <Button size="small" onClick={() => openEditModal(record)}>
              {t('edit')}
            </Button>
            <Button size="small" onClick={() => openFileChangeModal(record)}>
              {t('fileChange')}
            </Button>
            <Button size="small" onClick={() => openMergeModal(record)}>
              {t('mergeTag')}
            </Button>
            <Button size="small" danger onClick={() => deleteTag(record)}>
              {t('delete')}
            </Button>
          </Space>
        )
      }
    ],
    [getParentName, getTypeName, t]
  )

  const parentOptions = useMemo(() => {
    const list = parentSuggestions || []
    return list.map((item) => ({
      value: item.id,
      label: `${item.name} (${getTypeName(item.type_id)})`
    }))
  }, [getTypeName, parentSuggestions])

  const mergeOptions = useMemo(() => {
    const list = mergeSuggestions || []
    return list.map((item) => ({
      value: item.id,
      label: `${item.name} (${t('usage')}: ${item.usage_count ?? 0})`
    }))
  }, [mergeSuggestions, t])

  return (
    <Space direction="vertical" size="large" className="w-full">
      <Card className="shadow-sm">
        <Space direction="vertical" size="large" className="w-full">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <Form layout="inline">
              <Form.Item label={t('filterByType')}>
                <Select
                  value={selectedTypeId ?? undefined}
                  allowClear
                  style={{ minWidth: 220 }}
                  placeholder={t('allTypes')}
                  onChange={(value) => setSelectedTypeId(value ? Number(value) : null)}
                  options={types.map((type) => ({ value: type.id, label: type.name }))}
                />
              </Form.Item>
            </Form>

            <Button type="primary" onClick={openCreateModal}>
              + {t('newTag')}
            </Button>
          </div>

          <Table<TagRecord>
            rowKey={(record) => record.id}
            dataSource={tags}
            loading={loading}
            pagination={false}
            size="middle"
            columns={columns}
            locale={{ emptyText: t('noTagsFoundForType') }}
          />

          <div className="flex justify-end">
            <Pagination
              simple
              current={currentPage}
              total={totalPages}
              pageSize={1}
              onChange={(page) => fetchTags(page).catch(() => {})}
            />
          </div>
        </Space>
      </Card>

      <Modal
        open={editorOpen}
        title={editingTag ? `${t('edit')} ${t('tag')}` : t('newTag')}
        okText={t('save')}
        cancelText={t('cancel')}
        width={640}
        onOk={() => saveTag().catch(() => {})}
        onCancel={closeEditor}
      >
        <Form layout="vertical">
          <Form.Item label={t('name')} required>
            <Input value={tagForm.name} onChange={(event) => setTagForm((prev) => ({ ...prev, name: event.target.value }))} />
          </Form.Item>
          <Form.Item label={t('description')}>
            <Input.TextArea
              value={tagForm.description}
              rows={3}
              onChange={(event) => setTagForm((prev) => ({ ...prev, description: event.target.value }))}
            />
          </Form.Item>
          <Form.Item label={t('type')} required>
            <Select
              value={tagForm.type_id ?? undefined}
              dropdownMatchSelectWidth={false}
              onChange={(value) => {
                const nextTypeId = value ? Number(value) : null
                setTagForm((prev) => ({ ...prev, type_id: nextTypeId, parent_id: null }))
              }}
              options={types.map((type) => ({ value: type.id, label: type.name }))}
            />
          </Form.Item>
          <Form.Item label={t('parentTag')}>
            <Select
              value={tagForm.parent_id ?? undefined}
              showSearch
              allowClear
              filterOption={false}
              placeholder={t('none')}
              notFoundContent={parentLoading ? t('loading') : null}
              onSearch={(value) => loadParentSuggestions(value).catch(() => {})}
              onFocus={() => loadParentSuggestions('').catch(() => {})}
              onChange={(value) => setTagForm((prev) => ({ ...prev, parent_id: value ? Number(value) : null }))}
              dropdownMatchSelectWidth={false}
              options={parentOptions}
            />
          </Form.Item>
          <Form.Item label={t('aliases')}>
            <Space align="start" className="w-full">
              <Input
                value={tagForm.newAlias}
                placeholder={t('aliases')}
                onChange={(event) => setTagForm((prev) => ({ ...prev, newAlias: event.target.value }))}
                onPressEnter={(event) => {
                  event.preventDefault()
                  addAlias()
                }}
              />
              <Button type="dashed" onClick={addAlias}>
                {t('add')}
              </Button>
            </Space>

            <div className="mt-2 flex flex-wrap gap-2">
              {tagForm.aliases.map((alias) => (
                <Tag key={`alias-${alias}`} closable onClose={(event) => {
                  event.preventDefault()
                  removeAlias(alias)
                }}>
                  {alias}
                </Tag>
              ))}
            </div>
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        open={fileChangeOpen}
        title={`${t('fileChange')} - ${fileChangeTag?.name || ''}`}
        cancelText={t('cancel')}
        okButtonProps={{ disabled: fileChangeOkDisabled }}
        confirmLoading={fileChanging}
        width={720}
        onOk={() => executeFileChange().catch(() => {})}
        onCancel={closeFileChangeModal}
      >
        <Form layout="vertical">
          <Form.Item label={t('selectAction')}>
            <Radio.Group value={fileChangeAction} onChange={(event) => setFileChangeAction(event.target.value as FileChangeAction)}>
              <Space direction="vertical">
                <Radio value="delete">
                  {t('deleteTagFromFilenames')} [{fileChangeTag?.name || ''}]
                </Radio>
                <Radio value="rename">
                  {t('renameTagInFilenames')} [{fileChangeTag?.name || ''}]
                </Radio>
                <Radio value="split">
                  {t('splitTagInFilenames')} [{fileChangeTag?.name || ''}]
                </Radio>
              </Space>
            </Radio.Group>
          </Form.Item>

          {fileChangeAction === 'rename' ? (
            <Form.Item label={t('newTagName')}>
              <Input value={newTagName} placeholder={fileChangeTag?.name || ''} onChange={(event) => setNewTagName(event.target.value)} />
            </Form.Item>
          ) : null}

          {fileChangeAction === 'split' ? (
            <Space direction="vertical" size="middle" className="w-full">
              <Form.Item label={t('addNewTagName')}>
                <Space className="w-full">
                  <Input
                    value={newTagNameInput}
                    placeholder={t('newTagNamePlaceholder')}
                    onChange={(event) => setNewTagNameInput(event.target.value)}
                    onPressEnter={(event) => {
                      event.preventDefault()
                      addNewTagName()
                    }}
                  />
                  <Button type="dashed" onClick={addNewTagName}>
                    {t('add')}
                  </Button>
                </Space>
              </Form.Item>

              {newTagNames.length ? (
                <List
                  size="small"
                  bordered
                  dataSource={newTagNames}
                  renderItem={(item) => (
                    <List.Item className="flex items-center justify-between">
                      <Typography.Text>[{item}]</Typography.Text>
                      <Button type="text" danger size="small" onClick={() => removeNewTagName(item)}>
                        {t('delete')}
                      </Button>
                    </List.Item>
                  )}
                />
              ) : null}
            </Space>
          ) : null}

          <Space direction="vertical" className="w-full">
            <Button loading={previewLoading} onClick={() => loadPreview().catch(() => {})}>
              {t('preview')}
            </Button>

            <Typography.Paragraph>
              {t('impactedFiles')}: <Typography.Text strong>{previewData.impacted || 0}</Typography.Text>
            </Typography.Paragraph>

            {previewData.examples?.length ? (
              <List
                size="small"
                bordered
                dataSource={previewData.examples}
                renderItem={(item) => (
                  <List.Item>
                    <div className="flex flex-col">
                      <span>
                        <strong>{t('previewOldLabel')}:</strong> {item.old}
                      </span>
                      <span>
                        <strong>{t('previewNewLabel')}:</strong> {item.new}
                      </span>
                    </div>
                  </List.Item>
                )}
              />
            ) : null}

            <Alert type="warning" showIcon message={t('warningFileRename')} />
          </Space>
        </Form>
      </Modal>

      <Modal
        open={mergeOpen}
        title={t('mergeTag')}
        okText={t('confirmMerge')}
        cancelText={t('cancel')}
        confirmLoading={merging}
        onOk={() => executeMerge().catch(() => {})}
        onCancel={() => setMergeOpen(false)}
      >
        <Form layout="vertical">
          <Form.Item label={t('selectTargetTag')}>
            <Select
              value={mergeTarget ?? undefined}
              showSearch
              filterOption={false}
              placeholder={t('selectTargetTag')}
              onSearch={(value) => searchMergeTargets(value).catch(() => {})}
              onFocus={() => searchMergeTargets('').catch(() => {})}
              onChange={(value) => setMergeTarget(value ? Number(value) : null)}
              options={mergeOptions}
            />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  )
}
