// apps/web/src/components/TagTypeManager.vue
<template>
  <a-space direction="vertical" size="middle" class="w-full">
    <a-list
      :data-source="types"
      bordered
      item-layout="horizontal"
    >
      <template #renderItem="{ item }">
        <a-list-item>
          <template v-if="editingTypeId === item.id">
            <a-space wrap class="w-full">
              <a-input
                v-model:value="editingTypeName"
                :placeholder="$t('typeName')"
                style="min-width: 180px"
              />
              <a-input-number
                v-model:value="editingTypeSortOrder"
                :placeholder="$t('sortValue')"
                style="width: 120px"
              />
              <a-space size="small">
                <a-button type="primary" size="small" @click="saveEdit">
                  {{ $t('save') }}
                </a-button>
                <a-button size="small" @click="cancelEditing">
                  {{ $t('cancel') }}
                </a-button>
              </a-space>
            </a-space>
          </template>
          <template v-else>
            <div class="flex w-full flex-wrap items-center justify-between gap-3">
              <div>
                <a-typography-text strong>{{ item.name }}</a-typography-text>
                <a-tag class="ml-2">
                  {{ $t('sortOrder') }}: {{ item.sort_order }}
                </a-tag>
              </div>
              <a-space size="small">
                <a-button size="small" @click="startEditing(item)">
                  {{ $t('edit') }}
                </a-button>
                <a-button danger size="small" @click="deleteType(item.id)">
                  {{ $t('delete') }}
                </a-button>
              </a-space>
            </div>
          </template>
        </a-list-item>
      </template>
      <template #footer>
        <a-button type="dashed" block @click="openCreateDialog">
          + {{ $t('newType') }}
        </a-button>
      </template>
    </a-list>

    <a-modal
      v-model:open="isCreating"
      :title="$t('newType')"
      :ok-text="$t('save')"
      :cancel-text="$t('cancel')"
      @ok="createType"
      @cancel="resetCreateForm"
    >
      <a-form layout="vertical">
        <a-form-item :label="$t('typeName')" :required="true">
          <a-input v-model:value="newTypeName" />
        </a-form-item>
        <a-form-item :label="$t('sortValue')">
          <a-input-number v-model:value="newTypeSortOrder" style="width: 160px" />
        </a-form-item>
      </a-form>
    </a-modal>

    <a-divider />

    <a-button type="primary" ghost @click="startScan">
      {{ $t('scanNewTags') }}
    </a-button>

    <a-modal
      v-model:open="showScanner"
      :title="$t('foundUndefinedTags')"
      :ok-text="$t('addSelectedTags')"
      :cancel-text="$t('close')"
      :ok-button-props="{ disabled: selectedScannedTags.length === 0 || !selectedTagType }"
      @ok="addSelectedTags"
    >
      <a-spin :spinning="isLoadingScannedTags">
        <template v-if="!isLoadingScannedTags && scannedTags.length === 0">
          <a-empty :description="$t('noNewTagsFound')" />
        </template>
        <template v-else>
          <a-checkbox-group
            v-model:value="selectedScannedTags"
            class="grid grid-cols-1 sm:grid-cols-2 gap-2"
          >
            <a-checkbox v-for="tag in scannedTags" :key="tag" :value="tag">
              {{ tag }}
            </a-checkbox>
          </a-checkbox-group>

          <a-form layout="vertical" class="mt-4">
            <a-form-item :label="$t('tagTypes')">
              <a-select v-model:value="selectedTagType" :placeholder="$t('type')">
                <a-select-option v-for="type in types" :key="type.id" :value="type.id">
                  {{ type.name }}
                </a-select-option>
              </a-select>
            </a-form-item>
          </a-form>

          <a-typography-text type="secondary">
            {{ $t('tagsSelected', { count: selectedScannedTags.length }) }}
          </a-typography-text>
        </template>
      </a-spin>
    </a-modal>
  </a-space>
</template>

<script setup>
import { ref, watch } from 'vue'
import axios from 'axios'
import { useI18n } from 'vue-i18n'
import { message, Modal } from 'ant-design-vue'
import { useLibraryStore } from '@/store/library'

const { t } = useI18n()
const libraryStore = useLibraryStore()

const props = defineProps({
  types: {
    type: Array,
    required: true
  }
})

const emit = defineEmits(['dataChanged'])

const newTypeName = ref('')
const newTypeSortOrder = ref(0)
const isCreating = ref(false)
const editingTypeId = ref(null)
const editingTypeName = ref('')
const editingTypeSortOrder = ref(0)

const scannedTags = ref([])
const isLoadingScannedTags = ref(false)
const showScanner = ref(false)
const selectedScannedTags = ref([])
const selectedTagType = ref(null)

watch(showScanner, value => {
  if (!value) {
    selectedScannedTags.value = []
  }
})

function resetCreateForm() {
  isCreating.value = false
  newTypeName.value = ''
  newTypeSortOrder.value = 0
}

function openCreateDialog() {
  newTypeName.value = ''
  newTypeSortOrder.value = 0
  isCreating.value = true
}

async function createType() {
  if (!newTypeName.value.trim()) {
    message.warning(t('tagNameAndTypeRequired'))
    return
  }

  try {
    await axios.post('/api/v1/tag-types', {
      name: newTypeName.value,
      sort_order: newTypeSortOrder.value
    })
    message.success(t('settingsSavedSuccessfully'))
    resetCreateForm()
    emit('dataChanged')
  } catch (error) {
    console.error('Failed to create tag type:', error)
    message.error(t('errorCreatingTagType') + (error.response?.data?.error || ''))
  }
}

async function startScan() {
  showScanner.value = true
  isLoadingScannedTags.value = true
  selectedScannedTags.value = []
  selectedTagType.value = props.types[0]?.id ?? null

  try {
    const response = await axios.get('/api/v1/reports/undefined-tags')
    scannedTags.value = response.data
  } catch (error) {
    console.error('Failed to scan for undefined tags:', error)
    message.error(t('errorScanningTags') + (error.response?.data?.error || ''))
  } finally {
    isLoadingScannedTags.value = false
    libraryStore.checkActiveTasks()
  }
}

async function addSelectedTags() {
  if (selectedScannedTags.value.length === 0 || !selectedTagType.value) {
    message.warning(t('selectTagsAndType'))
    return
  }

  try {
    for (const tagName of selectedScannedTags.value) {
      await axios.post('/api/v1/tags', {
        name: tagName,
        type_id: selectedTagType.value
      })
    }
    message.success(t('tagsAddedSuccessfully'))
    showScanner.value = false
    scannedTags.value = []
    emit('dataChanged')
  } catch (error) {
    console.error('Failed to add tags:', error)
    message.error(t('errorAddingTags') + (error.response?.data?.error || ''))
  }
}

function deleteType(id) {
  Modal.confirm({
    title: t('confirmDeleteTagType'),
    okType: 'danger',
    onOk: async () => {
      try {
        await axios.delete(`/api/v1/tag-types/${id}`)
        message.success(t('settingsSavedSuccessfully'))
        emit('dataChanged')
      } catch (error) {
        console.error('Failed to delete tag type:', error)
        message.error(t('errorDeletingTagType') + (error.response?.data?.error || ''))
      }
    }
  })
}

function startEditing(type) {
  editingTypeId.value = type.id
  editingTypeName.value = type.name
  editingTypeSortOrder.value = type.sort_order
}

function cancelEditing() {
  editingTypeId.value = null
}

async function saveEdit() {
  if (!editingTypeName.value.trim()) {
    message.warning(t('tagNameAndTypeRequired'))
    return
  }

  try {
    await axios.put(`/api/v1/tag-types/${editingTypeId.value}`, {
      name: editingTypeName.value,
      sort_order: editingTypeSortOrder.value
    })
    message.success(t('settingsSavedSuccessfully'))
    cancelEditing()
    emit('dataChanged')
  } catch (error) {
    console.error('Failed to update tag type:', error)
    message.error(t('errorUpdatingTagType') + (error.response?.data?.error || ''))
  }
}
</script>

// apps/web/src/components/tags/TagTypeManager.tsx
import { Button, Checkbox, Divider, Empty, Form, Input, InputNumber, List, Modal, Select, Space, Spin, Tag, Typography, message } from 'antd'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { http } from '@/api/http'
import { useLibraryStore } from '@/store/library'

export type TagType = {
  id: number
  name: string
  sort_order: number | null
}

export type TagTypeManagerProps = {
  types: TagType[]
  onDataChanged: () => void
}

export default function TagTypeManager({ types, onDataChanged }: TagTypeManagerProps) {
  const { t } = useTranslation()
  const checkActiveTasks = useLibraryStore((state) => state.checkActiveTasks)

  const [isCreating, setIsCreating] = useState(false)
  const [newTypeName, setNewTypeName] = useState('')
  const [newTypeSortOrder, setNewTypeSortOrder] = useState(0)

  const [editingTypeId, setEditingTypeId] = useState<number | null>(null)
  const [editingTypeName, setEditingTypeName] = useState('')
  const [editingTypeSortOrder, setEditingTypeSortOrder] = useState(0)

  const [scannedTags, setScannedTags] = useState<string[]>([])
  const [isLoadingScannedTags, setIsLoadingScannedTags] = useState(false)
  const [showScanner, setShowScanner] = useState(false)
  const [selectedScannedTags, setSelectedScannedTags] = useState<string[]>([])
  const [selectedTagType, setSelectedTagType] = useState<number | null>(null)

  useEffect(() => {
    if (!showScanner) {
      setSelectedScannedTags([])
    }
  }, [showScanner])

  const resetCreateForm = () => {
    setIsCreating(false)
    setNewTypeName('')
    setNewTypeSortOrder(0)
  }

  const openCreateDialog = () => {
    setNewTypeName('')
    setNewTypeSortOrder(0)
    setIsCreating(true)
  }

  const createType = async () => {
    if (!newTypeName.trim()) {
      message.warning(t('tagNameAndTypeRequired'))
      return
    }
    try {
      await http.post('/api/v1/tag-types', {
        name: newTypeName,
        sort_order: newTypeSortOrder
      })
      message.success(t('settingsSavedSuccessfully'))
      resetCreateForm()
      onDataChanged()
    } catch (error) {
      console.error('创建标签类型失败：', error)
      message.error(t('errorCreatingTagType') + ((error as any)?.response?.data?.error || ''))
    }
  }

  const deleteType = (id: number) => {
    Modal.confirm({
      title: t('confirmDeleteTagType'),
      okType: 'danger',
      okText: t('delete'),
      cancelText: t('cancel'),
      onOk: async () => {
        try {
          await http.delete(`/api/v1/tag-types/${id}`)
          message.success(t('settingsSavedSuccessfully'))
          onDataChanged()
        } catch (error) {
          console.error('删除标签类型失败：', error)
          message.error(t('errorDeletingTagType') + ((error as any)?.response?.data?.error || ''))
        }
      }
    })
  }

  const startEditing = (type: TagType) => {
    setEditingTypeId(type.id)
    setEditingTypeName(type.name)
    setEditingTypeSortOrder(type.sort_order || 0)
  }

  const cancelEditing = () => {
    setEditingTypeId(null)
  }

  const saveEdit = async () => {
    if (!editingTypeId) {
      return
    }
    if (!editingTypeName.trim()) {
      message.warning(t('tagNameAndTypeRequired'))
      return
    }
    try {
      await http.put(`/api/v1/tag-types/${editingTypeId}`, {
        name: editingTypeName,
        sort_order: editingTypeSortOrder
      })
      message.success(t('settingsSavedSuccessfully'))
      cancelEditing()
      onDataChanged()
    } catch (error) {
      console.error('更新标签类型失败：', error)
      message.error(t('errorUpdatingTagType') + ((error as any)?.response?.data?.error || ''))
    }
  }

  const startScan = async () => {
    setShowScanner(true)
    setIsLoadingScannedTags(true)
    setSelectedScannedTags([])
    setSelectedTagType(types[0]?.id ?? null)
    try {
      const response = await http.get('/api/v1/reports/undefined-tags')
      setScannedTags((response?.data || []) as string[])
    } catch (error) {
      console.error('扫描未定义标签失败：', error)
      message.error(t('errorScanningTags') + ((error as any)?.response?.data?.error || ''))
    } finally {
      setIsLoadingScannedTags(false)
      checkActiveTasks().catch(() => {})
    }
  }

  const addSelectedTags = async () => {
    if (!selectedScannedTags.length || !selectedTagType) {
      message.warning(t('selectTagsAndType'))
      return
    }
    try {
      for (const tagName of selectedScannedTags) {
        await http.post('/api/v1/tags', { name: tagName, type_id: selectedTagType })
      }
      message.success(t('tagsAddedSuccessfully'))
      setShowScanner(false)
      setScannedTags([])
      onDataChanged()
    } catch (error) {
      console.error('新增标签失败：', error)
      message.error(t('errorAddingTags') + ((error as any)?.response?.data?.error || ''))
    }
  }

  return (
    <Space direction="vertical" size="middle" className="w-full">
      <List
        bordered
        dataSource={types}
        itemLayout="horizontal"
        renderItem={(item) => (
          <List.Item key={`tag-type-${item.id}`}>
            {editingTypeId === item.id ? (
              <Space wrap className="w-full">
                <Input value={editingTypeName} placeholder={t('typeName')} style={{ minWidth: 180 }} onChange={(e) => setEditingTypeName(e.target.value)} />
                <InputNumber value={editingTypeSortOrder} placeholder={t('sortValue')} style={{ width: 120 }} onChange={(v) => setEditingTypeSortOrder(Number(v ?? 0))} />
                <Space size="small">
                  <Button type="primary" size="small" onClick={() => saveEdit().catch(() => {})}>
                    {t('save')}
                  </Button>
                  <Button size="small" onClick={cancelEditing}>
                    {t('cancel')}
                  </Button>
                </Space>
              </Space>
            ) : (
              <div className="flex w-full flex-wrap items-center justify-between gap-3">
                <div>
                  <Typography.Text strong>{item.name}</Typography.Text>
                  <Tag className="ml-2">
                    {t('sortOrder')}: {item.sort_order}
                  </Tag>
                </div>
                <Space size="small">
                  <Button size="small" onClick={() => startEditing(item)}>
                    {t('edit')}
                  </Button>
                  <Button danger size="small" onClick={() => deleteType(item.id)}>
                    {t('delete')}
                  </Button>
                </Space>
              </div>
            )}
          </List.Item>
        )}
        footer={
          <Button type="dashed" block onClick={openCreateDialog}>
            + {t('newType')}
          </Button>
        }
      />

      <Modal
        open={isCreating}
        title={t('newType')}
        okText={t('save')}
        cancelText={t('cancel')}
        onOk={() => createType().catch(() => {})}
        onCancel={resetCreateForm}
      >
        <Form layout="vertical">
          <Form.Item label={t('typeName')} required>
            <Input value={newTypeName} onChange={(e) => setNewTypeName(e.target.value)} />
          </Form.Item>
          <Form.Item label={t('sortValue')}>
            <InputNumber value={newTypeSortOrder} style={{ width: 160 }} onChange={(v) => setNewTypeSortOrder(Number(v ?? 0))} />
          </Form.Item>
        </Form>
      </Modal>

      <Divider />

      <Button type="primary" ghost onClick={() => startScan().catch(() => {})}>
        {t('scanNewTags')}
      </Button>

      <Modal
        open={showScanner}
        title={t('foundUndefinedTags')}
        okText={t('addSelectedTags')}
        cancelText={t('close')}
        okButtonProps={{ disabled: selectedScannedTags.length === 0 || !selectedTagType }}
        onOk={() => addSelectedTags().catch(() => {})}
        onCancel={() => setShowScanner(false)}
      >
        <Spin spinning={isLoadingScannedTags}>
          {!isLoadingScannedTags && scannedTags.length === 0 ? (
            <Empty description={t('noNewTagsFound')} />
          ) : (
            <Space direction="vertical" size="middle" className="w-full">
              <Checkbox.Group
                value={selectedScannedTags}
                onChange={(value) => setSelectedScannedTags(value as string[])}
                className="grid grid-cols-1 sm:grid-cols-2 gap-2"
              >
                {scannedTags.map((tag) => (
                  <Checkbox key={`scanned-${tag}`} value={tag}>
                    {tag}
                  </Checkbox>
                ))}
              </Checkbox.Group>

              <Form layout="vertical">
                <Form.Item label={t('tagTypes')}>
                  <Select
                    value={selectedTagType ?? undefined}
                    placeholder={t('type')}
                    onChange={(value) => setSelectedTagType(Number(value))}
                    options={types.map((type) => ({ value: type.id, label: type.name }))}
                  />
                </Form.Item>
              </Form>

              <Typography.Text type="secondary">{t('tagsSelected', { count: selectedScannedTags.length })}</Typography.Text>
            </Space>
          )}
        </Spin>
      </Modal>
    </Space>
  )
}
