// apps/web/src/components/library/LibraryDisplaySettings.tsx
import { Button, Checkbox, Col, Form, InputNumber, Row, Select, Space, Typography, message } from 'antd'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { http } from '@/api/http'
import type { LibraryCardFieldKey, LibraryCardFields, LibraryGridColumns } from '@/store/uiSettings'
import { DEFAULT_LIBRARY_CARD_FIELDS, DEFAULT_LIBRARY_GRID_COLUMNS, LIBRARY_CARD_FIELD_DEFS, useUiSettingsStore } from '@/store/uiSettings'

type TagType = {
  id: number
  name: string
  sort_order?: number | null
}

const breakpoints = Object.freeze([
  { key: 'base', labelKey: 'libraryGridBreakpointBase' },
  { key: 'sm', labelKey: 'libraryGridBreakpointSm' },
  { key: 'md', labelKey: 'libraryGridBreakpointMd' },
  { key: 'lg', labelKey: 'libraryGridBreakpointLg' },
  { key: 'xl', labelKey: 'libraryGridBreakpointXl' },
  { key: '2xl', labelKey: 'libraryGridBreakpoint2xl' }
] as const)

export default function LibraryDisplaySettings() {
  const { t } = useTranslation()

  const ensureLoaded = useUiSettingsStore((state) => state.ensureLoaded)
  const saveLibraryDisplaySettings = useUiSettingsStore((state) => state.saveLibraryDisplaySettings)
  const resetLibraryDisplaySettings = useUiSettingsStore((state) => state.resetLibraryDisplaySettings)

  const libraryGridColumns = useUiSettingsStore((state) => state.libraryGridColumns)
  const libraryCardFields = useUiSettingsStore((state) => state.libraryCardFields)
  const libraryAuthorTagTypeId = useUiSettingsStore((state) => state.libraryAuthorTagTypeId)

  const [saving, setSaving] = useState(false)
  const [tagTypesLoading, setTagTypesLoading] = useState(false)
  const [tagTypes, setTagTypes] = useState<TagType[]>([])

  const [columnsDraft, setColumnsDraft] = useState<LibraryGridColumns>({ ...DEFAULT_LIBRARY_GRID_COLUMNS })
  const [gridFieldsDraft, setGridFieldsDraft] = useState<LibraryCardFieldKey[]>([...DEFAULT_LIBRARY_CARD_FIELDS.grid])
  const [listFieldsDraft, setListFieldsDraft] = useState<LibraryCardFieldKey[]>([...DEFAULT_LIBRARY_CARD_FIELDS.list])
  const [authorTagTypeIdDraft, setAuthorTagTypeIdDraft] = useState<number | null>(null)

  const fieldOptions = useMemo(
    () => LIBRARY_CARD_FIELD_DEFS.map((item) => ({ value: item.key, label: t(item.labelKey) })),
    [t]
  )

  useEffect(() => {
    ensureLoaded().catch(() => {})
  }, [ensureLoaded])

  useEffect(() => {
    setColumnsDraft({ ...DEFAULT_LIBRARY_GRID_COLUMNS, ...(libraryGridColumns || {}) })
    setGridFieldsDraft([...(libraryCardFields?.grid || DEFAULT_LIBRARY_CARD_FIELDS.grid)])
    setListFieldsDraft([...(libraryCardFields?.list || DEFAULT_LIBRARY_CARD_FIELDS.list)])
    setAuthorTagTypeIdDraft(libraryAuthorTagTypeId || null)
  }, [libraryAuthorTagTypeId, libraryCardFields, libraryGridColumns])

  const loadTagTypes = useCallback(async () => {
    setTagTypesLoading(true)
    try {
      const response = await http.get('/api/v1/tag-types')
      setTagTypes((response?.data || []) as TagType[])
    } catch (error) {
      console.error('加载标签类型失败：', error)
      message.error(t('failedToLoadTagTypes'))
    } finally {
      setTagTypesLoading(false)
    }
  }, [t])

  useEffect(() => {
    loadTagTypes().catch(() => {})
  }, [loadTagTypes])

  const save = async () => {
    setSaving(true)
    try {
      const cardFields: LibraryCardFields = {
        grid: gridFieldsDraft,
        list: listFieldsDraft
      }
      await saveLibraryDisplaySettings({
        gridColumns: columnsDraft,
        cardFields,
        authorTagTypeId: authorTagTypeIdDraft
      })
      message.success(t('libraryDisplaySettingsSaved'))
    } catch (error) {
      console.error('保存图书馆展示设置失败：', error)
      message.error(t('failedToSaveSettings'))
    } finally {
      setSaving(false)
    }
  }

  const reset = async () => {
    setSaving(true)
    try {
      await resetLibraryDisplaySettings()
      message.success(t('libraryDisplaySettingsReset'))
    } catch (error) {
      console.error('重置图书馆展示设置失败：', error)
      message.error(t('failedToSaveSettings'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <Form layout="vertical" onFinish={() => save().catch(() => {})}>
      <Form.Item label={t('libraryGridColumns')}>
        <Row gutter={[12, 12]}>
          {breakpoints.map((bp) => (
            <Col key={`grid-bp-${bp.key}`} xs={12} sm={8} md={4}>
              <InputNumber
                min={1}
                max={24}
                className="w-full"
                value={(columnsDraft as any)[bp.key]}
                onChange={(value) =>
                  setColumnsDraft((prev) => ({
                    ...prev,
                    [bp.key]: Number(value ?? prev[bp.key as keyof LibraryGridColumns])
                  }))
                }
              />
              <div className="mt-1 text-xs text-gray-500">{t(bp.labelKey)}</div>
            </Col>
          ))}
        </Row>
        <Typography.Text type="secondary" className="text-xs">
          {t('libraryGridColumnsHelp')}
        </Typography.Text>
      </Form.Item>

      <Form.Item label={t('libraryCardFieldsGrid')}>
        <Checkbox.Group value={gridFieldsDraft} options={fieldOptions} onChange={(value) => setGridFieldsDraft(value as any)} />
      </Form.Item>

      <Form.Item label={t('libraryCardFieldsList')}>
        <Checkbox.Group value={listFieldsDraft} options={fieldOptions} onChange={(value) => setListFieldsDraft(value as any)} />
        <Typography.Text type="secondary" className="text-xs">
          {t('libraryCardFieldsHelp')}
        </Typography.Text>
      </Form.Item>

      <Form.Item label={t('libraryAuthorTagType')}>
        <Select
          allowClear
          loading={tagTypesLoading}
          placeholder={t('libraryAuthorTagTypePlaceholder')}
          style={{ maxWidth: 360 }}
          value={authorTagTypeIdDraft ?? undefined}
          onChange={(value) => setAuthorTagTypeIdDraft(typeof value === 'number' ? value : null)}
          options={tagTypes.map((type) => ({ value: type.id, label: type.name }))}
        />
        <Typography.Text type="secondary" className="text-xs">
          {t('libraryAuthorTagTypeHelp')}
        </Typography.Text>
      </Form.Item>

      <Space>
        <Button type="primary" loading={saving} onClick={() => save().catch(() => {})}>
          {t('save')}
        </Button>
        <Button disabled={saving} onClick={() => reset().catch(() => {})}>
          {t('resetToDefault')}
        </Button>
      </Space>
    </Form>
  )
}

// frontend/src/components/LibraryDisplaySettings.vue
<script setup>
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import axios from 'axios'
import { message } from 'ant-design-vue'
import { storeToRefs } from 'pinia'
import {
  DEFAULT_LIBRARY_CARD_FIELDS,
  DEFAULT_LIBRARY_GRID_COLUMNS,
  LIBRARY_CARD_FIELD_DEFS,
  useUiSettingsStore
} from '@/store/uiSettings'

const { t } = useI18n()
const uiSettingsStore = useUiSettingsStore()
const { libraryGridColumns, libraryCardFields, libraryAuthorTagTypeId } = storeToRefs(uiSettingsStore)

const saving = ref(false)
const tagTypesLoading = ref(false)
const tagTypes = ref([])

const breakpoints = Object.freeze([
  { key: 'base', labelKey: 'libraryGridBreakpointBase' },
  { key: 'sm', labelKey: 'libraryGridBreakpointSm' },
  { key: 'md', labelKey: 'libraryGridBreakpointMd' },
  { key: 'lg', labelKey: 'libraryGridBreakpointLg' },
  { key: 'xl', labelKey: 'libraryGridBreakpointXl' },
  { key: '2xl', labelKey: 'libraryGridBreakpoint2xl' }
])

const columnsDraft = ref({ ...DEFAULT_LIBRARY_GRID_COLUMNS })
const gridFieldsDraft = ref([...DEFAULT_LIBRARY_CARD_FIELDS.grid])
const listFieldsDraft = ref([...DEFAULT_LIBRARY_CARD_FIELDS.list])
const authorTagTypeIdDraft = ref(null)

const fieldOptions = computed(() =>
  LIBRARY_CARD_FIELD_DEFS.map(item => ({
    value: item.key,
    label: t(item.labelKey)
  }))
)

const syncDraftFromStore = () => {
  columnsDraft.value = { ...DEFAULT_LIBRARY_GRID_COLUMNS, ...(libraryGridColumns.value || {}) }
  gridFieldsDraft.value = [...((libraryCardFields.value?.grid) || DEFAULT_LIBRARY_CARD_FIELDS.grid)]
  listFieldsDraft.value = [...((libraryCardFields.value?.list) || DEFAULT_LIBRARY_CARD_FIELDS.list)]
  authorTagTypeIdDraft.value = libraryAuthorTagTypeId.value || null
}

const loadTagTypes = async () => {
  tagTypesLoading.value = true
  try {
    const response = await axios.get('/api/v1/tag_types')
    tagTypes.value = response.data || []
  } catch (error) {
    console.error('加载标签类型失败：', error)
    message.error(t('failedToLoadTagTypes'))
  } finally {
    tagTypesLoading.value = false
  }
}

const save = async () => {
  saving.value = true
  try {
    await uiSettingsStore.saveLibraryDisplaySettings({
      gridColumns: columnsDraft.value,
      cardFields: {
        grid: gridFieldsDraft.value,
        list: listFieldsDraft.value
      },
      authorTagTypeId: authorTagTypeIdDraft.value
    })
    message.success(t('libraryDisplaySettingsSaved'))
    syncDraftFromStore()
  } catch (error) {
    console.error('保存图书馆展示设置失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}

const reset = async () => {
  saving.value = true
  try {
    await uiSettingsStore.resetLibraryDisplaySettings()
    message.success(t('libraryDisplaySettingsReset'))
    syncDraftFromStore()
  } catch (error) {
    console.error('重置图书馆展示设置失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}

onMounted(async () => {
  await uiSettingsStore.ensureLoaded()
  syncDraftFromStore()
  loadTagTypes()
})
</script>

<template>
  <a-form layout="vertical" @submit.prevent>
    <a-form-item :label="$t('libraryGridColumns')">
      <a-row :gutter="[12, 12]">
        <a-col
          v-for="bp in breakpoints"
          :key="`grid-bp-${bp.key}`"
          :xs="12"
          :sm="8"
          :md="4"
        >
          <a-input-number
            v-model:value="columnsDraft[bp.key]"
            :min="1"
            :max="24"
            class="w-full"
          />
          <div class="mt-1 text-xs text-gray-500">
            {{ $t(bp.labelKey) }}
          </div>
        </a-col>
      </a-row>
      <a-typography-text type="secondary" class="text-xs">
        {{ $t('libraryGridColumnsHelp') }}
      </a-typography-text>
    </a-form-item>

    <a-form-item :label="$t('libraryCardFieldsGrid')">
      <a-checkbox-group v-model:value="gridFieldsDraft" :options="fieldOptions" />
    </a-form-item>

    <a-form-item :label="$t('libraryCardFieldsList')">
      <a-checkbox-group v-model:value="listFieldsDraft" :options="fieldOptions" />
      <a-typography-text type="secondary" class="text-xs">
        {{ $t('libraryCardFieldsHelp') }}
      </a-typography-text>
    </a-form-item>

    <a-form-item :label="$t('libraryAuthorTagType')">
      <a-select
        v-model:value="authorTagTypeIdDraft"
        allow-clear
        :loading="tagTypesLoading"
        :placeholder="$t('libraryAuthorTagTypePlaceholder')"
        style="max-width: 360px"
      >
        <a-select-option v-for="type in tagTypes" :key="type.id" :value="type.id">
          {{ type.name }}
        </a-select-option>
      </a-select>
      <a-typography-text type="secondary" class="text-xs">
        {{ $t('libraryAuthorTagTypeHelp') }}
      </a-typography-text>
    </a-form-item>

    <a-space>
      <a-button type="primary" :loading="saving" @click="save">
        {{ $t('save') }}
      </a-button>
      <a-button :disabled="saving" @click="reset">
        {{ $t('resetToDefault') }}
      </a-button>
    </a-space>
  </a-form>
</template>
