// apps/web/src/components/tags/TagTypeManager.tsx
import { Button, Checkbox, Divider, Empty, Form, Input, InputNumber, List, Modal, Select, Space, Spin, Tag, Typography, message } from 'antd'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { http } from '@/api/http'
import { useLibraryStore } from '@/store/library'

export type TagType = {
  id: number
  name: string
  sort_order: number | null
}

export type TagTypeManagerProps = {
  types: TagType[]
  onDataChanged: () => void
}

export default function TagTypeManager({ types, onDataChanged }: TagTypeManagerProps) {
  const { t } = useTranslation()
  const checkActiveTasks = useLibraryStore((state) => state.checkActiveTasks)

  const [isCreating, setIsCreating] = useState(false)
  const [newTypeName, setNewTypeName] = useState('')
  const [newTypeSortOrder, setNewTypeSortOrder] = useState(0)

  const [editingTypeId, setEditingTypeId] = useState<number | null>(null)
  const [editingTypeName, setEditingTypeName] = useState('')
  const [editingTypeSortOrder, setEditingTypeSortOrder] = useState(0)

  const [scannedTags, setScannedTags] = useState<string[]>([])
  const [isLoadingScannedTags, setIsLoadingScannedTags] = useState(false)
  const [showScanner, setShowScanner] = useState(false)
  const [selectedScannedTags, setSelectedScannedTags] = useState<string[]>([])
  const [selectedTagType, setSelectedTagType] = useState<number | null>(null)

  useEffect(() => {
    if (!showScanner) {
      setSelectedScannedTags([])
    }
  }, [showScanner])

  const resetCreateForm = () => {
    setIsCreating(false)
    setNewTypeName('')
    setNewTypeSortOrder(0)
  }

  const openCreateDialog = () => {
    setNewTypeName('')
    setNewTypeSortOrder(0)
    setIsCreating(true)
  }

  const createType = async () => {
    if (!newTypeName.trim()) {
      message.warning(t('tagNameAndTypeRequired'))
      return
    }
    try {
      await http.post('/api/v1/tag-types', {
        name: newTypeName,
        sort_order: newTypeSortOrder
      })
      message.success(t('settingsSavedSuccessfully'))
      resetCreateForm()
      onDataChanged()
    } catch (error) {
      console.error('创建标签类型失败：', error)
      message.error(t('errorCreatingTagType') + ((error as any)?.response?.data?.error || ''))
    }
  }

  const deleteType = (id: number) => {
    Modal.confirm({
      title: t('confirmDeleteTagType'),
      okType: 'danger',
      okText: t('delete'),
      cancelText: t('cancel'),
      onOk: async () => {
        try {
          await http.delete(`/api/v1/tag-types/${id}`)
          message.success(t('settingsSavedSuccessfully'))
          onDataChanged()
        } catch (error) {
          console.error('删除标签类型失败：', error)
          message.error(t('errorDeletingTagType') + ((error as any)?.response?.data?.error || ''))
        }
      }
    })
  }

  const startEditing = (type: TagType) => {
    setEditingTypeId(type.id)
    setEditingTypeName(type.name)
    setEditingTypeSortOrder(type.sort_order || 0)
  }

  const cancelEditing = () => {
    setEditingTypeId(null)
  }

  const saveEdit = async () => {
    if (!editingTypeId) {
      return
    }
    if (!editingTypeName.trim()) {
      message.warning(t('tagNameAndTypeRequired'))
      return
    }
    try {
      await http.put(`/api/v1/tag-types/${editingTypeId}`, {
        name: editingTypeName,
        sort_order: editingTypeSortOrder
      })
      message.success(t('settingsSavedSuccessfully'))
      cancelEditing()
      onDataChanged()
    } catch (error) {
      console.error('更新标签类型失败：', error)
      message.error(t('errorUpdatingTagType') + ((error as any)?.response?.data?.error || ''))
    }
  }

  const startScan = async () => {
    setShowScanner(true)
    setIsLoadingScannedTags(true)
    setSelectedScannedTags([])
    setSelectedTagType(types[0]?.id ?? null)
    try {
      const response = await http.get('/api/v1/reports/undefined-tags')
      setScannedTags((response?.data || []) as string[])
    } catch (error) {
      console.error('扫描未定义标签失败：', error)
      message.error(t('errorScanningTags') + ((error as any)?.response?.data?.error || ''))
    } finally {
      setIsLoadingScannedTags(false)
      checkActiveTasks().catch(() => {})
    }
  }

  const addSelectedTags = async () => {
    if (!selectedScannedTags.length || !selectedTagType) {
      message.warning(t('selectTagsAndType'))
      return
    }
    try {
      for (const tagName of selectedScannedTags) {
        await http.post('/api/v1/tags', { name: tagName, type_id: selectedTagType })
      }
      message.success(t('tagsAddedSuccessfully'))
      setShowScanner(false)
      setScannedTags([])
      onDataChanged()
    } catch (error) {
      console.error('新增标签失败：', error)
      message.error(t('errorAddingTags') + ((error as any)?.response?.data?.error || ''))
    }
  }

  return (
    <Space direction="vertical" size="middle" className="w-full">
      <List
        bordered
        dataSource={types}
        itemLayout="horizontal"
        renderItem={(item) => (
          <List.Item key={`tag-type-${item.id}`}>
            {editingTypeId === item.id ? (
              <Space wrap className="w-full">
                <Input value={editingTypeName} placeholder={t('typeName')} style={{ minWidth: 180 }} onChange={(e) => setEditingTypeName(e.target.value)} />
                <InputNumber value={editingTypeSortOrder} placeholder={t('sortValue')} style={{ width: 120 }} onChange={(v) => setEditingTypeSortOrder(Number(v ?? 0))} />
                <Space size="small">
                  <Button type="primary" size="small" onClick={() => saveEdit().catch(() => {})}>
                    {t('save')}
                  </Button>
                  <Button size="small" onClick={cancelEditing}>
                    {t('cancel')}
                  </Button>
                </Space>
              </Space>
            ) : (
              <div className="flex w-full flex-wrap items-center justify-between gap-3">
                <div>
                  <Typography.Text strong>{item.name}</Typography.Text>
                  <Tag className="ml-2">
                    {t('sortOrder')}: {item.sort_order}
                  </Tag>
                </div>
                <Space size="small">
                  <Button size="small" onClick={() => startEditing(item)}>
                    {t('edit')}
                  </Button>
                  <Button danger size="small" onClick={() => deleteType(item.id)}>
                    {t('delete')}
                  </Button>
                </Space>
              </div>
            )}
          </List.Item>
        )}
        footer={
          <Button type="dashed" block onClick={openCreateDialog}>
            + {t('newType')}
          </Button>
        }
      />

      <Modal
        open={isCreating}
        title={t('newType')}
        okText={t('save')}
        cancelText={t('cancel')}
        onOk={() => createType().catch(() => {})}
        onCancel={resetCreateForm}
      >
        <Form layout="vertical">
          <Form.Item label={t('typeName')} required>
            <Input value={newTypeName} onChange={(e) => setNewTypeName(e.target.value)} />
          </Form.Item>
          <Form.Item label={t('sortValue')}>
            <InputNumber value={newTypeSortOrder} style={{ width: 160 }} onChange={(v) => setNewTypeSortOrder(Number(v ?? 0))} />
          </Form.Item>
        </Form>
      </Modal>

      <Divider />

      <Button type="primary" ghost onClick={() => startScan().catch(() => {})}>
        {t('scanNewTags')}
      </Button>

      <Modal
        open={showScanner}
        title={t('foundUndefinedTags')}
        okText={t('addSelectedTags')}
        cancelText={t('close')}
        okButtonProps={{ disabled: selectedScannedTags.length === 0 || !selectedTagType }}
        onOk={() => addSelectedTags().catch(() => {})}
        onCancel={() => setShowScanner(false)}
      >
        <Spin spinning={isLoadingScannedTags}>
          {!isLoadingScannedTags && scannedTags.length === 0 ? (
            <Empty description={t('noNewTagsFound')} />
          ) : (
            <Space direction="vertical" size="middle" className="w-full">
              <Checkbox.Group
                value={selectedScannedTags}
                onChange={(value) => setSelectedScannedTags(value as string[])}
                className="grid grid-cols-1 sm:grid-cols-2 gap-2"
              >
                {scannedTags.map((tag) => (
                  <Checkbox key={`scanned-${tag}`} value={tag}>
                    {tag}
                  </Checkbox>
                ))}
              </Checkbox.Group>

              <Form layout="vertical">
                <Form.Item label={t('tagTypes')}>
                  <Select
                    value={selectedTagType ?? undefined}
                    placeholder={t('type')}
                    onChange={(value) => setSelectedTagType(Number(value))}
                    options={types.map((type) => ({ value: type.id, label: type.name }))}
                  />
                </Form.Item>
              </Form>

              <Typography.Text type="secondary">{t('tagsSelected', { count: selectedScannedTags.length })}</Typography.Text>
            </Space>
          )}
        </Spin>
      </Modal>
    </Space>
  )
}

// frontend/src/components/TagTypeManager.vue
<script setup>
import { ref } from 'vue';
import axios from 'axios';
import { useI18n } from 'vue-i18n';

const { t } = useI18n();

const props = defineProps({
  types: {
    type: Array,
    required: true,
  },
});

const emit = defineEmits(['dataChanged']);

const newTypeName = ref('');
const newTypeSortOrder = ref(0);
const isCreating = ref(false);
const editingTypeId = ref(null);
const editingTypeName = ref('');
const editingTypeSortOrder = ref(0);

const scannedTags = ref([]);
const isLoadingScannedTags = ref(false);
const showScanner = ref(false);
const selectedScannedTags = ref([]);
const selectedTagType = ref(null);

const createType = async () => {
  if (!newTypeName.value.trim()) return;
  try {
    await axios.post('/api/v1/tag_types', {
      name: newTypeName.value,
      sort_order: newTypeSortOrder.value,
    });
    newTypeName.value = '';
    newTypeSortOrder.value = 0;
    emit('dataChanged');
  } catch (error) {
    console.error('Failed to create tag type:', error);
    alert(t('errorCreatingTagType') + (error.response?.data?.error || ''));
  }
};

const startScan = async () => {
  showScanner.value = true;
  isLoadingScannedTags.value = true;
  selectedScannedTags.value = [];
  if (props.types.length > 0) {
    selectedTagType.value = props.types[0].id;
  }
  try {
    const response = await axios.get('/api/v1/tags/scan-undefined-tags');
    scannedTags.value = response.data;
  } catch (error) {
    console.error('Failed to scan for undefined tags:', error);
    alert(t('errorScanningTags') + (error.response?.data?.error || ''));
  } finally {
    isLoadingScannedTags.value = false;
  }
};

const addSelectedTags = async () => {
  if (selectedScannedTags.value.length === 0 || !selectedTagType.value) {
    alert(t('selectTagsAndType'));
    return;
  }

  try {
    for (const tagName of selectedScannedTags.value) {
      await axios.post('/api/v1/tags', {
        name: tagName,
        type_id: selectedTagType.value,
      });
    }
    alert(t('tagsAddedSuccessfully'));
    showScanner.value = false;
    scannedTags.value = [];
    emit('dataChanged');
  } catch (error) {
    console.error('Failed to add tags:', error);
    alert(t('errorAddingTags') + (error.response?.data?.error || ''));
  }
};

const deleteType = async (id) => {
  if (!confirm(t('confirmDeleteTagType'))) return;
  try {
    await axios.delete(`/api/v1/tag_types/${id}`);
    emit('dataChanged');
  } catch (error) {
    console.error('Failed to delete tag type:', error);
    alert(t('errorDeletingTagType') + (error.response?.data?.error || ''));
  }
};

const startEditing = (type) => {
  editingTypeId.value = type.id;
  editingTypeName.value = type.name;
  editingTypeSortOrder.value = type.sort_order;
};

const cancelEditing = () => {
  editingTypeId.value = null;
};

const saveEdit = async () => {
  if (!editingTypeName.value.trim()) return;
  try {
    await axios.put(`/api/v1/tag_types/${editingTypeId.value}`, {
      name: editingTypeName.value,
      sort_order: editingTypeSortOrder.value,
    });
    cancelEditing();
    emit('dataChanged');
  } catch (error) {
    console.error('Failed to update tag type:', error);
    alert(t('errorUpdatingTagType') + (error.response?.data?.error || ''));
  }
};

</script>

<template>
  <div class="space-y-3">
    <div v-for="type in types" :key="type.id" class="p-2 rounded-md bg-gray-50 flex items-center justify-between">
      <div v-if="editingTypeId === type.id" class="flex-grow flex items-center space-x-2">
        <input v-model="editingTypeName" type="text" class="p-1 border rounded-md w-full" />
        <input v-model="editingTypeSortOrder" type="number" class="p-1 border rounded-md w-20" />
        <button @click="saveEdit" class="btn btn-primary btn-sm">&#10003;</button>
        <button @click="cancelEditing" class="btn btn-danger btn-sm">&#10005;</button>
      </div>
      <div v-else class="flex-grow">
        <span class="font-medium">{{ type.name }}</span>
        <span class="text-xs text-gray-500 ml-2">({{ t('sortOrder') }}: {{ type.sort_order }})</span>
      </div>
      <div v-if="editingTypeId !== type.id" class="flex space-x-2">
        <button @click="startEditing(type)" class="btn btn-secondary btn-sm">{{ $t('edit') }}</button>
        <button @click="deleteType(type.id)" class="btn btn-danger btn-sm">{{ $t('delete') }}</button>
      </div>
    </div>

    <!-- Create Form -->
    <div class="mt-4">
      <div v-if="!isCreating" @click="isCreating = true" class="cursor-pointer text-blue-600 hover:underline">
        + {{ $t('newType') }}
      </div>
      <div v-else class="p-3 bg-blue-50 rounded-md">
        <input v-model="newTypeName" type="text" :placeholder="$t('typeName')" class="p-1 border rounded-md w-full mb-2" />
        <input v-model="newTypeSortOrder" type="number" :placeholder="$t('sortValue')" class="p-1 border rounded-md w-full mb-2" />
        <div class="flex space-x-2">
          <button @click="createType" class="btn btn-primary">{{ $t('save') }}</button>
          <button @click="isCreating = false" class="btn btn-secondary">{{ $t('cancel') }}</button>
        </div>
      </div>
    </div>
    <hr />
    <!-- Undefined Tag Scanner -->
    <div class="mt-4">
        <button @click="startScan" class="btn btn-primary">
            {{ $t('scanNewTags') }}
        </button>
    </div>
    <div v-if="showScanner" class="mt-4 p-4 border rounded-md bg-gray-50">
      <h4 class="font-semibold text-lg mb-2">{{ $t('foundUndefinedTags') }}</h4>
      <div v-if="isLoadingScannedTags"></div>
      <div v-else-if="scannedTags.length === 0">{{ $t('noNewTagsFound') }}</div>
      <div v-else>
        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2 max-h-60 overflow-y-auto p-2 bg-white border rounded">
            <label v-for="tag in scannedTags" :key="tag" class="flex items-center space-x-2">
                <input type="checkbox" :value="tag" v-model="selectedScannedTags" class="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" />
                <span>{{ tag }}</span>
            </label>
        </div>
        <div class="mt-4 flex items-center space-x-4">
            <select v-model="selectedTagType" class="p-1 border rounded-md">
                <option v-for="type in types" :key="type.id" :value="type.id">{{ type.name }}</option>
            </select>
            <button @click="addSelectedTags" class="btn btn-primary" :disabled="selectedScannedTags.length === 0">{{ $t('addSelectedTags') }}</button>
            <button @click="showScanner = false" class="btn btn-secondary">{{ $t('close') }}</button>
        </div>
        <p class="text-sm text-gray-600 mt-2">{{ $t('tagsSelected', { count: selectedScannedTags.length }) }}</p>
      </div>
    </div>
  </div>
</template>
