// apps/web/src/components/MangaCard.vue
<script setup>
import { computed, ref, watch, onMounted, onBeforeUnmount, nextTick } from 'vue'
import axios from 'axios'
import { useI18n } from 'vue-i18n'
import { message } from 'ant-design-vue'
import { storeToRefs } from 'pinia'
import { useRouter } from 'vue-router'
import {
  HeartFilled,
  HeartOutlined,
  ReadOutlined,
  EditOutlined
} from '@ant-design/icons-vue'
import { useUiSettingsStore } from '@/store/uiSettings'
import { useAppSettingsStore } from '@/store/appSettings'

const { t } = useI18n()
const router = useRouter()

const sizeUnits = computed(() => [
  t('sizeUnitB'),
  t('sizeUnitKB'),
  t('sizeUnitMB'),
  t('sizeUnitGB'),
  t('sizeUnitTB')
])

const escapeXml = (value) =>
  String(value || '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')

const fallbackCover = computed(() => {
  const label = escapeXml(t('noCoverPlaceholder'))
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="300" height="400" viewBox="0 0 300 400">
      <rect width="300" height="400" fill="#1f1f1f"/>
      <rect x="18" y="18" width="264" height="364" rx="16" fill="#2a2a2a" stroke="#3a3a3a"/>
      <text x="150" y="206" text-anchor="middle" dominant-baseline="middle"
        fill="#9b9b9b" font-size="18" font-family="system-ui, -apple-system, Segoe UI, sans-serif">
        ${label}
      </text>
    </svg>
  `.trim()
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
})

const emit = defineEmits(['metadata-updated'])
const statusOrder = ['unread', 'in_progress', 'finished']

const props = defineProps({
  manga: {
    type: Object,
    required: true
  },
  hideWishlistButton: {
    type: Boolean,
    default: false
  },
  viewMode: {
    type: String,
    default: 'grid',
    validator: value => ['grid', 'list'].includes(value)
  }
})

const uiSettingsStore = useUiSettingsStore()
const { libraryAuthorTagTypeId } = storeToRefs(uiSettingsStore)
const appSettingsStore = useAppSettingsStore()
const { libraryLazyRootMarginPx } = storeToRefs(appSettingsStore)

const visibleFields = computed(() => uiSettingsStore.fieldsForViewMode(props.viewMode))
const hasField = (key) => visibleFields.value.includes(key)
const hasAnyField = (keys) => keys.some(key => hasField(key))

const coverHost = ref(null)
const shouldLoadCover = ref(false)
let coverObserver = null

const teardownCoverObserver = () => {
  if (coverObserver) {
    coverObserver.disconnect()
    coverObserver = null
  }
}

const setupCoverObserver = () => {
  if (shouldLoadCover.value) {
    return
  }
  teardownCoverObserver()

  if (!coverHost.value) {
    return
  }
  if (!('IntersectionObserver' in window)) {
    shouldLoadCover.value = true
    return
  }

  coverObserver = new IntersectionObserver(
    entries => {
      if (entries.some(entry => entry.isIntersecting)) {
        shouldLoadCover.value = true
        teardownCoverObserver()
      }
    },
    { rootMargin: `${libraryLazyRootMarginPx.value}px 0px` }
  )
  coverObserver.observe(coverHost.value)
}

const isLiked = ref(!!props.manga.is_liked)
const localStatus = ref(props.manga.reading_status || 'unread')
const progressPercent = ref(props.manga.progress_percent ?? 0)
const localLastReadPage = ref(props.manga.last_read_page ?? 0)
const updatingStatus = ref(false)

onMounted(() => nextTick(() => setupCoverObserver()))
onBeforeUnmount(() => teardownCoverObserver())

watch(
  () => props.viewMode,
  () => nextTick(() => setupCoverObserver())
)
watch(
  () => props.manga.cover_url,
  () => {
    shouldLoadCover.value = false
    nextTick(() => setupCoverObserver())
  }
)

watch(
  () => props.manga.is_liked,
  newVal => {
    isLiked.value = !!newVal
  }
)
watch(
  () => props.manga.reading_status,
  newVal => {
    localStatus.value = newVal || 'unread'
  }
)
watch(
  () => props.manga.progress_percent,
  newVal => {
    progressPercent.value = newVal ?? 0
  }
)
watch(
  () => props.manga.last_read_page,
  newVal => {
    localLastReadPage.value = newVal ?? 0
  }
)

const fileName = computed(() => props.manga.file_path?.split(/[\\/]/).pop() || '')
const displayName = computed(() => props.manga.display_name || fileName.value)
const folderName = computed(() => props.manga.folder_name || '')
const sanitizedTags = computed(() => props.manga.tags || [])

const normalizedProgress = computed(() => Math.min(100, Math.max(0, progressPercent.value ?? 0)))
const progressPercentDisplay = computed(() => `${Math.round(normalizedProgress.value)}%`)

const statusMetaMap = computed(() => ({
  unread: {
    label: t('statusUnread'),
    short: t('statusUnreadShort'),
    color: 'default',
    progress: '#bfbfbf'
  },
  in_progress: {
    label: t('statusInProgress'),
    short: t('statusInProgressShort'),
    color: 'orange',
    progress: '#fa8c16'
  },
  finished: {
    label: t('statusFinished'),
    short: t('statusFinishedShort'),
    color: 'green',
    progress: '#52c41a'
  }
}))

const statusMeta = computed(() => statusMetaMap.value[localStatus.value] || statusMetaMap.value.unread)
const statusButtons = computed(() =>
  statusOrder.map(value => ({
    value,
    label: statusMetaMap.value[value].short
  }))
)

const formatBytes = bytes => {
  if (!bytes) {
    return `0 ${sizeUnits.value[0]}`
  }
  const exponent = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), sizeUnits.value.length - 1)
  const size = bytes / Math.pow(1024, exponent)
  const unit = sizeUnits.value[exponent] || sizeUnits.value[sizeUnits.value.length - 1]
  return `${size.toFixed(size >= 10 ? 0 : 1)} ${unit}`
}

const formatDateTime = isoString => {
  if (!isoString) {
    return '--'
  }
  try {
    return new Date(isoString).toLocaleString()
  } catch (_error) {
    return isoString
  }
}

const fileSizeDisplay = computed(() =>
  props.manga.file_size ? formatBytes(props.manga.file_size) : '--'
)
const lastReadDisplay = computed(() =>
  props.manga.last_read_date ? formatDateTime(props.manga.last_read_date) : t('lastReadNever')
)
const addedAtDisplay = computed(() =>
  props.manga.add_date ? formatDateTime(props.manga.add_date) : '--'
)
const likedAtDisplay = computed(() =>
  props.manga.liked_at ? formatDateTime(props.manga.liked_at) : '--'
)

const authorNames = computed(() => {
  const typeId = libraryAuthorTagTypeId.value
  if (!typeId) {
    return []
  }
  return sanitizedTags.value
    .filter(tag => tag.type_id === typeId)
    .map(tag => tag.name)
    .filter(Boolean)
})
const authorsDisplay = computed(() => authorNames.value.slice(0, 4).join(' / '))

const progressSummary = computed(() => {
  const total = props.manga.total_pages || 0
  const lastRead = localLastReadPage.value || 0

  if (!total) {
    return t('progressUnknown')
  }
  if (localStatus.value === 'finished') {
    return t('progressFinished')
  }
  if (localStatus.value === 'unread') {
    return t('progressUnread')
  }
  return t('progressCurrent', { page: Math.min(total, lastRead + 1), total })
})

const applyServerUpdate = payload => {
  if (!payload) {
    return
  }
  localStatus.value = payload.reading_status || localStatus.value
  progressPercent.value = payload.progress_percent ?? progressPercent.value
  localLastReadPage.value = payload.last_read_page ?? localLastReadPage.value
  isLiked.value = payload.is_liked ?? isLiked.value
  emit('metadata-updated', payload)
}

const updateStatus = async status => {
  if (updatingStatus.value || !status) {
    return
  }
  updatingStatus.value = true
  try {
    const response = await axios.patch(`/api/v1/files/${props.manga.id}`, { reading_status: status })
    applyServerUpdate(response.data)
  } catch (error) {
    console.error('更新阅读状态失败：', error)
    message.error(t('failedToUpdateStatus'))
  } finally {
    updatingStatus.value = false
  }
}

const cycleStatus = async event => {
  event?.stopPropagation()
  event?.preventDefault()
  const currentIndex = Math.max(0, statusOrder.indexOf(localStatus.value))
  const nextStatus = statusOrder[(currentIndex + 1) % statusOrder.length]
  await updateStatus(nextStatus)
}

const setStatus = async (status, event) => {
  event?.stopPropagation()
  event?.preventDefault()
  await updateStatus(status)
}

const toggleLike = async event => {
  event?.stopPropagation()
  event?.preventDefault()

  const originalLikedState = isLiked.value
  isLiked.value = !isLiked.value

  try {
    if (isLiked.value) {
      await axios.put(`/api/v1/likes/${props.manga.id}`)
    } else {
      await axios.delete(`/api/v1/likes/${props.manga.id}`)
    }
    emit('metadata-updated', {
      ...props.manga,
      is_liked: isLiked.value,
      liked_at: isLiked.value ? new Date().toISOString() : null
    })
  } catch (error) {
    isLiked.value = originalLikedState
    console.error('更新喜欢状态失败：', error)
    message.error(t('failedToToggleLike'))
  }
}

const openReader = () => {
  router.push({ name: 'reader', params: { id: props.manga.id } })
}

const openEdit = (event) => {
  event?.stopPropagation()
  event?.preventDefault()
  router.push({ name: 'edit', params: { id: props.manga.id } })
}
</script>

<template>
  <div v-if="viewMode === 'grid'" class="manga-card-grid">
    <a-card
      hoverable
      class="manga-card-grid__card"
      :bodyStyle="{ padding: '12px' }"
      @click="openReader"
    >
      <template #cover>
        <div ref="coverHost" class="manga-card-grid__cover">
          <a-image
            v-if="shouldLoadCover"
            :src="manga.cover_url"
            :alt="displayName"
            :fallback="fallbackCover"
            :preview="false"
          />
          <div v-else class="manga-card-cover__placeholder"></div>
          <a-tag
            v-if="hasField('reading_status_tag')"
            class="manga-card-grid__status"
            :color="statusMeta.color"
            @click.stop="cycleStatus"
          >
            {{ statusMeta.label }}
          </a-tag>
          <a-button
            v-if="!hideWishlistButton"
            type="text"
            shape="circle"
            size="small"
            class="manga-card-grid__like"
            @click="toggleLike"
          >
            <HeartFilled v-if="isLiked" style="color: #f5222d" />
            <HeartOutlined v-else />
          </a-button>
          <div class="manga-card-grid__cover-edit">
            <a-button type="primary" size="small" block @click="openEdit">
              <template #icon>
                <EditOutlined />
              </template>
              {{ t('edit') }}
            </a-button>
          </div>
        </div>
      </template>

      <a-card-meta
        :title="displayName"
        :description="hasField('folder_name') ? folderName : ''"
      />

      <div class="manga-card-grid__meta">
        <div v-if="hasAnyField(['file_size', 'progress_percent'])" class="manga-card-grid__row">
          <a-typography-text v-if="hasField('file_size')" type="secondary">
            {{ fileSizeDisplay }}
          </a-typography-text>
          <a-typography-text v-if="hasField('progress_percent')" type="secondary">
            {{ progressPercentDisplay }}
          </a-typography-text>
        </div>

        <a-progress
          v-if="hasField('progress_bar')"
          :percent="normalizedProgress"
          :show-info="false"
          :stroke-color="statusMeta.progress"
        />

        <a-typography-text
          v-if="hasField('progress_summary')"
          type="secondary"
          class="manga-card-grid__subtitle"
        >
          {{ progressSummary }}
        </a-typography-text>

        <a-typography-text v-if="hasField('authors') && authorsDisplay" type="secondary" class="manga-card-grid__subtitle">
          {{ t('authorsLabel') }}: {{ authorsDisplay }}
        </a-typography-text>

        <a-typography-text v-if="hasField('add_date')" type="secondary" class="manga-card-grid__subtitle">
          {{ t('addedAtLabel') }}: {{ addedAtDisplay }}
        </a-typography-text>

        <a-typography-text v-if="hasField('liked_at') && manga.is_liked" type="secondary" class="manga-card-grid__subtitle">
          {{ t('likedAtLabel') }}: {{ likedAtDisplay }}
        </a-typography-text>

        <div v-if="hasAnyField(['total_pages', 'last_read_date'])" class="manga-card-grid__row">
          <a-typography-text v-if="hasField('total_pages')" type="secondary">
            {{ manga.total_pages || 0 }} {{ t('pages') }}
          </a-typography-text>
          <a-typography-text v-if="hasField('last_read_date')" type="secondary">
            {{ lastReadDisplay }}
          </a-typography-text>
        </div>
      </div>

      <div v-if="sanitizedTags.length" class="manga-card-grid__tags">
        <a-tag
          v-for="tag in sanitizedTags"
          :key="`grid-tag-${tag.id}`"
        >
          {{ tag.name }}
        </a-tag>
      </div>
    </a-card>
  </div>
  <a-card v-else class="manga-card-list" :bodyStyle="{ padding: '16px' }">
    <a-row :gutter="16" align="middle">
      <a-col :xs="8" :sm="6" :md="5">
        <div ref="coverHost" class="manga-card-list__cover">
          <a-image
            v-if="shouldLoadCover"
            :src="manga.cover_url"
            :alt="displayName"
            :fallback="fallbackCover"
            :preview="false"
          />
          <div v-else class="manga-card-cover__placeholder"></div>
          <a-button
            v-if="!hideWishlistButton"
            type="text"
            shape="circle"
            size="small"
            class="manga-card-list__like"
            @click="toggleLike"
          >
            <HeartFilled v-if="isLiked" style="color: #f5222d" />
            <HeartOutlined v-else />
          </a-button>
        </div>
      </a-col>
      <a-col :xs="16" :sm="18" :md="19">
        <div class="manga-card-list__header">
          <RouterLink
            :to="{ name: 'reader', params: { id: manga.id } }"
            class="manga-card-list__title"
          >
            {{ displayName }}
          </RouterLink>
          <a-tag
            v-if="hasField('reading_status_tag')"
            :color="statusMeta.color"
            class="manga-card-list__status"
            @click.prevent="cycleStatus"
          >
            {{ statusMeta.label }}
          </a-tag>
        </div>
        <a-typography-text v-if="hasField('folder_name')" type="secondary" class="manga-card-list__folder">
          {{ folderName }}
        </a-typography-text>

        <div v-if="hasAnyField(['progress_bar', 'progress_percent'])" class="manga-card-list__progress">
          <a-progress
            v-if="hasField('progress_bar')"
            :percent="normalizedProgress"
            :stroke-color="statusMeta.progress"
            size="small"
            :show-info="false"
          />
          <a-typography-text v-if="hasField('progress_percent')" type="secondary">
            {{ progressPercentDisplay }}
          </a-typography-text>
        </div>
        <a-typography-text v-if="hasField('progress_summary')" type="secondary" class="manga-card-list__summary">
          {{ progressSummary }}
        </a-typography-text>

        <a-typography-text v-if="hasField('authors') && authorsDisplay" type="secondary">
          {{ t('authorsLabel') }}: {{ authorsDisplay }}
        </a-typography-text>

        <a-space v-if="hasAnyField(['total_pages', 'file_size', 'last_read_date', 'add_date', 'liked_at'])" wrap size="small" class="manga-card-list__stats">
          <span v-if="hasField('total_pages')">{{ t('pages') }}: {{ manga.total_pages || 0 }}</span>
          <span v-if="hasField('file_size')">{{ t('fileSizeLabel') }}: {{ fileSizeDisplay }}</span>
          <span v-if="hasField('last_read_date')">{{ t('lastReadAt') }}: {{ lastReadDisplay }}</span>
          <span v-if="hasField('add_date')">{{ t('addedAtLabel') }}: {{ addedAtDisplay }}</span>
          <span v-if="hasField('liked_at') && manga.is_liked">{{ t('likedAtLabel') }}: {{ likedAtDisplay }}</span>
        </a-space>

        <div v-if="sanitizedTags.length" class="manga-card-list__tags">
          <a-tag
            v-for="tag in sanitizedTags"
            :key="`list-tag-${tag.id}`"
          >
            {{ tag.name }}
          </a-tag>
        </div>

        <div class="manga-card-list__actions">
          <RouterLink :to="{ name: 'reader', params: { id: manga.id } }" custom v-slot="{ navigate }">
            <a-button type="primary" @click="navigate">
              <template #icon>
                <ReadOutlined />
              </template>
              {{ t('read') }}
            </a-button>
          </RouterLink>
          <RouterLink :to="{ name: 'edit', params: { id: manga.id } }" custom v-slot="{ navigate }">
            <a-button @click="navigate">
              <template #icon>
                <EditOutlined />
              </template>
              {{ t('edit') }}
            </a-button>
          </RouterLink>
          <a-segmented
            class="manga-card-list__status-switcher"
            :value="localStatus"
            :options="statusButtons"
            size="small"
            :block="true"
            :disabled="updatingStatus"
            @change="value => setStatus(value)"
          />
        </div>
      </a-col>
    </a-row>
  </a-card>
</template>

<style scoped>
.manga-card-grid__card {
  position: relative;
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.manga-card-grid__cover {
  position: relative;
  width: 100%;
  height: 0;
  padding-bottom: 150%;
  overflow: hidden;
  border-radius: 12px;
}

.manga-card-grid__cover :deep(.ant-image) {
  position: absolute;
  inset: 0;
}

.manga-card-grid__cover-edit {
  position: absolute;
  left: 10px;
  right: 10px;
  bottom: 10px;
  opacity: 0;
  transform: translateY(6px);
  pointer-events: none;

  transition: opacity 160ms ease, transform 160ms ease;
}

.manga-card-grid__cover:hover .manga-card-grid__cover-edit {
  opacity: 1;
  transform: translateY(0);
  pointer-events: auto;
}

.manga-card-grid__cover-edit :deep(.ant-btn) {
  background: rgba(0, 0, 0, 0.55);
  border-color: rgba(255, 255, 255, 0.25);
  color: #fff;
}

.manga-card-grid__cover-edit :deep(.ant-btn:hover) {
  background: rgba(0, 0, 0, 0.65);
  border-color: rgba(255, 255, 255, 0.38);
  color: #fff;
}

.manga-card-cover__placeholder {
  position: absolute;
  inset: 0;
  background: #f2f4f7;
}

.manga-card-grid__cover :deep(.ant-image-img),
.manga-card-list__cover :deep(.ant-image-img) {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.manga-card-grid__status {
  position: absolute;
  top: 12px;
  left: 12px;
  cursor: pointer;
}

.manga-card-grid__like {
  position: absolute;
  top: 8px;
  right: 8px;
}

.manga-card-grid__like:hover :deep(.anticon) {
  color: #f5222d;
}

.manga-card-grid__meta {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.manga-card-grid__row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 6px;
}

.manga-card-grid__tags {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.manga-card-list {
  width: 100%;
}

.manga-card-list__cover {
  position: relative;
  border-radius: 12px;
  overflow: hidden;
  width: 100%;
  aspect-ratio: 3 / 4;
}

.manga-card-list__cover :deep(.ant-image) {
  position: absolute;
  inset: 0;
}

.manga-card-list__like {
  position: absolute;
  top: 8px;
  right: 8px;
}

.manga-card-list__like:hover :deep(.anticon) {
  color: #f5222d;
}

.manga-card-list__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 8px;
}

.manga-card-list__title {
  font-size: 1.1rem;
  font-weight: 600;
  color: #1f2937;
  text-decoration: none;
}

.manga-card-list__title:hover {
  color: #1677ff;
}

.manga-card-list__status {
  cursor: pointer;
}

.manga-card-list__folder {
  display: block;
  margin-bottom: 6px;
}

.manga-card-list__progress {
  display: flex;
  align-items: center;
  gap: 12px;
}

.manga-card-list__summary {
  display: block;
  margin-top: 4px;
}

.manga-card-list__stats {
  font-size: 0.85rem;
  color: #475467;
  margin-top: 8px;
}

.manga-card-list__tags {
  margin-top: 8px;
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.manga-card-list__actions {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  align-items: center;
  margin-top: 12px;
}

.manga-card-list__status-switcher {
  min-width: 200px;
}
</style>

// apps/web/src/components/library/MangaCard.tsx
import { EditOutlined, HeartFilled, HeartOutlined, ReadOutlined } from '@ant-design/icons'
import { Button, Card, Progress, Segmented, Space, Tag, Typography, message } from 'antd'
import type { SegmentedProps } from 'antd'
import type { CSSProperties } from 'react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import { http } from '@/api/http'
import { useAppSettingsStore } from '@/store/appSettings'
import type { LibraryCardFieldKey } from '@/store/uiSettings'
import { useUiSettingsStore } from '@/store/uiSettings'

export type MangaTag = {
  id: number
  name: string
  type_id: number
}

export type MangaItem = {
  id: number
  file_path?: string | null
  display_name?: string | null
  folder_name?: string | null
  cover_url?: string | null
  file_size?: number | null
  total_pages?: number | null
  last_read_page?: number | null
  last_read_date?: string | null
  add_date?: string | null
  liked_at?: string | null
  reading_status?: 'unread' | 'in_progress' | 'finished' | string | null
  progress_percent?: number | null
  is_liked?: boolean | null
  tags?: MangaTag[] | null
}

export type MangaCardProps = {
  manga: MangaItem
  hideWishlistButton?: boolean
  viewMode?: 'grid' | 'list'
  onMetadataUpdated?: (next: MangaItem) => void
}

const statusOrder = ['unread', 'in_progress', 'finished'] as const

const escapeXml = (value: unknown) =>
  String(value || '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')

const formatDateTime = (value: string | null | undefined) => {
  if (!value) {
    return ''
  }
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return ''
  }
  return date.toLocaleString()
}

export default function MangaCard({ manga, hideWishlistButton = false, viewMode = 'grid', onMetadataUpdated }: MangaCardProps) {
  const navigate = useNavigate()
  const { t } = useTranslation()

  const libraryLazyRootMarginPx = useAppSettingsStore((state) => state.libraryLazyRootMarginPx)
  const libraryCardFields = useUiSettingsStore((state) => state.libraryCardFields)
  const libraryAuthorTagTypeId = useUiSettingsStore((state) => state.libraryAuthorTagTypeId)

  const visibleFields = useMemo<LibraryCardFieldKey[]>(
    () => (viewMode === 'list' ? libraryCardFields.list : libraryCardFields.grid),
    [libraryCardFields.grid, libraryCardFields.list, viewMode]
  )

  const hasField = (key: LibraryCardFieldKey) => visibleFields.includes(key)
  const hasAnyField = (keys: LibraryCardFieldKey[]) => keys.some((key) => hasField(key))

  const sizeUnits = useMemo(() => [t('sizeUnitB'), t('sizeUnitKB'), t('sizeUnitMB'), t('sizeUnitGB'), t('sizeUnitTB')], [t])

  const formatBytes = (bytes: number | null | undefined, decimals = 2) => {
    if (!bytes) {
      return `0 ${sizeUnits[0]}`
    }
    const k = 1024
    const dm = decimals < 0 ? 0 : decimals
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    const value = Number.parseFloat((bytes / Math.pow(k, i)).toFixed(dm))
    const unit = sizeUnits[i] || sizeUnits[sizeUnits.length - 1]
    return `${value} ${unit}`
  }

  const fallbackCover = useMemo(() => {
    const label = escapeXml(t('noCoverPlaceholder'))
    const svg = `
      <svg xmlns="http://www.w3.org/2000/svg" width="300" height="400" viewBox="0 0 300 400">
        <rect width="300" height="400" fill="#1f1f1f"/>
        <rect x="18" y="18" width="264" height="364" rx="16" fill="#2a2a2a" stroke="#3a3a3a"/>
        <text x="150" y="206" text-anchor="middle" dominant-baseline="middle"
          fill="#9b9b9b" font-size="18" font-family="system-ui, -apple-system, Segoe UI, sans-serif">
          ${label}
        </text>
      </svg>
    `.trim()
    return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
  }, [t])

  const coverHostRef = useRef<HTMLDivElement | null>(null)
  const coverObserverRef = useRef<IntersectionObserver | null>(null)
  const [shouldLoadCover, setShouldLoadCover] = useState(false)

  const [isLiked, setIsLiked] = useState(Boolean(manga.is_liked))
  const [localStatus, setLocalStatus] = useState((manga.reading_status as any) || 'unread')
  const [progressPercent, setProgressPercent] = useState<number>(manga.progress_percent ?? 0)
  const [localLastReadPage, setLocalLastReadPage] = useState<number>(manga.last_read_page ?? 0)
  const [updatingStatus, setUpdatingStatus] = useState(false)
  const [updatingLike, setUpdatingLike] = useState(false)

  useEffect(() => {
    setIsLiked(Boolean(manga.is_liked))
  }, [manga.is_liked])

  useEffect(() => {
    setLocalStatus((manga.reading_status as any) || 'unread')
  }, [manga.reading_status])

  useEffect(() => {
    setProgressPercent(manga.progress_percent ?? 0)
  }, [manga.progress_percent])

  useEffect(() => {
    setLocalLastReadPage(manga.last_read_page ?? 0)
  }, [manga.last_read_page])

  useEffect(() => {
    setShouldLoadCover(false)
  }, [manga.cover_url, viewMode])

  useEffect(() => {
    if (shouldLoadCover) {
      return
    }
    if (typeof window === 'undefined') {
      setShouldLoadCover(true)
      return
    }
    const host = coverHostRef.current
    if (!host) {
      return
    }
    if (!('IntersectionObserver' in window)) {
      setShouldLoadCover(true)
      return
    }

    coverObserverRef.current?.disconnect()
    coverObserverRef.current = new IntersectionObserver(
      (entries) => {
        if (entries.some((entry) => entry.isIntersecting)) {
          setShouldLoadCover(true)
          coverObserverRef.current?.disconnect()
          coverObserverRef.current = null
        }
      },
      { rootMargin: `${libraryLazyRootMarginPx}px 0px` }
    )
    coverObserverRef.current.observe(host)

    return () => {
      coverObserverRef.current?.disconnect()
      coverObserverRef.current = null
    }
  }, [libraryLazyRootMarginPx, shouldLoadCover])

  const fileName = useMemo(() => (manga.file_path ? manga.file_path.split(/[\\/]/).pop() || '' : ''), [manga.file_path])
  const displayName = useMemo(() => manga.display_name || fileName || `#${manga.id}`, [fileName, manga.display_name, manga.id])
  const folderName = useMemo(() => manga.folder_name || '', [manga.folder_name])
  const tags = useMemo(() => (Array.isArray(manga.tags) ? manga.tags : []), [manga.tags])
  const authorTags = useMemo(() => {
    if (!libraryAuthorTagTypeId) {
      return []
    }
    return tags.filter((tag) => tag.type_id === libraryAuthorTagTypeId)
  }, [libraryAuthorTagTypeId, tags])

  const normalizedProgress = useMemo(() => Math.min(100, Math.max(0, progressPercent ?? 0)), [progressPercent])
  const progressPercentDisplay = useMemo(() => `${Math.round(normalizedProgress)}%`, [normalizedProgress])

  const statusMetaMap = useMemo(
    () => ({
      unread: { label: t('statusUnread'), short: t('statusUnreadShort'), color: 'default' as const, progress: '#bfbfbf' },
      in_progress: { label: t('statusInProgress'), short: t('statusInProgressShort'), color: 'orange' as const, progress: '#faad14' },
      finished: { label: t('statusFinished'), short: t('statusFinishedShort'), color: 'green' as const, progress: '#52c41a' }
    }),
    [t]
  )

  const resolvedStatusKey = useMemo(() => {
    const raw = String(localStatus || '').trim().toLowerCase()
    return (raw === 'in_progress' || raw === 'finished' || raw === 'unread' ? raw : 'unread') as 'unread' | 'in_progress' | 'finished'
  }, [localStatus])

  const statusMeta = statusMetaMap[resolvedStatusKey]

  const totalPages = useMemo(() => Number(manga.total_pages || 0), [manga.total_pages])
  const lastReadPage = useMemo(() => Number(localLastReadPage || 0), [localLastReadPage])

  const progressSummary = useMemo(() => {
    const total = Math.max(0, totalPages)
    if (resolvedStatusKey === 'finished') {
      return t('progressFinished')
    }
    if (resolvedStatusKey === 'unread') {
      return t('progressUnread')
    }
    return t('progressCurrent', { page: Math.min(total, lastReadPage + 1), total })
  }, [lastReadPage, resolvedStatusKey, t, totalPages])

  const applyServerUpdate = (payload: Partial<MangaItem> | null | undefined) => {
    if (!payload) {
      return
    }
    setLocalStatus((payload.reading_status as any) || localStatus)
    setProgressPercent(payload.progress_percent ?? progressPercent)
    setLocalLastReadPage(payload.last_read_page ?? localLastReadPage)
    setIsLiked(payload.is_liked ?? isLiked)
    onMetadataUpdated?.({ ...manga, ...payload })
  }

  const updateStatus = async (status: string) => {
    if (updatingStatus || !status) {
      return
    }
    setUpdatingStatus(true)
    try {
      const response = await http.patch(`/api/v1/files/${manga.id}`, { reading_status: status })
      applyServerUpdate(response.data)
    } catch (error) {
      console.error('更新阅读状态失败：', error)
      message.error(t('failedToUpdateStatus'))
    } finally {
      setUpdatingStatus(false)
    }
  }

  const cycleStatus = async (event?: { stopPropagation?: () => void; preventDefault?: () => void }) => {
    event?.stopPropagation?.()
    event?.preventDefault?.()
    const currentIndex = Math.max(0, statusOrder.indexOf(resolvedStatusKey))
    const nextStatus = statusOrder[(currentIndex + 1) % statusOrder.length]
    await updateStatus(nextStatus)
  }

  const setStatus: SegmentedProps['onChange'] = async (value) => {
    await updateStatus(String(value))
  }

  const toggleLike = async (event?: { stopPropagation?: () => void; preventDefault?: () => void }) => {
    event?.stopPropagation?.()
    event?.preventDefault?.()
    if (updatingLike) {
      return
    }

    const originalLikedState = isLiked
    const next = !isLiked
    setIsLiked(next)
    setUpdatingLike(true)

    try {
      if (next) {
        await http.put(`/api/v1/likes/${manga.id}`)
      } else {
        await http.delete(`/api/v1/likes/${manga.id}`)
      }
      onMetadataUpdated?.({
        ...manga,
        is_liked: next,
        liked_at: next ? new Date().toISOString() : null
      })
    } catch (error) {
      setIsLiked(originalLikedState)
      console.error('更新喜欢状态失败：', error)
      message.error(t('failedToToggleLike'))
    } finally {
      setUpdatingLike(false)
    }
  }

  const openReader = () => {
    navigate(`/reader/${manga.id}`)
  }

  const openEdit = (event?: { stopPropagation?: () => void; preventDefault?: () => void }) => {
    event?.stopPropagation?.()
    event?.preventDefault?.()
    navigate(`/edit/${manga.id}`)
  }

  const readButton = (
    <Button type="primary" icon={<ReadOutlined />} onClick={(event) => openReader()}>
      {t('read')}
    </Button>
  )

  const editButton = (
    <Button icon={<EditOutlined />} onClick={(event) => openEdit(event as any)}>
      {t('edit')}
    </Button>
  )

  const statusButtons = useMemo<SegmentedProps['options']>(
    () => [
      { value: 'unread', label: statusMetaMap.unread.short },
      { value: 'in_progress', label: statusMetaMap.in_progress.short },
      { value: 'finished', label: statusMetaMap.finished.short }
    ],
    [statusMetaMap]
  )

  const statsLine = useMemo(() => {
    const parts: string[] = []
    if (hasField('file_size')) {
      parts.push(formatBytes(manga.file_size ?? 0))
    }
    if (hasField('total_pages') && typeof manga.total_pages === 'number') {
      parts.push(`${manga.total_pages} ${t('pages')}`)
    }
    if (hasField('last_read_date')) {
      const value = formatDateTime(manga.last_read_date)
      if (value) {
        parts.push(`${t('lastReadAt')}: ${value}`)
      }
    }
    if (hasField('add_date')) {
      const value = formatDateTime(manga.add_date)
      if (value) {
        parts.push(`${t('addedAtLabel')}: ${value}`)
      }
    }
    if (hasField('liked_at') && isLiked) {
      const value = formatDateTime(manga.liked_at)
      if (value) {
        parts.push(`${t('likedAtLabel')}: ${value}`)
      }
    }
    return parts
  }, [formatBytes, hasField, isLiked, manga.add_date, manga.file_size, manga.last_read_date, manga.liked_at, manga.total_pages, t])

  const coverImage = useMemo(() => {
    const coverUrl = manga.cover_url || ''
    if (!shouldLoadCover || !coverUrl) {
      return <div className="manga-card-cover__placeholder" />
    }
    return <img src={coverUrl} alt={displayName} loading="lazy" onError={(event) => ((event.currentTarget.src = fallbackCover), undefined)} />
  }, [displayName, fallbackCover, manga.cover_url, shouldLoadCover])

  const progressBar =
    hasField('progress_bar') && totalPages > 0 ? (
      <Progress percent={Math.round(normalizedProgress)} showInfo={false} strokeColor={statusMeta.progress} />
    ) : null

  const progressSummaryNode = hasField('progress_summary') ? (
    <Typography.Text type="secondary" className="manga-card-list__summary">
      {progressSummary}
    </Typography.Text>
  ) : null

  const authorNode =
    hasField('authors') && authorTags.length ? (
      <Space wrap className="manga-card-grid__tags">
        {authorTags.map((tag) => (
          <Tag key={`author-${tag.id}`}>{tag.name}</Tag>
        ))}
      </Space>
    ) : null

  if (viewMode === 'list') {
    return (
      <Card hoverable className="manga-card-list" onClick={openReader}>
        <div className="manga-card-list__grid">
          <div className="manga-card-list__cover" ref={coverHostRef}>
            {coverImage}
            {!hideWishlistButton ? (
              <Button
                type="text"
                shape="circle"
                size="small"
                className="manga-card-list__like"
                loading={updatingLike}
                onClick={(event) => toggleLike(event as any)}
              >
                {isLiked ? <HeartFilled style={{ color: '#f5222d' }} /> : <HeartOutlined />}
              </Button>
            ) : null}
          </div>

          <div className="manga-card-list__content">
            <div className="manga-card-list__header">
              <Typography.Text strong className="manga-card-list__title" onClick={(event) => (event.stopPropagation(), openReader())}>
                {displayName}
              </Typography.Text>
              {hasField('reading_status_tag') ? (
                <Tag className="manga-card-list__status" color={statusMeta.color} onClick={(event) => cycleStatus(event as any)}>
                  {statusMeta.label}
                </Tag>
              ) : null}
            </div>

            {hasField('folder_name') && folderName ? (
              <Typography.Text type="secondary" className="manga-card-list__folder">
                {folderName}
              </Typography.Text>
            ) : null}

            {hasAnyField(['progress_percent', 'progress_bar']) ? (
              <div className="manga-card-list__progress">
                {hasField('progress_percent') ? <Typography.Text>{progressPercentDisplay}</Typography.Text> : null}
                <div className="flex-1">{progressBar}</div>
              </div>
            ) : null}

            {progressSummaryNode}
            {authorNode}

            {statsLine.length ? (
              <Typography.Text type="secondary" className="manga-card-list__stats">
                {statsLine.join(' · ')}
              </Typography.Text>
            ) : null}

            {tags.length ? (
              <div className="manga-card-list__tags">
                {tags.map((tag) => (
                  <Tag key={`list-tag-${tag.id}`}>{tag.name}</Tag>
                ))}
              </div>
            ) : null}

            <div className="manga-card-list__actions">
              <Space wrap>
                {readButton}
                {editButton}
              </Space>
              <Segmented
                className="manga-card-list__status-switcher"
                size="small"
                block
                value={resolvedStatusKey}
                options={statusButtons}
                disabled={updatingStatus}
                onChange={setStatus}
              />
            </div>
          </div>
        </div>
      </Card>
    )
  }

  const coverEditOverlay = (
    <div className="manga-card-grid__cover-edit">
      <Button type="primary" size="small" block icon={<EditOutlined />} onClick={(event) => openEdit(event as any)}>
        {t('edit')}
      </Button>
    </div>
  )

  const cardBodyStyle = useMemo(() => ({ padding: '12px' } as CSSProperties), [])

  return (
    <div className="manga-card-grid">
      <Card hoverable className="manga-card-grid__card" bodyStyle={cardBodyStyle} onClick={openReader}>
        <div ref={coverHostRef} className="manga-card-grid__cover">
          {coverImage}
          {hasField('reading_status_tag') ? (
            <Tag className="manga-card-grid__status" color={statusMeta.color} onClick={(event) => cycleStatus(event as any)}>
              {statusMeta.label}
            </Tag>
          ) : null}
          {!hideWishlistButton ? (
            <Button
              type="text"
              shape="circle"
              size="small"
              className="manga-card-grid__like"
              loading={updatingLike}
              onClick={(event) => toggleLike(event as any)}
            >
              {isLiked ? <HeartFilled style={{ color: '#f5222d' }} /> : <HeartOutlined />}
            </Button>
          ) : null}
          {coverEditOverlay}
        </div>

        <div className="manga-card-grid__meta">
          <div className="manga-card-grid__row">
            <Typography.Text strong ellipsis title={displayName}>
              {displayName}
            </Typography.Text>
          </div>

          {hasAnyField(['progress_percent', 'progress_bar', 'progress_summary']) ? (
            <Space direction="vertical" size={4} className="w-full">
              {hasField('progress_percent') ? <Typography.Text type="secondary">{progressPercentDisplay}</Typography.Text> : null}
              {progressBar}
              {progressSummaryNode}
            </Space>
          ) : null}

          {hasField('folder_name') && folderName ? (
            <Typography.Text type="secondary" ellipsis title={folderName}>
              {folderName}
            </Typography.Text>
          ) : null}

          {authorNode}

          {statsLine.length ? (
            <Typography.Text type="secondary" className="manga-card-grid__stats">
              {statsLine.join(' · ')}
            </Typography.Text>
          ) : null}

          {tags.length ? (
            <Space wrap className="manga-card-grid__tags">
              {tags.slice(0, 6).map((tag) => (
                <Tag key={`grid-tag-${tag.id}`}>{tag.name}</Tag>
              ))}
            </Space>
          ) : null}
        </div>
      </Card>
    </div>
  )
}
