// apps/web/src/components/RenameTemplateSettings.vue
<template>
  <a-space direction="vertical" size="large" class="w-full">
    <a-form layout="vertical" @submit.prevent>
      <a-form-item :label="$t('renameFilenameTemplate')">
        <a-textarea
          v-model:value="template"
          :placeholder="$t('renameFilenameTemplatePlaceholder')"
          :auto-size="{ minRows: 2, maxRows: 6 }"
        />
        <div class="mt-1 text-xs text-gray-500">
          {{ $t('renameFilenameTemplateHelp') }}
        </div>
      </a-form-item>

      <a-space>
        <a-button type="primary" :loading="saving" @click="save">
          {{ $t('save') }}
        </a-button>
        <a-button :disabled="saving" @click="resetToDefault">
          {{ $t('resetToDefault') }}
        </a-button>
      </a-space>
    </a-form>
  </a-space>
</template>

<script setup>
import { ref, watch } from 'vue'
import { message } from 'ant-design-vue'
import { useI18n } from 'vue-i18n'
import { useAppSettingsStore } from '@/store/appSettings'

const { t } = useI18n()
const appSettingsStore = useAppSettingsStore()

const saving = ref(false)
const template = ref(appSettingsStore.renameFilenameTemplate)

watch(
  () => appSettingsStore.renameFilenameTemplate,
  value => {
    template.value = value
  }
)

const save = async () => {
  saving.value = true
  try {
    await appSettingsStore.setRenameFilenameTemplate(template.value)
    message.success(t('settingsSavedSuccessfully'))
  } catch (error) {
    console.error('保存重命名模板失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}

const resetToDefault = async () => {
  saving.value = true
  try {
    await appSettingsStore.setRenameFilenameTemplate('')
    message.success(t('settingsSavedSuccessfully'))
  } catch (error) {
    console.error('重置重命名模板失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}
</script>

// apps/web/src/components/library/RenameTemplateSettings.tsx
import { Button, Form, Space, message } from 'antd'
import TextArea from 'antd/es/input/TextArea'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useAppSettingsStore } from '@/store/appSettings'

export default function RenameTemplateSettings() {
  const { t } = useTranslation()
  const renameFilenameTemplate = useAppSettingsStore((state) => state.renameFilenameTemplate)
  const setRenameFilenameTemplate = useAppSettingsStore((state) => state.setRenameFilenameTemplate)

  const [saving, setSaving] = useState(false)
  const [template, setTemplate] = useState(renameFilenameTemplate)

  useEffect(() => setTemplate(renameFilenameTemplate), [renameFilenameTemplate])

  const save = async () => {
    setSaving(true)
    try {
      await setRenameFilenameTemplate(template)
      message.success(t('settingsSavedSuccessfully'))
    } catch (error) {
      console.error('保存重命名模板失败：', error)
      message.error(t('failedToSaveSettings'))
    } finally {
      setSaving(false)
    }
  }

  const resetToDefault = async () => {
    setSaving(true)
    try {
      setTemplate('')
      await setRenameFilenameTemplate('')
      message.success(t('settingsSavedSuccessfully'))
    } catch (error) {
      console.error('重置重命名模板失败：', error)
      message.error(t('failedToSaveSettings'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <Space direction="vertical" size="large" className="w-full">
      <Form layout="vertical">
        <Form.Item label={t('renameFilenameTemplate')}>
          <TextArea
            value={template}
            placeholder={t('renameFilenameTemplatePlaceholder')}
            autoSize={{ minRows: 2, maxRows: 6 }}
            onChange={(event) => setTemplate(event.target.value)}
          />
          <div className="mt-1 text-xs text-gray-500">{t('renameFilenameTemplateHelp')}</div>
        </Form.Item>

        <Space>
          <Button type="primary" loading={saving} onClick={() => save().catch(() => {})}>
            {t('save')}
          </Button>
          <Button disabled={saving} onClick={() => resetToDefault().catch(() => {})}>
            {t('resetToDefault')}
          </Button>
        </Space>
      </Form>
    </Space>
  )
}
