// apps/web/src/components/glass/settings/ManagerAppearanceSettings.tsx
import { Button, Divider, Form, InputNumber, Space, Switch, message } from 'antd'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useAppSettingsStore } from '@/store/appSettings'

export default function ManagerAppearanceSettings() {
  const { t } = useTranslation()

  const managerUiBlurEnabled = useAppSettingsStore((state) => state.managerUiBlurEnabled)
  const managerUiBlurRadiusPx = useAppSettingsStore((state) => state.managerUiBlurRadiusPx)
  const managerUiSurfaceBgOpacity = useAppSettingsStore((state) => state.managerUiSurfaceBgOpacity)
  const managerUiSurfaceBorderOpacity = useAppSettingsStore((state) => state.managerUiSurfaceBorderOpacity)
  const managerUiControlBgOpacity = useAppSettingsStore((state) => state.managerUiControlBgOpacity)
  const managerUiControlBorderOpacity = useAppSettingsStore((state) => state.managerUiControlBorderOpacity)

  const setManagerUiBlurEnabled = useAppSettingsStore((state) => state.setManagerUiBlurEnabled)
  const setManagerUiBlurRadiusPx = useAppSettingsStore((state) => state.setManagerUiBlurRadiusPx)
  const setManagerUiSurfaceBgOpacity = useAppSettingsStore((state) => state.setManagerUiSurfaceBgOpacity)
  const setManagerUiSurfaceBorderOpacity = useAppSettingsStore((state) => state.setManagerUiSurfaceBorderOpacity)
  const setManagerUiControlBgOpacity = useAppSettingsStore((state) => state.setManagerUiControlBgOpacity)
  const setManagerUiControlBorderOpacity = useAppSettingsStore((state) => state.setManagerUiControlBorderOpacity)

  const [saving, setSaving] = useState(false)
  const [formBlurEnabled, setFormBlurEnabled] = useState(managerUiBlurEnabled)
  const [formBlurRadiusPx, setFormBlurRadiusPx] = useState(managerUiBlurRadiusPx)
  const [formSurfaceBgOpacity, setFormSurfaceBgOpacity] = useState(managerUiSurfaceBgOpacity)
  const [formSurfaceBorderOpacity, setFormSurfaceBorderOpacity] = useState(managerUiSurfaceBorderOpacity)
  const [formControlBgOpacity, setFormControlBgOpacity] = useState(managerUiControlBgOpacity)
  const [formControlBorderOpacity, setFormControlBorderOpacity] = useState(managerUiControlBorderOpacity)

  useEffect(() => setFormBlurEnabled(managerUiBlurEnabled), [managerUiBlurEnabled])
  useEffect(() => setFormBlurRadiusPx(managerUiBlurRadiusPx), [managerUiBlurRadiusPx])
  useEffect(() => setFormSurfaceBgOpacity(managerUiSurfaceBgOpacity), [managerUiSurfaceBgOpacity])
  useEffect(() => setFormSurfaceBorderOpacity(managerUiSurfaceBorderOpacity), [managerUiSurfaceBorderOpacity])
  useEffect(() => setFormControlBgOpacity(managerUiControlBgOpacity), [managerUiControlBgOpacity])
  useEffect(() => setFormControlBorderOpacity(managerUiControlBorderOpacity), [managerUiControlBorderOpacity])

  const save = async () => {
    setSaving(true)
    try {
      await Promise.all([
        setManagerUiBlurEnabled(formBlurEnabled),
        setManagerUiBlurRadiusPx(formBlurRadiusPx),
        setManagerUiSurfaceBgOpacity(formSurfaceBgOpacity),
        setManagerUiSurfaceBorderOpacity(formSurfaceBorderOpacity),
        setManagerUiControlBgOpacity(formControlBgOpacity),
        setManagerUiControlBorderOpacity(formControlBorderOpacity)
      ])
      message.success(t('settingsSavedSuccessfully'))
    } catch (error) {
      console.error('保存管理器外观设置失败：', error)
      message.error(t('errorSavingSettings'))
    } finally {
      setSaving(false)
    }
  }

  const resetToDefault = async () => {
    setSaving(true)
    try {
      await Promise.all([
        setManagerUiBlurEnabled(true),
        setManagerUiBlurRadiusPx(10),
        setManagerUiSurfaceBgOpacity(0.72),
        setManagerUiSurfaceBorderOpacity(0.14),
        setManagerUiControlBgOpacity(0.6),
        setManagerUiControlBorderOpacity(0.14)
      ])
      message.success(t('settingsSavedSuccessfully'))
    } catch (error) {
      console.error('重置管理器外观设置失败：', error)
      message.error(t('errorSavingSettings'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <Space direction="vertical" size="large" className="w-full">
      <Form layout="vertical">
        <Form.Item label={t('managerUiBlurEnabled')}>
          <Switch checked={formBlurEnabled} onChange={setFormBlurEnabled} />
          <div className="mt-1 text-xs text-gray-500">{t('managerUiBlurEnabledHelp')}</div>
        </Form.Item>

        <Form.Item label={t('managerUiBlurRadiusPx')}>
          <InputNumber
            value={formBlurRadiusPx}
            min={0}
            max={30}
            step={1}
            style={{ maxWidth: 240 }}
            onChange={(value) => setFormBlurRadiusPx(Number(value ?? 0))}
          />
          <div className="mt-1 text-xs text-gray-500">{t('managerUiBlurRadiusPxHelp')}</div>
        </Form.Item>

        <Divider />

        <Form.Item label={t('managerUiSurfaceBgOpacity')}>
          <InputNumber
            value={formSurfaceBgOpacity}
            min={0.35}
            max={0.95}
            step={0.02}
            style={{ maxWidth: 240 }}
            onChange={(value) => setFormSurfaceBgOpacity(Number(value ?? 0))}
          />
          <div className="mt-1 text-xs text-gray-500">{t('managerUiSurfaceBgOpacityHelp')}</div>
        </Form.Item>

        <Form.Item label={t('managerUiSurfaceBorderOpacity')}>
          <InputNumber
            value={formSurfaceBorderOpacity}
            min={0.06}
            max={0.45}
            step={0.02}
            style={{ maxWidth: 240 }}
            onChange={(value) => setFormSurfaceBorderOpacity(Number(value ?? 0))}
          />
          <div className="mt-1 text-xs text-gray-500">{t('managerUiSurfaceBorderOpacityHelp')}</div>
        </Form.Item>

        <Divider />

        <Form.Item label={t('managerUiControlBgOpacity')}>
          <InputNumber
            value={formControlBgOpacity}
            min={0.18}
            max={0.9}
            step={0.02}
            style={{ maxWidth: 240 }}
            onChange={(value) => setFormControlBgOpacity(Number(value ?? 0))}
          />
          <div className="mt-1 text-xs text-gray-500">{t('managerUiControlBgOpacityHelp')}</div>
        </Form.Item>

        <Form.Item label={t('managerUiControlBorderOpacity')}>
          <InputNumber
            value={formControlBorderOpacity}
            min={0.06}
            max={0.6}
            step={0.02}
            style={{ maxWidth: 240 }}
            onChange={(value) => setFormControlBorderOpacity(Number(value ?? 0))}
          />
          <div className="mt-1 text-xs text-gray-500">{t('managerUiControlBorderOpacityHelp')}</div>
        </Form.Item>

        <Space>
          <Button type="primary" loading={saving} onClick={() => save().catch(() => {})}>
            {t('save')}
          </Button>
          <Button disabled={saving} onClick={() => resetToDefault().catch(() => {})}>
            {t('resetToDefault')}
          </Button>
        </Space>
      </Form>
    </Space>
  )
}

// frontend/src/components/glass/settings/ManagerAppearanceSettings.vue
<template>
  <a-space direction="vertical" size="large" class="w-full">
    <a-form layout="vertical" @submit.prevent>
      <a-form-item :label="$t('managerUiBlurEnabled')">
        <a-switch v-model:checked="formBlurEnabled" />
        <div class="mt-1 text-xs text-gray-500">
          {{ $t('managerUiBlurEnabledHelp') }}
        </div>
      </a-form-item>

      <a-form-item :label="$t('managerUiBlurRadiusPx')">
        <a-input-number
          v-model:value="formBlurRadiusPx"
          :min="0"
          :max="30"
          :step="1"
          style="max-width: 240px"
        />
        <div class="mt-1 text-xs text-gray-500">
          {{ $t('managerUiBlurRadiusPxHelp') }}
        </div>
      </a-form-item>

      <a-divider />

      <a-form-item :label="$t('managerUiSurfaceBgOpacity')">
        <a-input-number
          v-model:value="formSurfaceBgOpacity"
          :min="0.35"
          :max="0.95"
          :step="0.02"
          style="max-width: 240px"
        />
        <div class="mt-1 text-xs text-gray-500">
          {{ $t('managerUiSurfaceBgOpacityHelp') }}
        </div>
      </a-form-item>

      <a-form-item :label="$t('managerUiSurfaceBorderOpacity')">
        <a-input-number
          v-model:value="formSurfaceBorderOpacity"
          :min="0.06"
          :max="0.45"
          :step="0.02"
          style="max-width: 240px"
        />
        <div class="mt-1 text-xs text-gray-500">
          {{ $t('managerUiSurfaceBorderOpacityHelp') }}
        </div>
      </a-form-item>

      <a-divider />

      <a-form-item :label="$t('managerUiControlBgOpacity')">
        <a-input-number
          v-model:value="formControlBgOpacity"
          :min="0.18"
          :max="0.9"
          :step="0.02"
          style="max-width: 240px"
        />
        <div class="mt-1 text-xs text-gray-500">
          {{ $t('managerUiControlBgOpacityHelp') }}
        </div>
      </a-form-item>

      <a-form-item :label="$t('managerUiControlBorderOpacity')">
        <a-input-number
          v-model:value="formControlBorderOpacity"
          :min="0.06"
          :max="0.6"
          :step="0.02"
          style="max-width: 240px"
        />
        <div class="mt-1 text-xs text-gray-500">
          {{ $t('managerUiControlBorderOpacityHelp') }}
        </div>
      </a-form-item>

      <a-space>
        <a-button type="primary" :loading="saving" @click="save">
          {{ $t('save') }}
        </a-button>
        <a-button :disabled="saving" @click="resetToDefault">
          {{ $t('resetToDefault') }}
        </a-button>
      </a-space>
    </a-form>
  </a-space>
</template>

<script setup>
import { ref, watch } from 'vue'
import { message } from 'ant-design-vue'
import { useI18n } from 'vue-i18n'
import { useAppSettingsStore } from '@/store/appSettings'

const { t } = useI18n()
const appSettingsStore = useAppSettingsStore()

const saving = ref(false)
const formBlurEnabled = ref(appSettingsStore.managerUiBlurEnabled)
const formBlurRadiusPx = ref(appSettingsStore.managerUiBlurRadiusPx)
const formSurfaceBgOpacity = ref(appSettingsStore.managerUiSurfaceBgOpacity)
const formSurfaceBorderOpacity = ref(appSettingsStore.managerUiSurfaceBorderOpacity)
const formControlBgOpacity = ref(appSettingsStore.managerUiControlBgOpacity)
const formControlBorderOpacity = ref(appSettingsStore.managerUiControlBorderOpacity)

watch(
  () => appSettingsStore.managerUiBlurEnabled,
  value => {
    formBlurEnabled.value = value
  }
)
watch(
  () => appSettingsStore.managerUiBlurRadiusPx,
  value => {
    formBlurRadiusPx.value = value
  }
)
watch(
  () => appSettingsStore.managerUiSurfaceBgOpacity,
  value => {
    formSurfaceBgOpacity.value = value
  }
)
watch(
  () => appSettingsStore.managerUiSurfaceBorderOpacity,
  value => {
    formSurfaceBorderOpacity.value = value
  }
)
watch(
  () => appSettingsStore.managerUiControlBgOpacity,
  value => {
    formControlBgOpacity.value = value
  }
)
watch(
  () => appSettingsStore.managerUiControlBorderOpacity,
  value => {
    formControlBorderOpacity.value = value
  }
)

const save = async () => {
  saving.value = true
  try {
    await Promise.all([
      appSettingsStore.setManagerUiBlurEnabled(formBlurEnabled.value),
      appSettingsStore.setManagerUiBlurRadiusPx(formBlurRadiusPx.value),
      appSettingsStore.setManagerUiSurfaceBgOpacity(formSurfaceBgOpacity.value),
      appSettingsStore.setManagerUiSurfaceBorderOpacity(formSurfaceBorderOpacity.value),
      appSettingsStore.setManagerUiControlBgOpacity(formControlBgOpacity.value),
      appSettingsStore.setManagerUiControlBorderOpacity(formControlBorderOpacity.value),
    ])
    message.success(t('settingsSavedSuccessfully'))
  } catch (error) {
    console.error('保存管理器外观设置失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}

const resetToDefault = async () => {
  saving.value = true
  try {
    await Promise.all([
      appSettingsStore.setManagerUiBlurEnabled(true),
      appSettingsStore.setManagerUiBlurRadiusPx(10),
      appSettingsStore.setManagerUiSurfaceBgOpacity(0.72),
      appSettingsStore.setManagerUiSurfaceBorderOpacity(0.14),
      appSettingsStore.setManagerUiControlBgOpacity(0.6),
      appSettingsStore.setManagerUiControlBorderOpacity(0.14),
    ])
    message.success(t('settingsSavedSuccessfully'))
  } catch (error) {
    console.error('重置管理器外观设置失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}
</script>
