// apps/web/src/pages/MaintenanceView.tsx
import { Button, Checkbox, Empty, List, Modal, Space, Spin, Typography, message } from 'antd'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { http } from '@/api/http'
import GlassPage from '@/components/glass/ui/GlassPage'
import GlassSurface from '@/components/glass/ui/GlassSurface'
import BackupManager from '@/components/maintenance/BackupManager'
import { useLibraryStore } from '@/store/library'

type FileItem = {
  id: number
  file_path?: string | null
}

export default function MaintenanceView() {
  const { t } = useTranslation()
  const checkActiveTasks = useLibraryStore((state) => state.checkActiveTasks)

  const [duplicates, setDuplicates] = useState<FileItem[][]>([])
  const [loadingDuplicates, setLoadingDuplicates] = useState(false)

  const [missingFiles, setMissingFiles] = useState<FileItem[]>([])
  const [loadingMissing, setLoadingMissing] = useState(false)
  const [selectedMissingFiles, setSelectedMissingFiles] = useState<Set<number>>(() => new Set())

  const selectedMissingCount = useMemo(() => selectedMissingFiles.size, [selectedMissingFiles])

  const findDuplicates = useCallback(async () => {
    setLoadingDuplicates(true)
    setDuplicates([])
    try {
      const response = await http.get('/api/v1/reports/duplicate-files')
      setDuplicates((response?.data || []) as FileItem[][])
    } catch (error) {
      console.error('查找重复文件失败：', error)
      message.error(t('errorLoadingData', { error: t('duplicateFinder') }))
    } finally {
      setLoadingDuplicates(false)
      checkActiveTasks().catch(() => {})
    }
  }, [checkActiveTasks, t])

  const findMissingFiles = useCallback(async () => {
    setLoadingMissing(true)
    setMissingFiles([])
    try {
      const response = await http.get('/api/v1/files', {
        params: { is_missing: true, per_page: 9999 }
      })
      setMissingFiles((response?.data?.files || []) as FileItem[])
    } catch (error) {
      console.error('查找缺失文件失败：', error)
      message.error(t('errorLoadingData', { error: t('missingFileCleanup') }))
    } finally {
      setLoadingMissing(false)
    }
  }, [t])

  const cleanupSelectedMissingFiles = () => {
    if (selectedMissingFiles.size === 0) {
      message.warning(t('pleaseSelectFileToRename'))
      return
    }

    Modal.confirm({
      title: t('deleteSelectedRecords'),
      content: `${t('deleteSelectedRecords')} (${selectedMissingFiles.size})`,
      okType: 'danger',
      okText: t('delete'),
      cancelText: t('cancel'),
      onOk: async () => {
        try {
          const ids = Array.from(selectedMissingFiles)
          const response = await http.post('/api/v1/missing-file-cleanups', { file_ids: ids })
          message.success(response?.data?.message || t('successfullySaved'))
          setSelectedMissingFiles(new Set())
          await findMissingFiles()
        } catch (error) {
          console.error('清理缺失文件记录失败：', error)
          message.error((error as any)?.response?.data?.error || t('error'))
        } finally {
          checkActiveTasks().catch(() => {})
        }
      }
    })
  }

  useEffect(() => {
    findMissingFiles().catch(() => {})
  }, [findMissingFiles])

  return (
    <GlassPage>
      <Space direction="vertical" size="large" className="w-full">
        <BackupManager />

        <GlassSurface title={t('duplicateFinder')}>
          <Button type="primary" loading={loadingDuplicates} onClick={() => findDuplicates().catch(() => {})}>
            {loadingDuplicates ? t('scanning') : t('findDuplicates')}
          </Button>

          {loadingDuplicates ? (
            <div className="mt-4 flex justify-center">
              <Spin />
            </div>
          ) : duplicates.length ? (
            <List
              className="mt-4"
              bordered
              dataSource={duplicates}
              renderItem={(group, index) => (
                <List.Item key={`dup-${index}`}>
                  <div className="w-full">
                    <Typography.Title level={5} className="mb-3">
                      {t('duplicateFinder')} #{index + 1}
                    </Typography.Title>
                    <List
                      size="small"
                      dataSource={group}
                      renderItem={(file) => (
                        <List.Item key={`dup-file-${file.id}`}>
                          <Typography.Text code className="truncate block">
                            {file.file_path || `#${file.id}`}
                          </Typography.Text>
                        </List.Item>
                      )}
                    />
                  </div>
                </List.Item>
              )}
            />
          ) : (
            <Empty className="mt-4" description={t('noDuplicatesFound')} />
          )}
        </GlassSurface>

        <GlassSurface title={t('missingFileCleanup')}>
          <Space wrap className="mb-4">
            <Button type="primary" loading={loadingMissing} onClick={() => findMissingFiles().catch(() => {})}>
              {loadingMissing ? t('scanning') : t('findMissingFiles')}
            </Button>
            {missingFiles.length ? (
              <Button danger onClick={cleanupSelectedMissingFiles}>
                {t('deleteSelectedRecords')}
                {selectedMissingCount ? ` (${selectedMissingCount})` : ''}
              </Button>
            ) : null}
          </Space>

          {loadingMissing ? (
            <div className="flex justify-center py-8">
              <Spin />
            </div>
          ) : missingFiles.length ? (
            <List
              bordered
              dataSource={missingFiles}
              renderItem={(item) => {
                const checked = selectedMissingFiles.has(item.id)
                return (
                  <List.Item key={`missing-${item.id}`}>
                    <Checkbox
                      checked={checked}
                      onChange={(event) => {
                        setSelectedMissingFiles((prev) => {
                          const next = new Set(prev)
                          if (event.target.checked) {
                            next.add(item.id)
                          } else {
                            next.delete(item.id)
                          }
                          return next
                        })
                      }}
                    >
                      <span className="text-sm">{item.file_path || `#${item.id}`}</span>
                    </Checkbox>
                  </List.Item>
                )
              }}
            />
          ) : (
            <Empty description={t('noMissingFilesFound')} />
          )}
        </GlassSurface>
      </Space>
    </GlassPage>
  )
}

// apps/web/_legacy/vue/src/pages/MaintenanceView.vue
<script setup>
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import axios from 'axios'
import { Modal, message } from 'ant-design-vue'
import BackupManager from '../components/BackupManager.vue'
import GlassPage from '@/components/glass/ui/GlassPage.vue'
import GlassSurface from '@/components/glass/ui/GlassSurface.vue'
import { useLibraryStore } from '@/store/library'

const duplicates = ref([])
const isLoadingDuplicates = ref(false)

const missingFiles = ref([])
const isLoadingMissing = ref(false)
const selectedMissingFiles = ref(new Set())

const { t } = useI18n()
const libraryStore = useLibraryStore()

const findDuplicates = async () => {
  isLoadingDuplicates.value = true
  duplicates.value = []
  try {
    const response = await axios.get('/api/v1/reports/duplicate-files')
    duplicates.value = response.data
  } catch (error) {
    console.error('Failed to find duplicates:', error)
    message.error(t('errorLoadingData', { error: t('duplicateFinder') }))
  } finally {
    isLoadingDuplicates.value = false
    libraryStore.checkActiveTasks()
  }
}

const findMissingFiles = async () => {
  isLoadingMissing.value = true
  missingFiles.value = []
  try {
    const response = await axios.get('/api/v1/files', {
      params: { is_missing: true, per_page: 9999 }
    })
    missingFiles.value = response.data.files
  } catch (error) {
    console.error('Failed to find missing files:', error)
    message.error(t('errorLoadingData', { error: t('missingFileCleanup') }))
  } finally {
    isLoadingMissing.value = false
  }
}

const cleanupSelectedMissingFiles = () => {
  if (selectedMissingFiles.value.size === 0) {
    message.warning(t('pleaseSelectFileToRename'))
    return
  }

  Modal.confirm({
    title: t('deleteSelectedRecords'),
    content: `${t('deleteSelectedRecords')} (${selectedMissingFiles.value.size})`,
    okType: 'danger',
    async onOk() {
      try {
        const ids = Array.from(selectedMissingFiles.value)
        const response = await axios.post('/api/v1/missing-file-cleanups', { file_ids: ids })
        message.success(response.data.message)
        selectedMissingFiles.value.clear()
        findMissingFiles()
      } catch (error) {
        console.error('Failed to cleanup missing files:', error)
        message.error(t('error'))
      } finally {
        libraryStore.checkActiveTasks()
      }
    }
  })
}
</script>

<template>
  <GlassPage>
    <a-space direction="vertical" size="large" class="w-full">
      <BackupManager />

      <GlassSurface :title="$t('duplicateFinder')">
      <a-button type="primary" :loading="isLoadingDuplicates" @click="findDuplicates">
        {{ isLoadingDuplicates ? $t('scanning') : $t('findDuplicates') }}
      </a-button>
      <a-list
        v-if="duplicates.length"
        class="mt-4"
        :data-source="duplicates"
        bordered
      >
        <template #renderItem="{ item, index }">
          <a-list-item :key="index">
            <a-card type="inner" :title="`${$t('duplicateFinder')} #${index + 1}`">
              <a-list :data-source="item" :renderItem="file => null" size="small">
                <template #renderItem="{ item: file }">
                  <a-list-item>
                    <a-typography-text code class="truncate block">
                      {{ file.file_path }}
                    </a-typography-text>
                  </a-list-item>
                </template>
              </a-list>
            </a-card>
          </a-list-item>
        </template>
      </a-list>
      <a-empty v-else-if="!isLoadingDuplicates" class="mt-4" :description="$t('noDuplicatesFound')" />
      </GlassSurface>

      <GlassSurface :title="$t('missingFileCleanup')">
      <a-space wrap class="mb-4">
        <a-button type="primary" :loading="isLoadingMissing" @click="findMissingFiles">
          {{ isLoadingMissing ? $t('scanning') : $t('findMissingFiles') }}
        </a-button>
        <a-button
          v-if="missingFiles.length"
          danger
          @click="cleanupSelectedMissingFiles"
        >
          {{ $t('deleteSelectedRecords') }}
        </a-button>
      </a-space>

      <a-list
        v-if="missingFiles.length"
        bordered
        :data-source="missingFiles"
        :locale="{ emptyText: null }"
      >
        <template #renderItem="{ item }">
          <a-list-item>
            <a-checkbox
              :checked="selectedMissingFiles.has(item.id)"
              @change="event => {
                if (event.target.checked) {
                  selectedMissingFiles.add(item.id)
                } else {
                  selectedMissingFiles.delete(item.id)
                }
              }"
            >
              <span class="text-sm">{{ item.file_path }}</span>
            </a-checkbox>
          </a-list-item>
        </template>
      </a-list>

      <a-empty v-else-if="!isLoadingMissing" :description="$t('noMissingFilesFound')" />
      </GlassSurface>
    </a-space>
  </GlassPage>
</template>
