// apps/web/_legacy/vue/src/components/reader/settings/ReaderUiAppearanceSettings.vue
<template>
  <a-form layout="vertical" @submit.prevent>
    <a-form-item :label="$t('readerUiBlurEnabled')">
      <a-switch v-model:checked="formReaderUiBlurEnabled" />
      <div class="mt-1 text-xs text-gray-500">
        {{ $t('readerUiBlurEnabledHelp') }}
      </div>
    </a-form-item>

    <a-form-item :label="$t('readerUiBlurRadiusPx')">
      <a-input-number
        v-model:value="formReaderUiBlurRadiusPx"
        :min="0"
        :max="30"
        :step="1"
        style="max-width: 240px"
      />
      <div class="mt-1 text-xs text-gray-500">
        {{ $t('readerUiBlurRadiusPxHelp') }}
      </div>
    </a-form-item>

    <a-form-item :label="$t('readerUiControlBgOpacity')">
      <a-input-number
        v-model:value="formReaderUiControlBgOpacity"
        :min="0.12"
        :max="0.7"
        :step="0.02"
        style="max-width: 240px"
      />
      <div class="mt-1 text-xs text-gray-500">
        {{ $t('readerUiControlBgOpacityHelp') }}
      </div>
    </a-form-item>

    <a-form-item :label="$t('readerUiControlBorderOpacity')">
      <a-input-number
        v-model:value="formReaderUiControlBorderOpacity"
        :min="0.06"
        :max="0.4"
        :step="0.02"
        style="max-width: 240px"
      />
      <div class="mt-1 text-xs text-gray-500">
        {{ $t('readerUiControlBorderOpacityHelp') }}
      </div>
    </a-form-item>

    <a-space>
      <a-button type="primary" :loading="saving" @click="save">
        {{ $t('save') }}
      </a-button>
      <a-button :disabled="saving" @click="resetToDefault">
        {{ $t('resetToDefault') }}
      </a-button>
    </a-space>
  </a-form>
</template>

<script setup>
import { ref, watch } from 'vue'
import { message } from 'ant-design-vue'
import { useI18n } from 'vue-i18n'
import { useAppSettingsStore } from '@/store/appSettings'

const { t } = useI18n()
const appSettingsStore = useAppSettingsStore()

const saving = ref(false)
const formReaderUiBlurEnabled = ref(appSettingsStore.readerUiBlurEnabled)
const formReaderUiBlurRadiusPx = ref(appSettingsStore.readerUiBlurRadiusPx)
const formReaderUiControlBgOpacity = ref(appSettingsStore.readerUiControlBgOpacity)
const formReaderUiControlBorderOpacity = ref(appSettingsStore.readerUiControlBorderOpacity)

watch(
  () => appSettingsStore.readerUiBlurEnabled,
  value => {
    formReaderUiBlurEnabled.value = value
  }
)
watch(
  () => appSettingsStore.readerUiBlurRadiusPx,
  value => {
    formReaderUiBlurRadiusPx.value = value
  }
)
watch(
  () => appSettingsStore.readerUiControlBgOpacity,
  value => {
    formReaderUiControlBgOpacity.value = value
  }
)
watch(
  () => appSettingsStore.readerUiControlBorderOpacity,
  value => {
    formReaderUiControlBorderOpacity.value = value
  }
)

const save = async () => {
  saving.value = true
  try {
    await Promise.all([
      appSettingsStore.setReaderUiBlurEnabled(formReaderUiBlurEnabled.value),
      appSettingsStore.setReaderUiBlurRadiusPx(formReaderUiBlurRadiusPx.value),
      appSettingsStore.setReaderUiControlBgOpacity(formReaderUiControlBgOpacity.value),
      appSettingsStore.setReaderUiControlBorderOpacity(formReaderUiControlBorderOpacity.value)
    ])
    message.success(t('settingsSavedSuccessfully'))
  } catch (error) {
    console.error('保存阅读器外观设置失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}

const resetToDefault = async () => {
  saving.value = true
  try {
    await Promise.all([
      appSettingsStore.setReaderUiBlurEnabled(true),
      appSettingsStore.setReaderUiBlurRadiusPx(12),
      appSettingsStore.setReaderUiControlBgOpacity(0.46),
      appSettingsStore.setReaderUiControlBorderOpacity(0.16)
    ])
    message.success(t('settingsSavedSuccessfully'))
  } catch (error) {
    console.error('重置阅读器外观设置失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}
</script>

// apps/web/src/components/reader/settings/ReaderUiAppearanceSettings.tsx
import { Button, Form, InputNumber, Space, Switch, message } from 'antd'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useAppSettingsStore } from '@/store/appSettings'

export default function ReaderUiAppearanceSettings() {
  const { t } = useTranslation()

  const readerUiBlurEnabled = useAppSettingsStore((state) => state.readerUiBlurEnabled)
  const readerUiBlurRadiusPx = useAppSettingsStore((state) => state.readerUiBlurRadiusPx)
  const readerUiControlBgOpacity = useAppSettingsStore((state) => state.readerUiControlBgOpacity)
  const readerUiControlBorderOpacity = useAppSettingsStore((state) => state.readerUiControlBorderOpacity)

  const setReaderUiBlurEnabled = useAppSettingsStore((state) => state.setReaderUiBlurEnabled)
  const setReaderUiBlurRadiusPx = useAppSettingsStore((state) => state.setReaderUiBlurRadiusPx)
  const setReaderUiControlBgOpacity = useAppSettingsStore((state) => state.setReaderUiControlBgOpacity)
  const setReaderUiControlBorderOpacity = useAppSettingsStore((state) => state.setReaderUiControlBorderOpacity)

  const [saving, setSaving] = useState(false)
  const [formBlurEnabled, setFormBlurEnabled] = useState(readerUiBlurEnabled)
  const [formBlurRadiusPx, setFormBlurRadiusPx] = useState(readerUiBlurRadiusPx)
  const [formControlBgOpacity, setFormControlBgOpacity] = useState(readerUiControlBgOpacity)
  const [formControlBorderOpacity, setFormControlBorderOpacity] = useState(readerUiControlBorderOpacity)

  useEffect(() => setFormBlurEnabled(readerUiBlurEnabled), [readerUiBlurEnabled])
  useEffect(() => setFormBlurRadiusPx(readerUiBlurRadiusPx), [readerUiBlurRadiusPx])
  useEffect(() => setFormControlBgOpacity(readerUiControlBgOpacity), [readerUiControlBgOpacity])
  useEffect(() => setFormControlBorderOpacity(readerUiControlBorderOpacity), [readerUiControlBorderOpacity])

  const save = async () => {
    setSaving(true)
    try {
      await Promise.all([
        setReaderUiBlurEnabled(formBlurEnabled),
        setReaderUiBlurRadiusPx(formBlurRadiusPx),
        setReaderUiControlBgOpacity(formControlBgOpacity),
        setReaderUiControlBorderOpacity(formControlBorderOpacity)
      ])
      message.success(t('settingsSavedSuccessfully'))
    } catch (error) {
      console.error('保存阅读器外观设置失败：', error)
      message.error(t('failedToSaveSettings'))
    } finally {
      setSaving(false)
    }
  }

  const resetToDefault = async () => {
    setSaving(true)
    try {
      await Promise.all([
        setReaderUiBlurEnabled(true),
        setReaderUiBlurRadiusPx(12),
        setReaderUiControlBgOpacity(0.46),
        setReaderUiControlBorderOpacity(0.16)
      ])
      message.success(t('settingsSavedSuccessfully'))
    } catch (error) {
      console.error('重置阅读器外观设置失败：', error)
      message.error(t('failedToSaveSettings'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <Form layout="vertical">
      <Form.Item label={t('readerUiBlurEnabled')}>
        <Switch checked={formBlurEnabled} onChange={setFormBlurEnabled} />
        <div className="mt-1 text-xs text-gray-500">{t('readerUiBlurEnabledHelp')}</div>
      </Form.Item>

      <Form.Item label={t('readerUiBlurRadiusPx')}>
        <InputNumber
          value={formBlurRadiusPx}
          min={0}
          max={30}
          step={1}
          style={{ maxWidth: 240 }}
          onChange={(value) => setFormBlurRadiusPx(Number(value ?? 12))}
        />
        <div className="mt-1 text-xs text-gray-500">{t('readerUiBlurRadiusPxHelp')}</div>
      </Form.Item>

      <Form.Item label={t('readerUiControlBgOpacity')}>
        <InputNumber
          value={formControlBgOpacity}
          min={0.12}
          max={0.7}
          step={0.02}
          style={{ maxWidth: 240 }}
          onChange={(value) => setFormControlBgOpacity(Number(value ?? 0.46))}
        />
        <div className="mt-1 text-xs text-gray-500">{t('readerUiControlBgOpacityHelp')}</div>
      </Form.Item>

      <Form.Item label={t('readerUiControlBorderOpacity')}>
        <InputNumber
          value={formControlBorderOpacity}
          min={0.06}
          max={0.4}
          step={0.02}
          style={{ maxWidth: 240 }}
          onChange={(value) => setFormControlBorderOpacity(Number(value ?? 0.16))}
        />
        <div className="mt-1 text-xs text-gray-500">{t('readerUiControlBorderOpacityHelp')}</div>
      </Form.Item>

      <Space>
        <Button type="primary" loading={saving} onClick={() => save().catch(() => {})}>
          {t('save')}
        </Button>
        <Button disabled={saving} onClick={() => resetToDefault().catch(() => {})}>
          {t('resetToDefault')}
        </Button>
      </Space>
    </Form>
  )
}
