// apps/web/_legacy/vue/src/components/ReaderTapZonesSettings.vue
<template>
  <a-space direction="vertical" size="large" class="w-full">
    <a-typography-paragraph type="secondary" class="!mb-0">
      {{ $t('readerTapZonesSettingsHelp') }}
    </a-typography-paragraph>

    <div class="reader-tap-zones-settings__preview">
      <ReaderTapZonesPreview
        v-model="draft"
        v-model:selectedZone="selectedZone"
        :overlay="false"
        :show-labels="true"
      />
    </div>

    <a-form layout="vertical" @submit.prevent>
      <a-form-item :label="zoneLabel(selectedZone)">
        <a-select
          v-model:value="selectedZoneAction"
          :options="actionOptions"
          style="max-width: 360px"
        />
      </a-form-item>

      <a-form-item :label="$t('readerTapZonesLeftWidth')">
        <a-slider v-model:value="leftWidthPercent" :min="8" :max="84" :step="1" :tooltip-open="false" />
        <div class="mt-1 text-xs text-gray-500">{{ leftWidthText }}</div>
      </a-form-item>

      <a-form-item :label="$t('readerTapZonesRightWidth')">
        <a-slider v-model:value="rightWidthPercent" :min="8" :max="84" :step="1" :tooltip-open="false" />
        <div class="mt-1 text-xs text-gray-500">{{ rightWidthText }}</div>
      </a-form-item>

      <a-form-item :label="$t('readerTapZonesCurrentSizes')">
        <a-space>
          <a-tag>{{ $t('readerTapZoneLeft') }}：{{ leftWidthText }}</a-tag>
          <a-tag>{{ $t('readerTapZoneMiddle') }}：{{ middleWidthText }}</a-tag>
          <a-tag>{{ $t('readerTapZoneRight') }}：{{ rightWidthText }}</a-tag>
        </a-space>
      </a-form-item>

      <a-space>
        <a-button type="primary" :loading="saving" @click="save">
          {{ $t('save') }}
        </a-button>
        <a-button :disabled="saving" @click="resetToDefault">
          {{ $t('resetToDefault') }}
        </a-button>
      </a-space>
    </a-form>
  </a-space>
</template>

<script setup>
import { computed, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { message } from 'ant-design-vue'
import { useI18n } from 'vue-i18n'
import { useAppSettingsStore, DEFAULT_READER_TAP_ZONES } from '@/store/appSettings'
import ReaderTapZonesPreview from '@/components/reader/tapZones/ReaderTapZonesPreview.vue'

const { t } = useI18n()
const appSettingsStore = useAppSettingsStore()
const { readerTapZones } = storeToRefs(appSettingsStore)

const saving = ref(false)
const selectedZone = ref('middle')

const draft = ref(JSON.parse(JSON.stringify(readerTapZones.value || DEFAULT_READER_TAP_ZONES)))

watch(
  readerTapZones,
  value => {
    if (!saving.value) {
      draft.value = JSON.parse(JSON.stringify(value || DEFAULT_READER_TAP_ZONES))
    }
  },
  { deep: true }
)

const actionOptions = computed(() => [
  { value: 'prev_page', label: t('readerTapActionPrevPage') },
  { value: 'next_page', label: t('readerTapActionNextPage') },
  { value: 'toggle_toolbar', label: t('readerTapActionToggleToolbar') },
  { value: 'expand_toolbar', label: t('readerTapActionExpandToolbar') },
  { value: 'collapse_toolbar', label: t('readerTapActionCollapseToolbar') },
  { value: 'none', label: t('readerTapActionNone') }
])

const zoneLabel = zoneKey => {
  if (zoneKey === 'left') return t('readerTapZoneLeft')
  if (zoneKey === 'right') return t('readerTapZoneRight')
  return t('readerTapZoneMiddle')
}

const selectedZoneAction = computed({
  get: () => draft.value?.actions?.[selectedZone.value] ?? 'none',
  set: value => {
    draft.value = {
      ...(draft.value || DEFAULT_READER_TAP_ZONES),
      actions: { ...(draft.value?.actions || DEFAULT_READER_TAP_ZONES.actions), [selectedZone.value]: value }
    }
  }
})

const leftRatio = computed(() => Number(draft.value?.boundaries?.left ?? DEFAULT_READER_TAP_ZONES.boundaries.left))
const rightRatio = computed(() => Number(draft.value?.boundaries?.right ?? DEFAULT_READER_TAP_ZONES.boundaries.right))

const widths = computed(() => {
  const left = Math.round(leftRatio.value * 100)
  const middle = Math.round((rightRatio.value - leftRatio.value) * 100)
  const right = Math.round((1 - rightRatio.value) * 100)
  return { left, middle, right }
})

const leftWidthText = computed(() => `${widths.value.left}%`)
const middleWidthText = computed(() => `${widths.value.middle}%`)
const rightWidthText = computed(() => `${widths.value.right}%`)

const clamp = (value, min, max) => Math.min(max, Math.max(min, value))

const setBoundaries = (left, right) => {
  const minZoneWidth = 0.08
  const normalizedLeft = clamp(left, minZoneWidth, 1 - minZoneWidth)
  const normalizedRight = clamp(right, minZoneWidth, 1 - minZoneWidth)
  if (normalizedLeft >= normalizedRight) {
    return
  }
  if (
    normalizedLeft < minZoneWidth ||
    1 - normalizedRight < minZoneWidth ||
    normalizedRight - normalizedLeft < minZoneWidth
  ) {
    return
  }

  draft.value = {
    ...(draft.value || DEFAULT_READER_TAP_ZONES),
    version: 1,
    boundaries: { left: normalizedLeft, right: normalizedRight },
    actions: { ...(draft.value?.actions || DEFAULT_READER_TAP_ZONES.actions) }
  }
}

const leftWidthPercent = computed({
  get: () => widths.value.left,
  set: percent => {
    setBoundaries(clamp(Number(percent) / 100, 0.08, 0.92), rightRatio.value)
  }
})

const rightWidthPercent = computed({
  get: () => widths.value.right,
  set: percent => {
    setBoundaries(leftRatio.value, 1 - clamp(Number(percent) / 100, 0.08, 0.92))
  }
})

const save = async () => {
  saving.value = true
  try {
    await appSettingsStore.setReaderTapZones(draft.value)
    message.success(t('settingsSavedSuccessfully'))
  } catch (error) {
    console.error('保存阅读器点击区域设置失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}

const resetToDefault = async () => {
  saving.value = true
  try {
    const next = {
      version: 1,
      boundaries: { ...DEFAULT_READER_TAP_ZONES.boundaries },
      actions: { ...DEFAULT_READER_TAP_ZONES.actions }
    }
    draft.value = next
    await appSettingsStore.setReaderTapZones(next)
    message.success(t('settingsSavedSuccessfully'))
  } catch (error) {
    console.error('重置阅读器点击区域设置失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}
</script>

<style scoped>
.reader-tap-zones-settings__preview {
  width: 100%;
  height: 260px;
  border-radius: 16px;
  overflow: hidden;
  background: #000;
  border: 1px solid rgba(0, 0, 0, 0.08);
}
</style>

// apps/web/src/components/reader/settings/ReaderTapZonesSettings.tsx
import { Button, Form, Select, Slider, Space, Tag, Typography, message } from 'antd'
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import ReaderTapZonesPreview from '@/components/reader/tapZones/ReaderTapZonesPreview'
import { DEFAULT_READER_TAP_ZONES, type ReaderTapZoneAction, type ReaderTapZoneKey, type ReaderTapZonesConfig } from '@/store/appSettings'
import { useAppSettingsStore } from '@/store/appSettings'

const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value))

const cloneTapZones = (value: ReaderTapZonesConfig | null | undefined): ReaderTapZonesConfig => {
  const boundaries = value?.boundaries ?? DEFAULT_READER_TAP_ZONES.boundaries
  const actions = value?.actions ?? DEFAULT_READER_TAP_ZONES.actions
  return {
    version: 1,
    boundaries: {
      left: Number((boundaries as any).left ?? DEFAULT_READER_TAP_ZONES.boundaries.left),
      right: Number((boundaries as any).right ?? DEFAULT_READER_TAP_ZONES.boundaries.right)
    },
    actions: {
      left: ((actions as any).left ?? DEFAULT_READER_TAP_ZONES.actions.left) as ReaderTapZoneAction,
      middle: ((actions as any).middle ?? DEFAULT_READER_TAP_ZONES.actions.middle) as ReaderTapZoneAction,
      right: ((actions as any).right ?? DEFAULT_READER_TAP_ZONES.actions.right) as ReaderTapZoneAction
    }
  }
}

export default function ReaderTapZonesSettings() {
  const { t } = useTranslation()
  const readerTapZones = useAppSettingsStore((state) => state.readerTapZones)
  const setReaderTapZones = useAppSettingsStore((state) => state.setReaderTapZones)

  const [saving, setSaving] = useState(false)
  const [selectedZone, setSelectedZone] = useState<ReaderTapZoneKey>('middle')
  const [draft, setDraft] = useState<ReaderTapZonesConfig>(() => cloneTapZones(readerTapZones))

  useEffect(() => {
    if (saving) return
    setDraft(cloneTapZones(readerTapZones))
  }, [readerTapZones, saving])

  const actionOptions = useMemo(
    () => [
      { value: 'prev_page', label: t('readerTapActionPrevPage') },
      { value: 'next_page', label: t('readerTapActionNextPage') },
      { value: 'toggle_toolbar', label: t('readerTapActionToggleToolbar') },
      { value: 'expand_toolbar', label: t('readerTapActionExpandToolbar') },
      { value: 'collapse_toolbar', label: t('readerTapActionCollapseToolbar') },
      { value: 'none', label: t('readerTapActionNone') }
    ],
    [t]
  )

  const zoneLabel = (zoneKey: ReaderTapZoneKey) => {
    if (zoneKey === 'left') return t('readerTapZoneLeft')
    if (zoneKey === 'right') return t('readerTapZoneRight')
    return t('readerTapZoneMiddle')
  }

  const leftRatio = Number(draft?.boundaries?.left ?? DEFAULT_READER_TAP_ZONES.boundaries.left)
  const rightRatio = Number(draft?.boundaries?.right ?? DEFAULT_READER_TAP_ZONES.boundaries.right)

  const widths = useMemo(() => {
    const left = Math.round(leftRatio * 100)
    const middle = Math.round((rightRatio - leftRatio) * 100)
    const right = Math.round((1 - rightRatio) * 100)
    return { left, middle, right }
  }, [leftRatio, rightRatio])

  const leftWidthText = `${widths.left}%`
  const middleWidthText = `${widths.middle}%`
  const rightWidthText = `${widths.right}%`

  const setBoundaries = (left: number, right: number) => {
    const minZoneWidth = 0.08
    const normalizedLeft = clamp(left, minZoneWidth, 1 - minZoneWidth)
    const normalizedRight = clamp(right, minZoneWidth, 1 - minZoneWidth)
    if (normalizedLeft >= normalizedRight) return
    if (normalizedLeft < minZoneWidth || 1 - normalizedRight < minZoneWidth || normalizedRight - normalizedLeft < minZoneWidth) return

    setDraft((prev) => ({
      ...(prev || DEFAULT_READER_TAP_ZONES),
      version: 1,
      boundaries: { left: normalizedLeft, right: normalizedRight },
      actions: { ...(prev?.actions || DEFAULT_READER_TAP_ZONES.actions) }
    }))
  }

  const selectedZoneAction = (draft?.actions as any)?.[selectedZone] ?? 'none'

  const save = async () => {
    setSaving(true)
    try {
      await setReaderTapZones(draft)
      message.success(t('settingsSavedSuccessfully'))
    } catch (error) {
      console.error('保存阅读器点击区域设置失败：', error)
      message.error(t('failedToSaveSettings'))
    } finally {
      setSaving(false)
    }
  }

  const resetToDefault = async () => {
    const next = cloneTapZones(DEFAULT_READER_TAP_ZONES)
    setSaving(true)
    try {
      setDraft(next)
      await setReaderTapZones(next)
      message.success(t('settingsSavedSuccessfully'))
    } catch (error) {
      console.error('重置阅读器点击区域设置失败：', error)
      message.error(t('failedToSaveSettings'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <Space direction="vertical" size="large" className="w-full">
      <Typography.Paragraph type="secondary" className="!mb-0">
        {t('readerTapZonesSettingsHelp')}
      </Typography.Paragraph>

      <div className="reader-tap-zones-settings__preview">
        <ReaderTapZonesPreview value={draft} onChange={setDraft} selectedZone={selectedZone} onSelectedZoneChange={setSelectedZone} overlay={false} showLabels />
      </div>

      <Form layout="vertical">
        <Form.Item label={zoneLabel(selectedZone)}>
          <Select
            value={selectedZoneAction}
            style={{ maxWidth: 360 }}
            onChange={(value) => {
              setDraft((prev) => ({
                ...(prev || DEFAULT_READER_TAP_ZONES),
                actions: { ...(prev?.actions || DEFAULT_READER_TAP_ZONES.actions), [selectedZone]: value as ReaderTapZoneAction }
              }))
            }}
            options={actionOptions}
          />
        </Form.Item>

        <Form.Item label={t('readerTapZonesLeftWidth')}>
          <Slider
            value={widths.left}
            min={8}
            max={84}
            step={1}
            tooltip={{ open: false }}
            onChange={(percent) => setBoundaries(clamp(Number(percent) / 100, 0.08, 0.92), rightRatio)}
          />
          <div className="mt-1 text-xs text-gray-500">{leftWidthText}</div>
        </Form.Item>

        <Form.Item label={t('readerTapZonesRightWidth')}>
          <Slider
            value={widths.right}
            min={8}
            max={84}
            step={1}
            tooltip={{ open: false }}
            onChange={(percent) => setBoundaries(leftRatio, 1 - clamp(Number(percent) / 100, 0.08, 0.92))}
          />
          <div className="mt-1 text-xs text-gray-500">{rightWidthText}</div>
        </Form.Item>

        <Form.Item label={t('readerTapZonesCurrentSizes')}>
          <Space wrap>
            <Tag>
              {t('readerTapZoneLeft')}: {leftWidthText}
            </Tag>
            <Tag>
              {t('readerTapZoneMiddle')}: {middleWidthText}
            </Tag>
            <Tag>
              {t('readerTapZoneRight')}: {rightWidthText}
            </Tag>
          </Space>
        </Form.Item>

        <Space>
          <Button type="primary" loading={saving} onClick={() => save().catch(() => {})}>
            {t('save')}
          </Button>
          <Button disabled={saving} onClick={() => resetToDefault().catch(() => {})}>
            {t('resetToDefault')}
          </Button>
        </Space>
      </Form>
    </Space>
  )
}
