// apps/web/src/components/reader/settings/ReaderBehaviorSettings.vue
<template>
  <a-form layout="vertical" @submit.prevent>
    <a-form-item :label="$t('readerPreloadAhead')">
      <a-input-number
        v-model:value="formPreloadAhead"
        :min="0"
        :max="20"
        :step="1"
        style="max-width: 240px"
      />
      <div class="mt-1 text-xs text-gray-500">
        {{ $t('readerPreloadAheadHelp') }}
      </div>
    </a-form-item>

    <a-form-item :label="$t('readerSplitViewDefaultEnabled')">
      <a-switch v-model:checked="formSplitDefaultEnabled" />
      <div class="mt-1 text-xs text-gray-500">
        {{ $t('readerSplitViewDefaultEnabledHelp') }}
      </div>
    </a-form-item>

    <a-form-item :label="$t('readerWideRatioThreshold')">
      <a-input-number
        v-model:value="formWideRatioThreshold"
        :min="1"
        :max="5"
        :step="0.05"
        style="max-width: 240px"
      />
      <div class="mt-1 text-xs text-gray-500">
        {{ $t('readerWideRatioThresholdHelp') }}
      </div>
    </a-form-item>

    <a-form-item :label="$t('readerToolbarAnimationMs')">
      <a-input-number
        v-model:value="formToolbarAnimationMs"
        :min="120"
        :max="600"
        :step="10"
        style="max-width: 240px"
      />
      <div class="mt-1 text-xs text-gray-500">
        {{ $t('readerToolbarAnimationMsHelp') }}
      </div>
    </a-form-item>

    <a-form-item :label="$t('readerToolbarBackgroundOpacity')">
      <a-input-number
        v-model:value="formToolbarBackgroundOpacity"
        :min="0.08"
        :max="0.8"
        :step="0.02"
        style="max-width: 240px"
      />
      <div class="mt-1 text-xs text-gray-500">
        {{ $t('readerToolbarBackgroundOpacityHelp') }}
      </div>
    </a-form-item>

    <a-form-item :label="$t('readerToolbarKeepStateOnPaging')">
      <a-switch v-model:checked="formToolbarKeepStateOnPaging" />
      <div class="mt-1 text-xs text-gray-500">
        {{ $t('readerToolbarKeepStateOnPagingHelp') }}
      </div>
    </a-form-item>

    <a-space>
      <a-button type="primary" :loading="saving" @click="save">
        {{ $t('save') }}
      </a-button>
      <a-button :disabled="saving" @click="resetToDefault">
        {{ $t('resetToDefault') }}
      </a-button>
    </a-space>
  </a-form>
</template>

<script setup>
import { ref, watch } from 'vue'
import { message } from 'ant-design-vue'
import { useI18n } from 'vue-i18n'
import { useAppSettingsStore } from '@/store/appSettings'

const { t } = useI18n()
const appSettingsStore = useAppSettingsStore()

const saving = ref(false)
const formPreloadAhead = ref(appSettingsStore.readerPreloadAhead)
const formSplitDefaultEnabled = ref(appSettingsStore.readerSplitDefaultEnabled)
const formWideRatioThreshold = ref(appSettingsStore.readerWideRatioThreshold)
const formToolbarAnimationMs = ref(appSettingsStore.readerToolbarAnimationMs)
const formToolbarBackgroundOpacity = ref(appSettingsStore.readerToolbarBackgroundOpacity)
const formToolbarKeepStateOnPaging = ref(appSettingsStore.readerToolbarKeepStateOnPaging)

watch(
  () => appSettingsStore.readerPreloadAhead,
  value => {
    formPreloadAhead.value = value
  }
)
watch(
  () => appSettingsStore.readerSplitDefaultEnabled,
  value => {
    formSplitDefaultEnabled.value = value
  }
)
watch(
  () => appSettingsStore.readerWideRatioThreshold,
  value => {
    formWideRatioThreshold.value = value
  }
)
watch(
  () => appSettingsStore.readerToolbarAnimationMs,
  value => {
    formToolbarAnimationMs.value = value
  }
)
watch(
  () => appSettingsStore.readerToolbarBackgroundOpacity,
  value => {
    formToolbarBackgroundOpacity.value = value
  }
)
watch(
  () => appSettingsStore.readerToolbarKeepStateOnPaging,
  value => {
    formToolbarKeepStateOnPaging.value = value
  }
)

const save = async () => {
  saving.value = true
  try {
    await Promise.all([
      appSettingsStore.setReaderPreloadAhead(formPreloadAhead.value),
      appSettingsStore.setReaderSplitDefaultEnabled(formSplitDefaultEnabled.value),
      appSettingsStore.setReaderWideRatioThreshold(formWideRatioThreshold.value),
      appSettingsStore.setReaderToolbarAnimationMs(formToolbarAnimationMs.value),
      appSettingsStore.setReaderToolbarBackgroundOpacity(formToolbarBackgroundOpacity.value),
      appSettingsStore.setReaderToolbarKeepStateOnPaging(formToolbarKeepStateOnPaging.value)
    ])
    message.success(t('settingsSavedSuccessfully'))
  } catch (error) {
    console.error('保存阅读器阅读行为设置失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}

const resetToDefault = async () => {
  saving.value = true
  try {
    await Promise.all([
      appSettingsStore.setReaderPreloadAhead(2),
      appSettingsStore.setReaderSplitDefaultEnabled(false),
      appSettingsStore.setReaderWideRatioThreshold(1.0),
      appSettingsStore.setReaderToolbarAnimationMs(240),
      appSettingsStore.setReaderToolbarBackgroundOpacity(0.72),
      appSettingsStore.setReaderToolbarKeepStateOnPaging(true)
    ])
    message.success(t('settingsSavedSuccessfully'))
  } catch (error) {
    console.error('重置阅读器阅读行为设置失败：', error)
    message.error(t('failedToSaveSettings'))
  } finally {
    saving.value = false
  }
}
</script>

// apps/web/src/components/reader/settings/ReaderBehaviorSettings.tsx
import { Button, Divider, Form, InputNumber, Space, Switch, message } from 'antd'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useAppSettingsStore } from '@/store/appSettings'

export default function ReaderBehaviorSettings() {
  const { t } = useTranslation()

  const readerPreloadAhead = useAppSettingsStore((state) => state.readerPreloadAhead)
  const readerSplitDefaultEnabled = useAppSettingsStore((state) => state.readerSplitDefaultEnabled)
  const readerWideRatioThreshold = useAppSettingsStore((state) => state.readerWideRatioThreshold)
  const readerToolbarAnimationMs = useAppSettingsStore((state) => state.readerToolbarAnimationMs)
  const readerToolbarBackgroundOpacity = useAppSettingsStore((state) => state.readerToolbarBackgroundOpacity)
  const readerToolbarKeepStateOnPaging = useAppSettingsStore((state) => state.readerToolbarKeepStateOnPaging)
  const readerToolbarCenterClickToggleEnabled = useAppSettingsStore((state) => state.readerToolbarCenterClickToggleEnabled)

  const setReaderPreloadAhead = useAppSettingsStore((state) => state.setReaderPreloadAhead)
  const setReaderSplitDefaultEnabled = useAppSettingsStore((state) => state.setReaderSplitDefaultEnabled)
  const setReaderWideRatioThreshold = useAppSettingsStore((state) => state.setReaderWideRatioThreshold)
  const setReaderToolbarAnimationMs = useAppSettingsStore((state) => state.setReaderToolbarAnimationMs)
  const setReaderToolbarBackgroundOpacity = useAppSettingsStore((state) => state.setReaderToolbarBackgroundOpacity)
  const setReaderToolbarKeepStateOnPaging = useAppSettingsStore((state) => state.setReaderToolbarKeepStateOnPaging)
  const setReaderToolbarCenterClickToggleEnabled = useAppSettingsStore((state) => state.setReaderToolbarCenterClickToggleEnabled)

  const [saving, setSaving] = useState(false)
  const [formPreloadAhead, setFormPreloadAhead] = useState(readerPreloadAhead)
  const [formSplitDefaultEnabled, setFormSplitDefaultEnabled] = useState(readerSplitDefaultEnabled)
  const [formWideRatioThreshold, setFormWideRatioThreshold] = useState(readerWideRatioThreshold)
  const [formToolbarAnimationMs, setFormToolbarAnimationMs] = useState(readerToolbarAnimationMs)
  const [formToolbarBackgroundOpacity, setFormToolbarBackgroundOpacity] = useState(readerToolbarBackgroundOpacity)
  const [formToolbarKeepStateOnPaging, setFormToolbarKeepStateOnPaging] = useState(readerToolbarKeepStateOnPaging)
  const [formToolbarCenterClickToggleEnabled, setFormToolbarCenterClickToggleEnabled] = useState(readerToolbarCenterClickToggleEnabled)

  useEffect(() => setFormPreloadAhead(readerPreloadAhead), [readerPreloadAhead])
  useEffect(() => setFormSplitDefaultEnabled(readerSplitDefaultEnabled), [readerSplitDefaultEnabled])
  useEffect(() => setFormWideRatioThreshold(readerWideRatioThreshold), [readerWideRatioThreshold])
  useEffect(() => setFormToolbarAnimationMs(readerToolbarAnimationMs), [readerToolbarAnimationMs])
  useEffect(() => setFormToolbarBackgroundOpacity(readerToolbarBackgroundOpacity), [readerToolbarBackgroundOpacity])
  useEffect(() => setFormToolbarKeepStateOnPaging(readerToolbarKeepStateOnPaging), [readerToolbarKeepStateOnPaging])
  useEffect(
    () => setFormToolbarCenterClickToggleEnabled(readerToolbarCenterClickToggleEnabled),
    [readerToolbarCenterClickToggleEnabled]
  )

  const save = async () => {
    setSaving(true)
    try {
      await Promise.all([
        setReaderPreloadAhead(formPreloadAhead),
        setReaderSplitDefaultEnabled(formSplitDefaultEnabled),
        setReaderWideRatioThreshold(formWideRatioThreshold),
        setReaderToolbarAnimationMs(formToolbarAnimationMs),
        setReaderToolbarBackgroundOpacity(formToolbarBackgroundOpacity),
        setReaderToolbarKeepStateOnPaging(formToolbarKeepStateOnPaging),
        setReaderToolbarCenterClickToggleEnabled(formToolbarCenterClickToggleEnabled)
      ])
      message.success(t('settingsSavedSuccessfully'))
    } catch (error) {
      console.error('保存阅读行为设置失败：', error)
      message.error(t('failedToSaveSettings'))
    } finally {
      setSaving(false)
    }
  }

  const resetToDefault = async () => {
    setSaving(true)
    try {
      await Promise.all([
        setReaderPreloadAhead(2),
        setReaderSplitDefaultEnabled(false),
        setReaderWideRatioThreshold(1.0),
        setReaderToolbarAnimationMs(240),
        setReaderToolbarBackgroundOpacity(0.28),
        setReaderToolbarKeepStateOnPaging(true),
        setReaderToolbarCenterClickToggleEnabled(true)
      ])
      message.success(t('settingsSavedSuccessfully'))
    } catch (error) {
      console.error('重置阅读行为设置失败：', error)
      message.error(t('failedToSaveSettings'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <Form layout="vertical">
      <Form.Item label={t('readerPreloadAhead')}>
        <InputNumber
          value={formPreloadAhead}
          min={0}
          max={20}
          step={1}
          style={{ maxWidth: 240 }}
          onChange={(value) => setFormPreloadAhead(Number(value ?? 0))}
        />
        <div className="mt-1 text-xs text-gray-500">{t('readerPreloadAheadHelp')}</div>
      </Form.Item>

      <Form.Item label={t('readerSplitViewDefaultEnabled')}>
        <Switch checked={formSplitDefaultEnabled} onChange={setFormSplitDefaultEnabled} />
        <div className="mt-1 text-xs text-gray-500">{t('readerSplitViewDefaultEnabledHelp')}</div>
      </Form.Item>

      <Form.Item label={t('readerWideRatioThreshold')}>
        <InputNumber
          value={formWideRatioThreshold}
          min={1}
          max={5}
          step={0.05}
          style={{ maxWidth: 240 }}
          onChange={(value) => setFormWideRatioThreshold(Number(value ?? 1))}
        />
        <div className="mt-1 text-xs text-gray-500">{t('readerWideRatioThresholdHelp')}</div>
      </Form.Item>

      <Divider />

      <Form.Item label={t('readerToolbarAnimationMs')}>
        <InputNumber
          value={formToolbarAnimationMs}
          min={120}
          max={600}
          step={10}
          style={{ maxWidth: 240 }}
          onChange={(value) => setFormToolbarAnimationMs(Number(value ?? 240))}
        />
        <div className="mt-1 text-xs text-gray-500">{t('readerToolbarAnimationMsHelp')}</div>
      </Form.Item>

      <Form.Item label={t('readerToolbarBackgroundOpacity')}>
        <InputNumber
          value={formToolbarBackgroundOpacity}
          min={0.08}
          max={0.8}
          step={0.02}
          style={{ maxWidth: 240 }}
          onChange={(value) => setFormToolbarBackgroundOpacity(Number(value ?? 0.28))}
        />
        <div className="mt-1 text-xs text-gray-500">{t('readerToolbarBackgroundOpacityHelp')}</div>
      </Form.Item>

      <Form.Item label={t('readerToolbarKeepStateOnPaging')}>
        <Switch checked={formToolbarKeepStateOnPaging} onChange={setFormToolbarKeepStateOnPaging} />
        <div className="mt-1 text-xs text-gray-500">{t('readerToolbarKeepStateOnPagingHelp')}</div>
      </Form.Item>

      <Form.Item label={t('readerToolbarCenterClickToggleEnabled')}>
        <Switch checked={formToolbarCenterClickToggleEnabled} onChange={setFormToolbarCenterClickToggleEnabled} />
        <div className="mt-1 text-xs text-gray-500">{t('readerToolbarCenterClickToggleEnabledHelp')}</div>
      </Form.Item>

      <Space>
        <Button type="primary" loading={saving} onClick={() => save().catch(() => {})}>
          {t('save')}
        </Button>
        <Button disabled={saving} onClick={() => resetToDefault().catch(() => {})}>
          {t('resetToDefault')}
        </Button>
      </Space>
    </Form>
  )
}
