// apps/web/src/pages/settings/SettingsReaderView.tsx
import { Space } from 'antd'
import { useTranslation } from 'react-i18next'
import ReaderBehaviorSettings from '@/components/reader/settings/ReaderBehaviorSettings'
import ReaderTapZonesSettings from '@/components/reader/settings/ReaderTapZonesSettings'
import ReaderUiAppearanceSettings from '@/components/reader/settings/ReaderUiAppearanceSettings'
import GlassPage from '@/components/glass/ui/GlassPage'
import GlassSurface from '@/components/glass/ui/GlassSurface'

export default function SettingsReaderView() {
  const { t } = useTranslation()
  return (
    <GlassPage>
      <Space direction="vertical" size="large" className="w-full">
        <GlassSurface title={t('readerBehaviorSettingsTitle')}>
          <ReaderBehaviorSettings />
        </GlassSurface>

        <GlassSurface title={t('readerUiAppearance')}>
          <ReaderUiAppearanceSettings />
        </GlassSurface>

        <GlassSurface title={t('readerTapZonesConfigTitle')}>
          <ReaderTapZonesSettings />
        </GlassSurface>
      </Space>
    </GlassPage>
  )
}

// apps/web/_legacy/vue/src/pages/settings/SettingsReaderView.vue
<template>
  <GlassPage>
    <a-space direction="vertical" size="large" class="w-full">
      <GlassSurface :title="$t('readerBehaviorSettingsTitle')">
        <ReaderBehaviorSettings />
      </GlassSurface>

      <GlassSurface :title="$t('readerUiAppearance')">
        <ReaderUiAppearanceSettings />
      </GlassSurface>

      <GlassSurface :title="$t('readerTapZonesConfigTitle')">
        <ReaderTapZonesSettings />
      </GlassSurface>
    </a-space>
  </GlassPage>
</template>

<script setup>
import ReaderTapZonesSettings from '@/components/ReaderTapZonesSettings.vue'
import ReaderBehaviorSettings from '@/components/reader/settings/ReaderBehaviorSettings.vue'
import ReaderUiAppearanceSettings from '@/components/reader/settings/ReaderUiAppearanceSettings.vue'
import GlassPage from '@/components/glass/ui/GlassPage.vue'
import GlassSurface from '@/components/glass/ui/GlassSurface.vue'
</script>
