// apps/web/src/pages/settings/SettingsTagManagementView.tsx
import { Alert, Divider, Space, Spin, Typography } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { http } from '@/api/http'
import TagManager from '@/components/tags/TagManager'
import TagTypeManager, { type TagType } from '@/components/tags/TagTypeManager'
import GlassPage from '@/components/glass/ui/GlassPage'
import GlassSurface from '@/components/glass/ui/GlassSurface'

export default function SettingsTagManagementView() {
  const { t } = useTranslation()

  const [tagTypes, setTagTypes] = useState<TagType[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const fetchTagData = useCallback(async () => {
    setLoading(true)
    setError('')
    try {
      const response = await http.get('/api/v1/tag-types')
      setTagTypes((response?.data || []) as TagType[])
    } catch (err) {
      console.error('加载标签类型失败：', err)
      const message = (err as any)?.response?.data?.error || t('failedToFetchTagTypes')
      setError(String(message))
    } finally {
      setLoading(false)
    }
  }, [t])

  useEffect(() => {
    fetchTagData().catch(() => {})
  }, [fetchTagData])

  return (
    <GlassPage>
      <Space direction="vertical" size="large" className="w-full">
        <GlassSurface title={t('tagTypeManagement')}>
          <Space direction="vertical" size="large" className="w-full">
            <div>
              <Typography.Title level={4}>{t('tagTypes')}</Typography.Title>

              {loading ? (
                <div className="py-6">
                  <Spin />
                </div>
              ) : error ? (
                <Alert type="error" showIcon message={t('failedToFetchTagTypes')} description={error} />
              ) : (
                <TagTypeManager types={tagTypes} onDataChanged={fetchTagData} />
              )}
            </div>

            <Divider />

            <TagManager types={tagTypes} />
          </Space>
        </GlassSurface>
      </Space>
    </GlassPage>
  )
}

// apps/web/src/pages/settings/SettingsTagManagementView.vue
<template>
  <GlassPage>
    <a-space direction="vertical" size="large" class="w-full">
      <GlassSurface :title="$t('tagTypeManagement')">
        <a-space direction="vertical" size="large" class="w-full">
          <div>
            <a-typography-title :level="4">
              {{ $t('tagTypes') }}
            </a-typography-title>
            <TagTypeManager :types="tagTypes" @dataChanged="fetchTagData" />
          </div>

          <a-divider />

          <TagManager :types="tagTypes" />
        </a-space>
      </GlassSurface>
    </a-space>
  </GlassPage>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import axios from 'axios'
import { message } from 'ant-design-vue'
import { useI18n } from 'vue-i18n'

import TagTypeManager from '@/components/TagTypeManager.vue'
import TagManager from '@/components/TagManager.vue'
import GlassPage from '@/components/glass/ui/GlassPage.vue'
import GlassSurface from '@/components/glass/ui/GlassSurface.vue'

const { t } = useI18n()
const tagTypes = ref([])

const fetchTagData = async () => {
  try {
    const response = await axios.get('/api/v1/tag_types')
    tagTypes.value = response.data
  } catch (error) {
    console.error('加载标签类型失败：', error)
    message.error(t('failedToFetchTagTypes'))
  }
}

onMounted(fetchTagData)
</script>
