// apps/web/src/pages/settings/SettingsDisplayView.tsx
import { Space } from 'antd'
import { useTranslation } from 'react-i18next'
import ManagerAppearanceSettings from '@/components/glass/settings/ManagerAppearanceSettings'
import GlassPage from '@/components/glass/ui/GlassPage'
import GlassSurface from '@/components/glass/ui/GlassSurface'
import LibraryDisplaySettings from '@/components/library/LibraryDisplaySettings'

export default function SettingsDisplayView() {
  const { t } = useTranslation()

  return (
    <GlassPage>
      <Space direction="vertical" size="large" className="w-full">
        <GlassSurface title={t('libraryDisplaySettings')}>
          <LibraryDisplaySettings />
        </GlassSurface>

        <GlassSurface title={t('managerUiAppearance')}>
          <ManagerAppearanceSettings />
        </GlassSurface>
      </Space>
    </GlassPage>
  )
}

// apps/web/src/pages/settings/SettingsDisplayView.vue
<template>
  <GlassPage>
    <a-space direction="vertical" size="large" class="w-full">
      <GlassSurface :title="$t('libraryDisplaySettings')">
        <LibraryDisplaySettings />
      </GlassSurface>

      <GlassSurface :title="$t('managerUiAppearance')">
        <ManagerAppearanceSettings />
      </GlassSurface>
    </a-space>
  </GlassPage>
</template>

<script setup>
import LibraryDisplaySettings from '@/components/LibraryDisplaySettings.vue'
import ManagerAppearanceSettings from '@/components/glass/settings/ManagerAppearanceSettings.vue'
import GlassPage from '@/components/glass/ui/GlassPage.vue'
import GlassSurface from '@/components/glass/ui/GlassSurface.vue'
</script>
