// apps/web/src/pages/settings/SettingsTasksView.vue
<template>
  <GlassPage>
    <a-space direction="vertical" size="large" class="w-full">
      <GlassSurface>
        <TaskManager />
      </GlassSurface>
    </a-space>
  </GlassPage>
</template>

<script setup>
import TaskManager from '@/components/TaskManager.vue'
import GlassPage from '@/components/glass/ui/GlassPage.vue'
import GlassSurface from '@/components/glass/ui/GlassSurface.vue'
</script>

// apps/web/src/pages/settings/SettingsTasksView.tsx
import { Space } from 'antd'
import { useTranslation } from 'react-i18next'
import GlassPage from '@/components/glass/ui/GlassPage'
import GlassSurface from '@/components/glass/ui/GlassSurface'
import TaskManager from '@/components/tasks/TaskManager'
import TaskSettings from '@/components/tasks/TaskSettings'

export default function SettingsTasksView() {
  const { t } = useTranslation()

  return (
    <GlassPage>
      <Space direction="vertical" size="large" className="w-full">
        <GlassSurface title={t('taskSettings')}>
          <TaskSettings />
        </GlassSurface>

        <GlassSurface>
          <TaskManager />
        </GlassSurface>
      </Space>
    </GlassPage>
  )
}
