// frontend/src/views/EditView.vue
<template>
  <div class="p-8 max-w-4xl mx-auto">
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-2xl font-bold text-gray-800">{{ $t('editFileDetails') }}</h1>
      <button @click="goBack" class="btn btn-secondary">
        {{ $t('back') }}
      </button>
    </div>
    <div v-if="error" class="text-center text-red-500">
      <p>{{ $t('errorLoadingData', { error: error }) }}</p>
    </div>
    <div v-else-if="file" class="space-y-6">
      <div class="p-6 bg-white rounded-lg shadow">
        <h2 class="text-lg font-semibold border-b pb-2 mb-4">{{ $t('metadata') }}</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
          <div class="col-span-full">
            <strong class="font-medium text-gray-600">{{ $t('filename') }}:</strong>
            <div class="flex items-center gap-2 mt-1">
              <input type="text" v-model="editableFilename" class="flex-grow p-2 border rounded-md">
              <button @click="handleRename" :disabled="isRenaming" class="btn btn-secondary">
                {{ isRenaming ? $t('renaming') : $t('rename') }}
              </button>
            </div>
            <p v-if="renameStatus === 'error'" class="text-red-500 text-sm mt-1">{{ renameError }}</p>
            <p v-if="renameStatus === 'success'" class="text-green-500 text-sm mt-1">{{ $t('renameSuccess') }}</p>
          </div>
          <div><strong class="font-medium text-gray-600">{{ $t('pages') }}:</strong> <span class="text-gray-800">{{ file.total_pages }}</span></div>
          <div class="col-span-full"><strong class="font-medium text-gray-600">{{ $t('fullPath') }}:</strong> <span class="text-gray-800 break-all">{{ file.file_path }}</span></div>
          <div class="col-span-full"><strong class="font-medium text-gray-600">{{ $t('hash') }}:</strong> <span class="text-gray-800 break-all">{{ file.file_hash }}</span></div>
        </div>
      </div>
      
      <div class="p-6 bg-white rounded-lg shadow">
        <h2 class="text-lg font-semibold border-b pb-2 mb-4">{{ $t('tags') }}</h2>
        <div class="flex items-start gap-4">
          <TagSelector v-model="file.tags" />
          <div v-if="file.tags && file.tags.length > 0" class="flex-grow pl-4">
            <div class="flex flex-wrap gap-2">
              <span v-for="tag in file.tags" :key="tag.id" class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                {{ tag.name }}
                <button @click="toggleTag(tag)" class="flex-shrink-0 ml-1.5 h-4 w-4 rounded-full inline-flex items-center justify-center text-blue-400 hover:bg-blue-200 hover:text-blue-500 focus:outline-none focus:bg-blue-500 focus:text-white">
                  <span class="sr-only">{{ $t('removeTag') }}</span>
                  <svg class="h-2 w-2" stroke="currentColor" fill="none" viewBox="0 0 8 8">
                    <path stroke-linecap="round" stroke-width="1.5" d="M1 1l6 6m0-6L1 7" />
                  </svg>
                </button>
              </span>
            </div>
          </div>
        </div>
      </div>

      <!-- Bookmarks Section -->
      <div class="p-6 bg-white rounded-lg shadow">
        <h2 class="text-lg font-semibold border-b pb-2 mb-4">{{ $t('bookmarks') }}</h2>
        <!-- Add new bookmark form -->
        <div class="flex items-start gap-4 mb-6 pb-6 border-b">
          <input type="number" v-model.number="newBookmark.page" :placeholder="$t('pagePlaceholder')" min="1" class="w-24 p-2 border rounded-md">
          <input type="text" v-model="newBookmark.note" :placeholder="$t('noteOptional')" class="flex-grow p-2 border rounded-md">
          <button @click="addBookmark" :disabled="!newBookmark.page" class="btn btn-primary">{{ $t('add') }}</button>
        </div>
        <p v-if="bookmarkError" class="text-red-500 text-sm mb-4">{{ bookmarkError }}</p>

        <!-- Existing bookmarks list -->
        <div v-if="bookmarks.length" class="space-y-3">
            <div v-for="bookmark in bookmarks" :key="bookmark.id" class="flex justify-between items-center p-3 bg-gray-50 rounded-md">
                <div>
                    <p class="font-semibold">{{ $t('page') }} {{ bookmark.page_number }}</p>
                    <p v-if="bookmark.note" class="text-sm text-gray-600">{{ bookmark.note }}</p>
                </div>
                <button @click="deleteBookmark(bookmark.id)" class="btn btn-danger btn-sm">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm4 0a1 1 0 012 0v6a1 1 0 11-2 0V8z" clip-rule="evenodd" /></svg>
                </button>
            </div>
        </div>
        <div v-else>
            <p class="text-gray-500">{{ $t('noBookmarksYet') }}</p>
        </div>
      </div>

      <div class="flex justify-end items-center gap-4 mt-6">
        <label class="flex items-center">
          <input type="checkbox" v-model="renameFileOnSave" class="h-4 w-4 text-monet-blue focus:ring-monet-blue border-gray-300 rounded">
          <span class="ml-2 text-sm text-gray-600">{{ $t('renameFileOnSave') }}</span>
        </label>
         <p v-if="saveStatus === 'success'" class="text-green-600">{{ $t('successfullySaved') }}</p>
         <p v-if="saveStatus === 'error'" class="text-red-500">{{ saveError }}</p>
        <button @click="handleSave" :disabled="isSaving" class="btn btn-primary">
          {{ isSaving ? $t('saving') : $t('saveChanges') }}
        </button>
      </div>

    </div>
  </div>
</template>


<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import axios from 'axios'
import TagSelector from '@/components/TagSelector.vue'

const route = useRoute()
const router = useRouter()
const { t } = useI18n()
const file = ref(null)
const allTags = ref([])
const bookmarks = ref([])
const loading = ref(true)
const error = ref(null)
const renameFileOnSave = ref(true)
const editableFilename = ref('')

const isRenaming = ref(false)
const renameStatus = ref('idle') // idle, success, error
const renameError = ref(null)

const newBookmark = ref({ page: null, note: '' })
const bookmarkError = ref(null)

const goBack = () => {
  router.back()
}

const isSaving = ref(false)
const saveStatus = ref('idle') // idle, success, error
const saveError = ref(null)

const toggleTag = (tag) => {
    if (!file.value || !file.value.tags) return;
    const index = file.value.tags.findIndex(t => t.id === tag.id);
    if (index > -1) {
        file.value.tags.splice(index, 1);
    }
};

const addBookmark = async () => {
    bookmarkError.value = null
    if (!newBookmark.value.page || newBookmark.value.page < 1) {
        bookmarkError.value = t('bookmarkPagePositiveNumber')
        return;
    }

    try {
        const response = await axios.post(`/api/v1/files/${file.value.id}/bookmarks`, {
            page_number: newBookmark.value.page,
            note: newBookmark.value.note
        });
        bookmarks.value.push(response.data);
        bookmarks.value.sort((a, b) => a.page_number - b.page_number); // Keep the list sorted
        // Reset form
        newBookmark.value.page = null;
        newBookmark.value.note = '';
    } catch (err) {
        bookmarkError.value = err.response?.data?.error || t('failedToAddBookmark');
    }
}

const deleteBookmark = async (bookmarkId) => {
    bookmarkError.value = null
    try {
        await axios.delete(`/api/v1/bookmarks/${bookmarkId}`);
        bookmarks.value = bookmarks.value.filter(b => b.id !== bookmarkId);
    } catch (err) {
        bookmarkError.value = err.response?.data?.error || t('failedToDeleteBookmark');
    }
}

const handleSave = async () => {
  isSaving.value = true
  saveStatus.value = 'idle'
  saveError.value = null
  try {
    const payload = {
      tags: file.value.tags,
      rename_file: renameFileOnSave.value
    }
    const response = await axios.put(`/api/v1/files/${file.value.id}`, payload)
    file.value = response.data // Update local state with response from server
    saveStatus.value = 'success'
     setTimeout(() => saveStatus.value = 'idle', 3000) // Reset after 3s
  } catch (err) {
    saveStatus.value = 'error'
    saveError.value = err.response?.data?.error || t('unexpectedSaveError')
  } finally {
    isSaving.value = false
  }
}

const handleRename = async () => {
  if (!editableFilename.value || !file.value) return;

  // Extract filename without extension
  const currentFilenameWithoutExt = editableFilename.value.includes('.')
    ? editableFilename.value.substring(0, editableFilename.value.lastIndexOf('.'))
    : editableFilename.value;

  isRenaming.value = true
  renameStatus.value = 'idle'
  renameError.value = null
  try {
    await axios.post(`/api/rename/file/${file.value.id}`, {
      new_filename: currentFilenameWithoutExt
    })
    renameStatus.value = 'success'
    // The backend will emit a socket event, so we might not need to update the path manually here.
    // However, it's good practice to update it for immediate feedback.
    const parts = file.value.file_path.split(/[\\/]/);
    const ext = parts.pop().split('.').pop();
    parts[parts.length - 1] = `${currentFilenameWithoutExt}.${ext}`;
    file.value.file_path = parts.join('/');
    editableFilename.value = `${currentFilenameWithoutExt}`

    setTimeout(() => renameStatus.value = 'idle', 3000)
  } catch (err) {
    renameStatus.value = 'error'
    renameError.value = err.response?.data?.error || t('unexpectedRenameError')
  } finally {
    isRenaming.value = false
  }
}

onMounted(async () => {
  const fileId = route.params.id
  try {
    const [fileResponse, tagsResponse, bookmarksResponse] = await Promise.all([
      axios.get(`/api/v1/files/${fileId}`),
      axios.get('/api/v1/tags'),
      axios.get(`/api/v1/files/${fileId}/bookmarks`),
    ])
    file.value = fileResponse.data
    allTags.value = tagsResponse.data
    bookmarks.value = bookmarksResponse.data
    if (file.value) {
      const filename = file.value.file_path.split(/[\\/]/).pop()
      editableFilename.value = filename.substring(0, filename.lastIndexOf('.'))
    }
  } catch (err) {
    error.value = err.response?.data?.error || err.message
  } finally {
    loading.value = false
  }
})
</script>

<style>
.btn {
  @apply py-2 px-4 rounded-md font-semibold text-sm transition-colors;
}
.btn-primary {
  @apply bg-monet-blue text-white hover:bg-blue-700 disabled:bg-gray-400;
}
.btn-secondary {
  @apply bg-monet-grey text-gray-800 hover:bg-gray-300;
}
.btn-danger {
  @apply bg-red-500 text-white hover:bg-red-600;
}
.btn-sm {
  @apply py-1 px-2 text-xs;
}
</style>

// apps/web/src/pages/EditView.tsx
import { ArrowLeftOutlined, DeleteOutlined } from '@ant-design/icons'
import { Alert, Button, Descriptions, Divider, Empty, Form, Input, InputNumber, Space, Spin, Table, Tag, Tooltip, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate, useParams } from 'react-router-dom'
import { http } from '@/api/http'
import GlassPage from '@/components/glass/ui/GlassPage'
import GlassSurface from '@/components/glass/ui/GlassSurface'
import TagSelector, { type SimpleTag } from '@/components/tags/TagSelector'

type FileRecord = {
  id: number
  file_path: string
  total_pages: number
  content_sha256: string | null
  tags: SimpleTag[]
}

type BookmarkRecord = {
  id: number
  page_number: number
  note: string | null
}

const getFilenameFromPath = (path: string | null | undefined) => {
  const raw = String(path || '')
  if (!raw) return ''
  const parts = raw.split(/[\\/]/)
  return parts[parts.length - 1] || ''
}

type TagSaveStatus = 'idle' | 'saving' | 'success' | 'error'

export default function EditView() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { id } = useParams()

  const [file, setFile] = useState<FileRecord | null>(null)
  const fileRef = useRef<FileRecord | null>(null)
  const [bookmarks, setBookmarks] = useState<BookmarkRecord[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const [editableFilename, setEditableFilename] = useState('')
  const [renaming, setRenaming] = useState(false)

  const [tagSaveStatus, setTagSaveStatus] = useState<TagSaveStatus>('idle')
  const [tagSaveError, setTagSaveError] = useState('')
  const tagSavingRef = useRef(false)
  const tagSavePendingRef = useRef(false)
  const suppressTagAutoSaveRef = useRef(false)
  const tagSaveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const [newBookmarkPage, setNewBookmarkPage] = useState<number | null>(null)
  const [newBookmarkNote, setNewBookmarkNote] = useState('')
  const [bookmarkError, setBookmarkError] = useState('')
  const [bookmarkSaving, setBookmarkSaving] = useState(false)

  useEffect(() => {
    fileRef.current = file
  }, [file])

  const totalPages = useMemo(() => Number(file?.total_pages || 0), [file?.total_pages])

  const syncEditableFilename = useCallback((nextFile: FileRecord | null) => {
    setEditableFilename(getFilenameFromPath(nextFile?.file_path))
  }, [])

  const fetchData = useCallback(async () => {
    if (!id) {
      setError(t('mangaNotFound'))
      setLoading(false)
      return
    }
    setLoading(true)
    setError('')
    try {
      suppressTagAutoSaveRef.current = true
      const [fileResponse, bookmarksResponse] = await Promise.all([
        http.get(`/api/v1/files/${id}`),
        http.get(`/api/v1/files/${id}/bookmarks`)
      ])
      const nextFile = (fileResponse?.data || null) as FileRecord | null
      const nextBookmarks = ((bookmarksResponse?.data || []) as BookmarkRecord[]).slice().sort((a, b) => a.page_number - b.page_number)

      setFile(nextFile)
      setBookmarks(nextBookmarks)
      syncEditableFilename(nextFile)
    } catch (err) {
      console.error('加载编辑页数据失败：', err)
      const msg = (err as any)?.response?.data?.error || (err as any)?.message || ''
      setError(msg || t('errorLoadingData', { error: '' }))
    } finally {
      setLoading(false)
      setTimeout(() => {
        suppressTagAutoSaveRef.current = false
      }, 0)
    }
  }, [id, syncEditableFilename, t])

  useEffect(() => {
    fetchData().catch(() => {})
  }, [fetchData])

  useEffect(() => {
    return () => {
      if (tagSaveTimerRef.current) {
        clearTimeout(tagSaveTimerRef.current)
        tagSaveTimerRef.current = null
      }
    }
  }, [])

  const handleRename = useCallback(async () => {
    const currentFile = fileRef.current
    const nextName = editableFilename.trim()
    if (!currentFile || !nextName) {
      return
    }

    setRenaming(true)
    try {
      const response = await http.patch(`/api/v1/files/${currentFile.id}`, { new_filename: nextName })
      const nextFile = (response?.data || null) as FileRecord | null
      suppressTagAutoSaveRef.current = true
      setFile(nextFile)
      syncEditableFilename(nextFile)
      message.success(t('renameSuccess'))
    } catch (err) {
      console.error('重命名文件失败：', err)
      const msg = (err as any)?.response?.data?.error || t('unexpectedRenameError')
      message.error(String(msg))
    } finally {
      setRenaming(false)
      setTimeout(() => {
        suppressTagAutoSaveRef.current = false
      }, 0)
    }
  }, [editableFilename, syncEditableFilename, t])

  const saveTags = useCallback(
    async function saveTagsImpl({ renameFile = false, silent = true }: { renameFile?: boolean; silent?: boolean } = {}) {
      const currentFile = fileRef.current
      if (!currentFile) {
        return
      }

      if (tagSavingRef.current) {
        tagSavePendingRef.current = true
        return
      }

      tagSavingRef.current = true
      setTagSaveStatus('saving')
      setTagSaveError('')
      try {
        const response = await http.put(`/api/v1/files/${currentFile.id}`, {
          tags: currentFile.tags,
          rename_file: renameFile
        })
        const nextFile = (response?.data || null) as FileRecord | null
        suppressTagAutoSaveRef.current = true
        setFile(nextFile)
        syncEditableFilename(nextFile)

        setTagSaveStatus('success')
        if (!silent) {
          message.success(t('successfullySaved'))
        }
        setTimeout(() => {
          setTagSaveStatus((prev) => (prev === 'success' ? 'idle' : prev))
        }, 2000)
      } catch (err) {
        console.error('保存标签失败：', err)
        const msg = (err as any)?.response?.data?.error || t('unexpectedSaveError')
        setTagSaveStatus('error')
        setTagSaveError(String(msg))
        message.error(String(msg))
      } finally {
        tagSavingRef.current = false
        setTimeout(() => {
          suppressTagAutoSaveRef.current = false
        }, 0)

        if (tagSavePendingRef.current) {
          tagSavePendingRef.current = false
          saveTagsImpl().catch(() => {})
        }
      }
    },
    [syncEditableFilename, t]
  )

  useEffect(() => {
    const currentFile = fileRef.current
    if (!currentFile) {
      return
    }
    if (suppressTagAutoSaveRef.current) {
      return
    }
    if (tagSaveTimerRef.current) {
      clearTimeout(tagSaveTimerRef.current)
      tagSaveTimerRef.current = null
    }
    tagSaveTimerRef.current = setTimeout(() => {
      saveTags({ renameFile: false, silent: true }).catch(() => {})
    }, 500)
  }, [file?.tags, saveTags])

  const removeTag = (tag: SimpleTag) => {
    setFile((prev) => {
      if (!prev) return prev
      return { ...prev, tags: (prev.tags || []).filter((item) => item.id !== tag.id) }
    })
  }

  const addBookmark = async () => {
    setBookmarkError('')
    const currentFile = fileRef.current
    if (!currentFile) {
      return
    }

    const pageNumberUi = Number(newBookmarkPage)
    if (!pageNumberUi || pageNumberUi < 1) {
      setBookmarkError(t('bookmarkPagePositiveNumber'))
      return
    }
    if (totalPages && pageNumberUi > totalPages) {
      setBookmarkError(t('goToPageOutOfRange', { total: totalPages }))
      return
    }

    setBookmarkSaving(true)
    try {
      const response = await http.post(`/api/v1/files/${currentFile.id}/bookmarks`, {
        page_number: pageNumberUi - 1,
        note: newBookmarkNote || null
      })
      const record = response?.data as BookmarkRecord
      setBookmarks((prev) => prev.concat([record]).slice().sort((a, b) => a.page_number - b.page_number))
      setNewBookmarkPage(null)
      setNewBookmarkNote('')
      message.success(t('bookmarkSaved'))
    } catch (err) {
      console.error('添加书签失败：', err)
      const msg = (err as any)?.response?.data?.error || t('failedToAddBookmark')
      setBookmarkError(String(msg))
      message.error(String(msg))
    } finally {
      setBookmarkSaving(false)
    }
  }

  const deleteBookmark = async (bookmarkId: number) => {
    setBookmarkError('')
    try {
      await http.delete(`/api/v1/bookmarks/${bookmarkId}`)
      setBookmarks((prev) => prev.filter((item) => item.id !== bookmarkId))
      message.success(t('remove'))
    } catch (err) {
      console.error('删除书签失败：', err)
      const msg = (err as any)?.response?.data?.error || t('failedToDeleteBookmark')
      setBookmarkError(String(msg))
      message.error(String(msg))
    }
  }

  const bookmarkColumns: ColumnsType<BookmarkRecord> = useMemo(
    () => [
      {
        title: t('pageNumber'),
        dataIndex: 'page_number',
        key: 'page',
        width: 120,
        render: (value: number) => <strong>{Number(value) + 1}</strong>
      },
      {
        title: t('note'),
        dataIndex: 'note',
        key: 'note',
        render: (value: string | null) => <Typography.Text type="secondary">{value || '--'}</Typography.Text>
      },
      {
        title: t('actions'),
        key: 'action',
        width: 80,
        align: 'center',
        render: (_value: unknown, record: BookmarkRecord) => (
          <Button type="text" danger size="small" onClick={() => deleteBookmark(record.id).catch(() => {})}>
            <DeleteOutlined />
          </Button>
        )
      }
    ],
    [t]
  )

  const tagSaveExtra = useMemo(() => {
    if (tagSaveStatus === 'saving') {
      return <Typography.Text type="secondary">{t('saving')}</Typography.Text>
    }
    if (tagSaveStatus === 'success') {
      return <Typography.Text type="success">{t('successfullySaved')}</Typography.Text>
    }
    if (tagSaveStatus === 'error') {
      return <Typography.Text type="danger">{tagSaveError || t('unexpectedSaveError')}</Typography.Text>
    }
    return null
  }, [tagSaveError, tagSaveStatus, t])

  return (
    <GlassPage>
      <Space direction="vertical" size="large" className="w-full">
        <div>
          <Button icon={<ArrowLeftOutlined />} onClick={() => navigate(-1)}>
            {t('back')}
          </Button>
        </div>

        {error ? <Alert type="error" showIcon message={t('failedToLoadMangaDetails')} description={error} /> : null}

        <Spin spinning={loading}>
          {file ? (
            <Space direction="vertical" size="large" className="w-full">
              <GlassSurface title={t('metadata')}>
                <Space direction="vertical" size="middle" className="w-full">
                  <Form layout="vertical">
                    <Form.Item label={t('filename')}>
                      <Space.Compact style={{ width: '100%' }}>
                        <Input value={editableFilename} onChange={(event) => setEditableFilename(event.target.value)} />
                        <Button type="primary" loading={renaming} disabled={!editableFilename.trim()} onClick={() => handleRename().catch(() => {})}>
                          {t('rename')}
                        </Button>
                      </Space.Compact>
                    </Form.Item>
                  </Form>

                  <Descriptions bordered size="small" column={1}>
                    <Descriptions.Item label={t('pages')}>{file.total_pages}</Descriptions.Item>
                    <Descriptions.Item label={t('fullPath')}>
                      <span className="break-all">{file.file_path}</span>
                    </Descriptions.Item>
                    <Descriptions.Item label={t('hash')}>
                      <span className="break-all">{file.content_sha256 || '--'}</span>
                    </Descriptions.Item>
                  </Descriptions>
                </Space>
              </GlassSurface>

              <GlassSurface title={t('tags')} extra={tagSaveExtra}>
                <Space direction="vertical" size="middle" className="w-full">
                  <div className="w-full flex flex-col gap-2 sm:flex-row sm:items-start">
                    <div className="flex-1 min-w-0">
                      <TagSelector
                        value={file.tags || []}
                        onChange={(next) => setFile((prev) => (prev ? { ...prev, tags: next } : prev))}
                      />
                    </div>
                    <Tooltip title={t('renameFileOnSaveTip')}>
                      <span className="inline-flex">
                        <Button
                          type="primary"
                          loading={tagSaveStatus === 'saving'}
                          disabled={!file}
                          className="shrink-0"
                          onClick={() => saveTags({ renameFile: true, silent: false }).catch(() => {})}
                        >
                          {t('renameFileOnSave')}
                        </Button>
                      </span>
                    </Tooltip>
                  </div>

                  {tagSaveStatus === 'error' ? <Typography.Text type="danger">{tagSaveError}</Typography.Text> : null}

                  <Divider className="my-0" />

                  {file.tags?.length ? (
                    <Space wrap>
                      {file.tags.map((tag) => (
                        <Tag key={tag.id} color="blue" closable onClose={(event) => {
                          event.preventDefault()
                          removeTag(tag)
                        }}>
                          {tag.name}
                        </Tag>
                      ))}
                    </Space>
                  ) : (
                    <Empty description={t('tagsEmpty')} />
                  )}
                </Space>
              </GlassSurface>

              <GlassSurface title={t('bookmarks')}>
                <Space direction="vertical" size="middle" className="w-full">
                  <Form layout="inline" className="flex flex-wrap gap-2" onFinish={() => addBookmark().catch(() => {})}>
                    <Form.Item label={t('pageNumber')}>
                      <InputNumber
                        value={newBookmarkPage ?? undefined}
                        min={1}
                        max={totalPages || undefined}
                        style={{ width: 120 }}
                        onChange={(value) => setNewBookmarkPage(value === null ? null : Number(value))}
                      />
                    </Form.Item>
                    <Form.Item label={t('note')} className="flex-1 min-w-[240px]">
                      <Input value={newBookmarkNote} placeholder={t('note')} onChange={(event) => setNewBookmarkNote(event.target.value)} />
                    </Form.Item>
                    <Button type="primary" loading={bookmarkSaving} disabled={!newBookmarkPage} onClick={() => addBookmark().catch(() => {})}>
                      {t('add')}
                    </Button>
                  </Form>

                  {bookmarkError ? <Alert type="error" showIcon message={bookmarkError} /> : null}

                  <Table<BookmarkRecord>
                    columns={bookmarkColumns}
                    dataSource={bookmarks}
                    rowKey={(record) => record.id}
                    size="small"
                    pagination={false}
                    locale={{ emptyText: t('noBookmarksYet') }}
                  />
                </Space>
              </GlassSurface>
            </Space>
          ) : null}
        </Spin>
      </Space>
    </GlassPage>
  )
}
