// apps/web/src/components/TaskSettings.vue
<template>
  <a-space direction="vertical" size="middle" class="w-full">
    <a-alert :message="$t('taskSettingsHelp')" type="info" show-icon />

    <a-form layout="vertical" @submit.prevent>
      <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
        <a-form-item :label="$t('taskHistoryLimit')" :help="$t('taskHistoryLimitHelp')">
          <a-input-number
            v-model:value="historyLimitInput"
            :min="10"
            :max="500"
            :step="10"
            style="width: 100%"
            @change="saveHistoryLimit"
          />
        </a-form-item>

        <a-form-item :label="$t('taskHistoryRetentionDays')" :help="$t('taskHistoryRetentionDaysHelp')">
          <a-input-number
            v-model:value="retentionDaysInput"
            :min="0"
            :max="3650"
            :step="1"
            style="width: 100%"
            @change="saveRetentionDays"
          />
        </a-form-item>
      </div>

      <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
        <a-form-item :label="$t('taskNotifyOnComplete')" :help="$t('taskNotifyOnCompleteHelp')">
          <a-switch :checked="appSettingsStore.tasksNotifyOnComplete" @change="appSettingsStore.setTasksNotifyOnComplete" />
        </a-form-item>

        <a-form-item :label="$t('taskNotifyOnFail')" :help="$t('taskNotifyOnFailHelp')">
          <a-switch :checked="appSettingsStore.tasksNotifyOnFail" @change="appSettingsStore.setTasksNotifyOnFail" />
        </a-form-item>
      </div>

      <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
        <a-form-item :label="$t('taskBadgeEnabled')" :help="$t('taskBadgeEnabledHelp')">
          <a-switch :checked="appSettingsStore.tasksBadgeEnabled" @change="appSettingsStore.setTasksBadgeEnabled" />
        </a-form-item>

        <a-form-item :label="$t('taskHistoryCleanup')" :help="$t('taskHistoryCleanupHelp')">
          <a-popconfirm
            :title="$t('confirmCleanupTasks', { days: appSettingsStore.tasksHistoryRetentionDays })"
            :ok-text="$t('confirm')"
            :cancel-text="$t('cancel')"
            @confirm="cleanupHistory"
          >
            <a-button danger :loading="cleaning">
              {{ $t('cleanupHistory') }}
            </a-button>
          </a-popconfirm>
        </a-form-item>
      </div>
    </a-form>
  </a-space>
</template>

<script setup>
import { ref, watch } from 'vue'
import axios from 'axios'
import { message } from 'ant-design-vue'
import { useI18n } from 'vue-i18n'
import { useAppSettingsStore } from '@/store/appSettings'
import { useLibraryStore } from '@/store/library'

const { t } = useI18n()
const appSettingsStore = useAppSettingsStore()
const libraryStore = useLibraryStore()

const historyLimitInput = ref(appSettingsStore.tasksHistoryLimit)
const retentionDaysInput = ref(appSettingsStore.tasksHistoryRetentionDays)
const cleaning = ref(false)

watch(
  () => appSettingsStore.tasksHistoryLimit,
  (value) => {
    historyLimitInput.value = value
  }
)

watch(
  () => appSettingsStore.tasksHistoryRetentionDays,
  (value) => {
    retentionDaysInput.value = value
  }
)

const saveHistoryLimit = async () => {
  await appSettingsStore.setTasksHistoryLimit(historyLimitInput.value)
  await libraryStore.checkActiveTasks()
}

const saveRetentionDays = async () => {
  await appSettingsStore.setTasksHistoryRetentionDays(retentionDaysInput.value)
}

const cleanupHistory = async () => {
  cleaning.value = true
  try {
    const response = await axios.delete('/api/v1/task-history', {
      data: { days: appSettingsStore.tasksHistoryRetentionDays }
    })
    message.success(response.data?.message || t('cleanupHistorySuccess'))
    await libraryStore.checkActiveTasks()
  } catch (error) {
    console.error('清理历史任务失败:', error)
    message.error(error.response?.data?.error || t('cleanupHistoryFailed'))
  } finally {
    cleaning.value = false
  }
}
</script>

// apps/web/src/components/tasks/TaskSettings.tsx
import { Alert, Button, Form, InputNumber, Popconfirm, Space, Switch, message } from 'antd'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { http } from '@/api/http'
import { useAppSettingsStore } from '@/store/appSettings'
import { useLibraryStore } from '@/store/library'

export default function TaskSettings() {
  const { t } = useTranslation()

  const tasksHistoryLimit = useAppSettingsStore((state) => state.tasksHistoryLimit)
  const tasksHistoryRetentionDays = useAppSettingsStore((state) => state.tasksHistoryRetentionDays)
  const tasksNotifyOnComplete = useAppSettingsStore((state) => state.tasksNotifyOnComplete)
  const tasksNotifyOnFail = useAppSettingsStore((state) => state.tasksNotifyOnFail)
  const tasksBadgeEnabled = useAppSettingsStore((state) => state.tasksBadgeEnabled)

  const setTasksHistoryLimit = useAppSettingsStore((state) => state.setTasksHistoryLimit)
  const setTasksHistoryRetentionDays = useAppSettingsStore((state) => state.setTasksHistoryRetentionDays)
  const setTasksNotifyOnComplete = useAppSettingsStore((state) => state.setTasksNotifyOnComplete)
  const setTasksNotifyOnFail = useAppSettingsStore((state) => state.setTasksNotifyOnFail)
  const setTasksBadgeEnabled = useAppSettingsStore((state) => state.setTasksBadgeEnabled)

  const checkActiveTasks = useLibraryStore((state) => state.checkActiveTasks)

  const [historyLimitInput, setHistoryLimitInput] = useState(tasksHistoryLimit)
  const [retentionDaysInput, setRetentionDaysInput] = useState(tasksHistoryRetentionDays)
  const [cleaning, setCleaning] = useState(false)

  useEffect(() => {
    setHistoryLimitInput(tasksHistoryLimit)
  }, [tasksHistoryLimit])

  useEffect(() => {
    setRetentionDaysInput(tasksHistoryRetentionDays)
  }, [tasksHistoryRetentionDays])

  const saveHistoryLimit = async () => {
    await setTasksHistoryLimit(historyLimitInput)
    await checkActiveTasks()
  }

  const saveRetentionDays = async () => {
    await setTasksHistoryRetentionDays(retentionDaysInput)
  }

  const cleanupHistory = async () => {
    setCleaning(true)
    try {
      const response = await http.delete('/api/v1/task-history', {
        data: { days: tasksHistoryRetentionDays }
      })
      message.success(response?.data?.message || t('cleanupHistorySuccess'))
      await checkActiveTasks()
    } catch (error) {
      console.error('清理历史任务失败：', error)
      message.error((error as any)?.response?.data?.error || t('cleanupHistoryFailed'))
    } finally {
      setCleaning(false)
    }
  }

  return (
    <Space direction="vertical" size="middle" className="w-full">
      <Alert message={t('taskSettingsHelp')} type="info" showIcon />

      <Form layout="vertical">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <Form.Item label={t('taskHistoryLimit')} help={t('taskHistoryLimitHelp')}>
            <InputNumber
              min={10}
              max={500}
              step={10}
              style={{ width: '100%' }}
              value={historyLimitInput}
              onChange={(value) => setHistoryLimitInput(Number(value ?? 0))}
              onBlur={() => saveHistoryLimit().catch(() => {})}
            />
          </Form.Item>

          <Form.Item label={t('taskHistoryRetentionDays')} help={t('taskHistoryRetentionDaysHelp')}>
            <InputNumber
              min={0}
              max={3650}
              step={1}
              style={{ width: '100%' }}
              value={retentionDaysInput}
              onChange={(value) => setRetentionDaysInput(Number(value ?? 0))}
              onBlur={() => saveRetentionDays().catch(() => {})}
            />
          </Form.Item>
        </div>

        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <Form.Item label={t('taskNotifyOnComplete')} help={t('taskNotifyOnCompleteHelp')}>
            <Switch checked={tasksNotifyOnComplete} onChange={(value) => setTasksNotifyOnComplete(value).catch(() => {})} />
          </Form.Item>

          <Form.Item label={t('taskNotifyOnFail')} help={t('taskNotifyOnFailHelp')}>
            <Switch checked={tasksNotifyOnFail} onChange={(value) => setTasksNotifyOnFail(value).catch(() => {})} />
          </Form.Item>
        </div>

        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <Form.Item label={t('taskBadgeEnabled')} help={t('taskBadgeEnabledHelp')}>
            <Switch checked={tasksBadgeEnabled} onChange={(value) => setTasksBadgeEnabled(value).catch(() => {})} />
          </Form.Item>

          <Form.Item label={t('taskHistoryCleanup')} help={t('taskHistoryCleanupHelp')}>
            <Popconfirm
              title={t('confirmCleanupTasks', { days: tasksHistoryRetentionDays })}
              okText={t('confirm')}
              cancelText={t('cancel')}
              okButtonProps={{ danger: true }}
              onConfirm={() => cleanupHistory().catch(() => {})}
            >
              <Button danger loading={cleaning}>
                {t('cleanupHistory')}
              </Button>
            </Popconfirm>
          </Form.Item>
        </div>
      </Form>
    </Space>
  )
}
