// apps/web/src/pages/LikeView.tsx
import { Empty, Spin } from 'antd'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { http } from '@/api/http'
import GlassPage from '@/components/glass/ui/GlassPage'
import GlassSurface from '@/components/glass/ui/GlassSurface'
import MangaCard, { type MangaItem } from '@/components/library/MangaCard'
import MangaGrid from '@/components/library/MangaGrid'

export default function LikeView() {
  const { t } = useTranslation()
  const [likedItems, setLikedItems] = useState<MangaItem[]>([])
  const [loading, setLoading] = useState(true)
  const [errorMessage, setErrorMessage] = useState('')

  const fetchLikes = async () => {
    setLoading(true)
    setErrorMessage('')
    try {
      const response = await http.get('/api/v1/likes')
      const list = (response?.data || []) as MangaItem[]
      setLikedItems(list.map((item) => ({ ...item, is_liked: true })))
    } catch (error) {
      console.error('加载喜欢列表失败：', error)
      const messageText = (error as any)?.response?.data?.error || t('loadingWishlist')
      setErrorMessage(String(messageText))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchLikes().catch(() => {})
  }, [])

  return (
    <GlassPage>
      <GlassSurface>
        {loading ? (
          <div className="w-full flex justify-center py-10">
            <Spin />
          </div>
        ) : errorMessage ? (
          <Empty description={errorMessage} className="py-12" />
        ) : likedItems.length ? (
          <MangaGrid>
            {likedItems.map((manga) => (
              <MangaCard key={manga.id} manga={manga} hideWishlistButton viewMode="grid" />
            ))}
          </MangaGrid>
        ) : (
          <Empty description={t('wishlistEmpty')} className="py-12" />
        )}
      </GlassSurface>
    </GlassPage>
  )
}

// frontend/src/views/LikeView.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import axios from 'axios'
import { message } from 'ant-design-vue'
import MangaCard from '../components/MangaCard.vue'
import MangaGrid from '@/components/MangaGrid.vue'

const likedItems = ref([])
const isLoading = ref(true)
const { t } = useI18n()

const fetchLikes = async () => {
  isLoading.value = true
  try {
    const response = await axios.get('/api/v1/likes')
    likedItems.value = response.data.map(item => ({ ...item, is_liked: true }))
  } catch (error) {
    console.error('Failed to fetch liked items:', error)
    message.error(t('loadingWishlist'))
  } finally {
    isLoading.value = false
  }
}

onMounted(fetchLikes)
</script>

<template>
  <a-card :title="$t('myWishlist')" class="shadow-sm">
    <a-spin v-if="isLoading" class="w-full flex justify-center py-10" />
    <template v-else>
      <MangaGrid v-if="likedItems.length">
        <MangaCard
          v-for="manga in likedItems"
          :key="manga.id"
          :manga="manga"
          :hide-wishlist-button="true"
        />
      </MangaGrid>
      <a-empty v-else :description="$t('wishlistEmpty')" class="py-12" />
    </template>
  </a-card>
</template>
