// apps/web/src/pages/settings/SettingsLibraryView.tsx
import { Space } from 'antd'
import { useTranslation } from 'react-i18next'
import GlassPage from '@/components/glass/ui/GlassPage'
import GlassSurface from '@/components/glass/ui/GlassSurface'
import LibraryBrowseSettings from '@/components/library/LibraryBrowseSettings'
import RenameTemplateSettings from '@/components/library/RenameTemplateSettings'
import ScannerSettings from '@/components/library/ScannerSettings'

export default function SettingsLibraryView() {
  const { t } = useTranslation()

  return (
    <GlassPage>
      <Space direction="vertical" size="large" className="w-full">
        <ScannerSettings />

        <GlassSurface title={t('libraryBrowseSettings')}>
          <LibraryBrowseSettings />
        </GlassSurface>

        <GlassSurface title={t('renameSettings')}>
          <RenameTemplateSettings />
        </GlassSurface>
      </Space>
    </GlassPage>
  )
}

// frontend/src/views/SettingsLibraryView.vue
<template>
  <GlassPage :title="$t('librarySettings')">
    <a-space direction="vertical" size="large" class="w-full">
      <ScannerSettings />

      <GlassSurface :title="$t('libraryBrowseSettings')">
        <LibraryBrowseSettings />
      </GlassSurface>

      <GlassSurface :title="$t('renameSettings')">
        <RenameTemplateSettings />
      </GlassSurface>
    </a-space>
  </GlassPage>
</template>

<script setup>
import ScannerSettings from '@/components/ScannerSettings.vue'
import LibraryBrowseSettings from '@/components/LibraryBrowseSettings.vue'
import RenameTemplateSettings from '@/components/RenameTemplateSettings.vue'
import GlassPage from '@/components/glass/ui/GlassPage.vue'
import GlassSurface from '@/components/glass/ui/GlassSurface.vue'
</script>
