// apps/web/src/pages/settings/SettingsAdvancedView.tsx
import { Alert, Button, Form, Input, Modal, Space, Table, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { http } from '@/api/http'
import GlassPage from '@/components/glass/ui/GlassPage'
import GlassSurface from '@/components/glass/ui/GlassSurface'

type SettingRow = {
  key: string
  value: string
}

export default function SettingsAdvancedView() {
  const { t } = useTranslation()

  const [loading, setLoading] = useState(false)
  const [keyword, setKeyword] = useState('')
  const [rows, setRows] = useState<SettingRow[]>([])

  const [modalOpen, setModalOpen] = useState(false)
  const [modalMode, setModalMode] = useState<'create' | 'edit'>('create')
  const [modalSaving, setModalSaving] = useState(false)
  const [modalKey, setModalKey] = useState('')
  const [modalValue, setModalValue] = useState('')

  const refresh = useCallback(async () => {
    setLoading(true)
    try {
      const response = await http.get('/api/v1/settings')
      const settings = (response?.data || {}) as Record<string, unknown>
      setRows(
        Object.keys(settings)
          .sort((a, b) => a.localeCompare(b))
          .map((key) => ({ key, value: String(settings[key] ?? '') }))
      )
    } catch (error) {
      console.error('加载高级设置失败：', error)
      message.error(t('failedToFetchSettings'))
    } finally {
      setLoading(false)
    }
  }, [t])

  useEffect(() => {
    refresh().catch(() => {})
  }, [refresh])

  const filteredRows = useMemo(() => {
    const q = keyword.trim().toLowerCase()
    if (!q) {
      return rows
    }
    return rows.filter((item) => item.key.toLowerCase().includes(q))
  }, [keyword, rows])

  const openCreateModal = () => {
    setModalMode('create')
    setModalKey('')
    setModalValue('')
    setModalOpen(true)
  }

  const openEditModal = (record: SettingRow) => {
    setModalMode('edit')
    setModalKey(record.key)
    setModalValue(record.value)
    setModalOpen(true)
  }

  const closeModal = () => {
    setModalOpen(false)
  }

  const saveModal = async () => {
    if (!modalKey.trim()) {
      message.warning(t('pleaseEnterSettingKey'))
      return
    }
    setModalSaving(true)
    try {
      await http.put(`/api/v1/settings/${modalKey.trim()}`, { value: modalValue })
      message.success(t('settingsSavedSuccessfully'))
      setModalOpen(false)
      await refresh()
    } catch (error) {
      console.error('保存高级设置失败：', error)
      message.error((error as any)?.response?.data?.error || t('failedToSaveSettings'))
    } finally {
      setModalSaving(false)
    }
  }

  const resetOverride = (key: string) => {
    Modal.confirm({
      title: t('confirmResetSetting'),
      okType: 'danger',
      okText: t('confirm'),
      cancelText: t('cancel'),
      onOk: async () => {
        try {
          await http.delete(`/api/v1/settings/${key}`)
          message.success(t('settingsSavedSuccessfully'))
          await refresh()
        } catch (error) {
          console.error('重置设置失败：', error)
          message.error(t('failedToSaveSettings'))
        }
      }
    })
  }

  const columns: ColumnsType<SettingRow> = useMemo(
    () => [
      { title: t('settingKey'), dataIndex: 'key', key: 'key', width: 340 },
      {
        title: t('settingValue'),
        dataIndex: 'value',
        key: 'value',
        render: (value: string) => (
          <Typography.Text code className="break-all">
            {value}
          </Typography.Text>
        )
      },
      {
        title: t('actions'),
        key: 'actions',
        width: 200,
        render: (_value, record) => (
          <Space>
            <Button size="small" onClick={() => openEditModal(record)}>
              {t('edit')}
            </Button>
            <Button size="small" danger onClick={() => resetOverride(record.key)}>
              {t('resetToDefault')}
            </Button>
          </Space>
        )
      }
    ],
    [t]
  )

  return (
    <GlassPage>
      <Space direction="vertical" size="large" className="w-full">
        <GlassSurface>
          <Space direction="vertical" size="middle" className="w-full">
            <Alert message={t('advancedSettingsHelp')} type="info" showIcon />

            <div className="flex flex-wrap gap-3 items-center justify-between">
              <Input.Search
                value={keyword}
                onChange={(event) => setKeyword(event.target.value)}
                placeholder={t('searchSettingsPlaceholder')}
                allowClear
                style={{ maxWidth: 420 }}
                onSearch={() => refresh().catch(() => {})}
              />
              <Space>
                <Button loading={loading} onClick={() => refresh().catch(() => {})}>
                  {t('refresh')}
                </Button>
                <Button type="primary" onClick={openCreateModal}>
                  {t('add')}
                </Button>
              </Space>
            </div>

            <Table
              dataSource={filteredRows}
              columns={columns}
              loading={loading}
              rowKey={(row) => row.key}
              size="middle"
              pagination={{ pageSize: 50 }}
            />
          </Space>
        </GlassSurface>
      </Space>

      <Modal
        open={modalOpen}
        title={modalMode === 'create' ? t('addSetting') : t('editSetting')}
        confirmLoading={modalSaving}
        onOk={() => saveModal().catch(() => {})}
        onCancel={closeModal}
        okText={t('save')}
        cancelText={t('cancel')}
      >
        <Form layout="vertical">
          <Form.Item label={t('settingKey')} required>
            <Input value={modalKey} disabled={modalMode === 'edit'} onChange={(event) => setModalKey(event.target.value)} />
          </Form.Item>
          <Form.Item label={t('settingValue')} required>
            <Input.TextArea
              value={modalValue}
              autoSize={{ minRows: 2, maxRows: 10 }}
              onChange={(event) => setModalValue(event.target.value)}
            />
          </Form.Item>
        </Form>
      </Modal>
    </GlassPage>
  )
}

// frontend/src/views/SettingsAdvancedView.vue
<template>
  <div class="p-4 md:p-8">
    <a-space direction="vertical" size="large" class="w-full">
      <a-typography-title :level="2" class="!mb-0">
        {{ $t('advancedSettings') }}
      </a-typography-title>

      <a-card :bordered="false">
        <a-space direction="vertical" size="middle" class="w-full">
          <a-alert :message="$t('advancedSettingsHelp')" type="info" show-icon />

          <div class="flex flex-wrap gap-3 items-center justify-between">
            <a-input-search
              v-model:value="keyword"
              :placeholder="$t('searchSettingsPlaceholder')"
              allow-clear
              style="max-width: 420px"
              @search="refresh"
            />
            <a-space>
              <a-button :loading="loading" @click="refresh">
                {{ $t('refresh') }}
              </a-button>
              <a-button type="primary" @click="openCreateModal">
                {{ $t('add') }}
              </a-button>
            </a-space>
          </div>

          <a-table
            :data-source="filteredRows"
            :columns="columns"
            :loading="loading"
            :row-key="row => row.key"
            size="middle"
            :pagination="{ pageSize: 50 }"
          >
            <template #bodyCell="{ column, record }">
              <template v-if="column.key === 'value'">
                <a-typography-text code class="break-all">
                  {{ record.value }}
                </a-typography-text>
              </template>
              <template v-else-if="column.key === 'actions'">
                <a-space>
                  <a-button size="small" @click="openEditModal(record)">
                    {{ $t('edit') }}
                  </a-button>
                  <a-button size="small" danger @click="resetOverride(record.key)">
                    {{ $t('resetToDefault') }}
                  </a-button>
                </a-space>
              </template>
            </template>
          </a-table>
        </a-space>
      </a-card>
    </a-space>

    <a-modal
      v-model:open="modalOpen"
      :title="modalMode === 'create' ? $t('addSetting') : $t('editSetting')"
      :confirm-loading="modalSaving"
      @ok="saveModal"
      @cancel="closeModal"
    >
      <a-form layout="vertical">
        <a-form-item :label="$t('settingKey')" required>
          <a-input v-model:value="modalKey" :disabled="modalMode === 'edit'" />
        </a-form-item>
        <a-form-item :label="$t('settingValue')" required>
          <a-textarea v-model:value="modalValue" :auto-size="{ minRows: 2, maxRows: 10 }" />
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import axios from 'axios'
import { message, Modal } from 'ant-design-vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const loading = ref(false)
const keyword = ref('')
const rows = ref([])

const modalOpen = ref(false)
const modalMode = ref('create')
const modalSaving = ref(false)
const modalKey = ref('')
const modalValue = ref('')

const columns = computed(() => [
  { title: t('settingKey'), dataIndex: 'key', key: 'key', width: 340 },
  { title: t('settingValue'), dataIndex: 'value', key: 'value' },
  { title: t('actions'), key: 'actions', width: 200 }
])

const filteredRows = computed(() => {
  const q = (keyword.value || '').trim().toLowerCase()
  if (!q) {
    return rows.value
  }
  return rows.value.filter(item => item.key.toLowerCase().includes(q))
})

const refresh = async () => {
  loading.value = true
  try {
    const response = await axios.get('/api/v1/settings')
    const settings = response.data || {}
    rows.value = Object.keys(settings)
      .sort((a, b) => a.localeCompare(b))
      .map(key => ({ key, value: String(settings[key] ?? '') }))
  } catch (error) {
    console.error('加载高级设置失败：', error)
    message.error(t('failedToFetchSettings'))
  } finally {
    loading.value = false
  }
}

const openCreateModal = () => {
  modalMode.value = 'create'
  modalKey.value = ''
  modalValue.value = ''
  modalOpen.value = true
}

const openEditModal = (record) => {
  modalMode.value = 'edit'
  modalKey.value = record.key
  modalValue.value = record.value
  modalOpen.value = true
}

const closeModal = () => {
  modalOpen.value = false
}

const saveModal = async () => {
  if (!modalKey.value.trim()) {
    message.warning(t('pleaseEnterSettingKey'))
    return
  }
  modalSaving.value = true
  try {
    await axios.post(`/api/v1/settings/${modalKey.value.trim()}`, { value: modalValue.value })
    message.success(t('settingsSavedSuccessfully'))
    modalOpen.value = false
    await refresh()
  } catch (error) {
    console.error('保存高级设置失败：', error)
    message.error(error.response?.data?.error || t('failedToSaveSettings'))
  } finally {
    modalSaving.value = false
  }
}

const resetOverride = (key) => {
  Modal.confirm({
    title: t('confirmResetSetting'),
    okType: 'danger',
    onOk: async () => {
      try {
        await axios.delete(`/api/v1/settings/${key}`)
        message.success(t('settingsSavedSuccessfully'))
        await refresh()
      } catch (error) {
        console.error('重置设置失败：', error)
        message.error(t('failedToSaveSettings'))
      }
    }
  })
}

onMounted(refresh)
</script>
